### ISSUE TITLE
[Question] Cannot debug iOS since updating to VS 16.5.0

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#10070]
Ever since I've updated to VS2019 16.5.0 I've been unable to debug our iOS apps.
This 16.5.0 windows release had mismatched mono and xamarin components to the mac release (which was still on the previous point version). 
It connects, builds, deploys, runs the app. but shortly after the app starts, a VS popup appears with this exception
```
Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadPdbFile(String assemblyFileName, String pdbFileName) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2812
   at Mono.Debugging.Soft.SoftDebuggerSession.LoadDebugFile(String assemblyFileName, String debugFileName, Func`3 loadDebugFile) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2912
   at Mono.Debugging.Soft.SoftDebuggerSession.CheckBetterMatch(TypeMirror type, String file, Int32 line, Int32 column, Location found) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2939
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByMethod(MethodMirror method, String file, Int32 line, Int32 column, Boolean& insideTypeRange) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 3114
   at Mono.Debugging.Soft.SoftDebuggerSession.FindLocationByType(TypeMirror type, String file, Int32 line, Int32 column, Boolean& genericMethod, Boolean& insideTypeRange) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 3132
   at Mono.Debugging.Soft.SoftDebuggerSession.ResolveBreakpoints(TypeMirror type) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2625
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleTypeLoadEvents(TypeLoadEvent[] events) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2179
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1718
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in E:\A\_work\2914\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1640
```

Now that the 8.5 mac version has been released, it's the mac version that is ahead of the windows components and it still doesn't debug, throwing the same error.
If I just run the app (no debugging), it launches and runs fine.

Has anyone had a similar issue, any ideas on what I can do to fix this?

**Comment by MitchBomcanhao** [comment]
![image](https://user-images.githubusercontent.com/31066938/77430119-93e46500-6dd2-11ea-9cec-02bb528c862a.png)

**Comment by pedromocoramalho** [comment]
I have de same problem. And after upgrade to 16.5.1 a have other problem de xaml file don't appear on add new item.

**Comment by PureWeen** [comment]
@MitchBomcanhao @pmramalho can you try the latest VS mac 8.5?

If that still doesn't work can you use the Report a Problem button in the top right corner of VS?

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

**Comment by pmramalho** [comment]
I do that. I'm waiting for anwer.
https://developercommunity.visualstudio.com/content/problem/960868/xamarin-forms-exception-systeminvalidoperationexce.html?childToView=964125#comment-964125

**Comment by MitchBomcanhao** [comment]
This issue has magically gone away while I was stepping through the application's initialisation. It looked like the error popup consistently came after running a specific bit of code, and after stepping through the app never failed again.

no idea what was wrong, or what changed to fix it.
