### ISSUE TITLE
[Bug]Upgrading Xamarin.Forms.Visual.Material to 4.5 breaks Android build 

### ISSUE THREAD

**Issue by stefanhk31** [xamarin/Xamarin.Forms#10223]
### Description

After upgrading Xamarin.Forms.Visual.Material from 4.3.0.991211 to 4.5.0.530, my build fails with the following error: 

```
    Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Material.Android.MaterialColors::ApplySeekBarColors(Android.Widget.AbsSeekBar,Xamarin.Forms.Color,Xamarin.Forms.Color,Xamarin.Forms.Color)' in assembly: 'Xamarin.Forms.Material.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.DrawableExtensions::SetColorFilter(Android.Graphics.Drawables.Drawable,Android.Graphics.Color,Xamarin.Forms.Platform.Android.FilterMode)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute() (1, 1)
```

Couldn't find any specific breaking change to Visual Material that would be causing this.

Project clean/build and deleting bin/obj folders/build doesn't fix it. Only solution I've found now is to roll back to 4.3. 

- Version with issue: 4.5.0.530
- Last known good version: 4.3.0.991211
- IDE: Visual Studio Community 2019
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages: Xamarin.Forms.Visual.Material

**Comment by PureWeen** [comment]
@stefanhk31 
do you have a repro? This exception sounds like you have mismatched versions of forms.  `SetColorFilter` was added in XF 4.5 so if you have a 4.3 version of forms mixed with 4.5 you'll see this exception

**Comment by stefanhk31** [comment]
So, checked it out again...turns out that it was actually an issue with running XF 4.5 and Visual.Material 4.3. Sorry for the confusion, but it appears to be user error.
