### ISSUE TITLE
[Bug] [Tizen] NullReferenceException in VisualElementRenderer.ComputeAbsoluteX(VisualElement e) 

### ISSUE THREAD

**Issue by SHuygh** [xamarin/Xamarin.Forms#10427]
### Description

We are using Xamarin Forms to make a Tizen watch application. But are getting app crashes for which I do not have an immediate idea how to fix them.
Below you can find the stack trace.

at Xamarin.Forms.Platform.Tizen.VisualElementRenderer1.ComputeAbsoluteX(VisualElement e) at Xamarin.Forms.Platform.Tizen.VisualElementRenderer1.ComputeAbsolutePoint(VisualElement e)
at Xamarin.Forms.Platform.Tizen.VisualElementRenderer1.UpdateNativeGeometry() at Xamarin.Forms.Platform.Tizen.VisualElementRenderer1.UpdateLayout()
at Xamarin.Forms.Platform.Tizen.VisualElementRenderer1.OnBatchCommitted(Object sender, EventArg1 e)
at Xamarin.Forms.VisualElement.BatchCommit()
at Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)
at Xamarin.Forms.VisualElement.Layout(Rectangle bounds)
at Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.OnLayout()
at ElmSharp.Box.<>cDisplayClass14_0.<SetLayoutCallback>b0(IntPtr obj, IntPtr priv, IntPtr data)
at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
at Tizen.Applications.CoreApplication.Run(String[] args)
at Tizen.Applications.CoreUIApplication.Run(String[] args)

The relevant code can be found here https://github.com/xamarin/Xamarin.Forms/blob/4.3.0/Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs#L655-L658
The VisualElement should not be null as we already block dispose being called from the background thread due to a custom implementation and the CirclePageRenderer.OnLayout() quick returns after dispose.

I suspect that Platform.GetRenderer(e.RealParent) might be null. However, I am not able to find a specific code path which could cause this issue.

We are not capable of finding a reproducible scenario as it both occurs while the user is using the app, or leaves the application open for some time without any actions. It is not caused due to navigation as it would not happen at that time.

### Expected Behavior
- No null reference exception is thrown

### Actual Behavior
- Null reference exception is thrown

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Tizen: tizen40
- Nuget Packages:
  - Autofac "Version="4.8.1"
  - Fody" Version="6.0.4"
  - Newtonsoft.Json Version="12.0.1" 
  - PropertyChanged.Fody Version="3.1.3"
  - Xamarin.Forms Version="4.3.0.947036"
- Affected Devices: Samsung Galaxy Watch

**Comment by rookiejava** [comment]
Thank you for reaching out. 

It is difficult to determine the cause from the description. However, according to the stack trace, it seems to be a CirclePageRenderer issue not Xamarin.Forms itself. I would appreciate if you could transfer the issue to [CircularUI](https://github.com/Samsung/Tizen.CircularUI) project home for further investigation. 

Plus, could you share the relevant app code that I can reproduce? This would be helpful to figure out the reason.
