### ISSUE TITLE
[Bug] WPF runtime issue

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#10489]
### Description

FileNotFoundException: Could not load file or assembly 'Xamarin.Forms.Platform.WPF, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### Steps to Reproduce

1. Create netcoreapp5.0 app or netcoreapp3.1
2. restore nuget packages (Xamarin.Forms, Xamarin.Forms.Platform.WPF)
3. Create MainPage OnStart
```
var page = new ContentPage();
            var stack = new StackLayout();
            stack.Children.Add(new Label() { Text = "12" });
            page.Content = stack;
            MainPage = new NavigationPage(page);
```
3. Maximize window

### Expected Behavior
app runs

### Actual Behavior
content is not rendered
crash
```
   at System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
   at System.Windows.FrameworkElement.AddLogicalChild(Object child)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at Xamarin.Forms.Platform.WPF.ScrollViewRenderer.LoadContent()
   at Xamarin.Forms.Platform.WPF.ScrollViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.PageRenderer.UpdateContent()
   at Xamarin.Forms.Platform.WPF.PageRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.CreateOrResizeContent(FrameworkElement parent, VisualElement visualElement)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.OnSizeContentChanged(FrameworkElement parent, Object page)
   at Xamarin.Forms.Platform.WPF.Controls.FormsContentControl.LightContentControl_SizeChanged(Object sender, SizeChangedEventArgs e)
   at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

### Basic Information

- Nuget Packages: 4.8.0-740-nightly

**Comment by hartez** [comment]
You need to use a .NET Framework WPF app with Forms.

**Comment by VladislavAntonyuk** [comment]
@hartez there was a PR to update allow use .NET CORE with WPF

**Comment by hartez** [comment]
@VladislavAntonyuk You are correct. And the PR was merged on the 15th, and that nightly was built on the 23rd. So the support should be there.

**Comment by VladislavAntonyuk** [comment]
@hartez I updated to 4.8 build, and was able to run the app, but the content is not rendered and on window maximize app crashes.
the same code for net462 works

**Comment by VladislavAntonyuk** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/2704

**Comment by PureWeen** [comment]
@VladislavAntonyuk Can you confirm if the PR you did here worked for you when running the WPF ControlGallery?

https://github.com/xamarin/Xamarin.Forms/pull/10736

Currently the WPF Gallery doesn't run it just crashes with a cannot find dll error.

The gallery works fine before #10736 but not after it so I wonder if the netcoreapp3.1 targets have ever really worked

**Comment by VladislavAntonyuk** [comment]
It worked on my dev env. I also use net5 now with nightly build for wpf and it works

**Comment by VladislavAntonyuk** [comment]
I decided not to close it because we have an issue with ControlGallery. But I still can build and execute it locally. Could it be some kind of cached data?

**Comment by VladislavAntonyuk** [comment]
Well I see, modify line 3 of csproj to netcoreapp3.1 (remove net461) and now it works. But works fine with net5.0
