### ISSUE TITLE
[Bug] System.IO.IOException: The process cannot access the file 'C:\Project\100\android\assets\xxxx.dll' because it is being used by another process.

### ISSUE THREAD

**Issue by pmahend1** [xamarin/Xamarin.Forms#10529]
### Description
Android project in Xamarin forms does not build 
Gives the error System.IO.IOException: The process cannot access the file 'C:\Project\100\android\assets\xxxx.dll' because it is being used by another process. where xxxx is different every different try of build 

### Steps to Reproduce

1. Create new Xamarin forms project on Visual Studio Windows
2. Build 

### Expected Behavior
All projects should build

### Actual Behavior
Android project does not build only on VIsual Studio windows , but builds on Visual Studio Mac

```log
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.IOException: The process cannot access the file '

C:\Source\DevPrateek\src\ProjectName.Mobile.Droid\obj\Debug\100\android\assets\Plugin.Media.dll
' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	ProjectName.Mobile.Droid			
```
### Basic Information

- Version with issue: NA
- Last known good version: NA
- IDE:only Visual Studio Windows 
- Platform Target Frameworks: 
  - iOS:   NA
  - Android:  10 SDK 29 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin forms Xamarin essentials latest
- Affected Devices: Android

### Reproduction Link
NA

### Workaround
No work around at this time, trying to build project varius changes and seeing if anything works.

**Comment by hartez** [comment]
@pmahend1 Which version of Visual Studio are you using? Have you tried restarting the machine?

**Comment by pmahend1** [comment]
@hartez Latest stable version of Visual Studio 16.5.4 .Tried all the things I could think of like deleting bin obj . deleting .vs folder, reinstalling Visual studio , changing Visual studio build settings, changing project references, changing Android build options. None seem to work

**Comment by hartez** [comment]
But you did try a restart? I only ask because I've run into the same issue and was able to fix it by restarting the machine - I suspect it was either a rogue MSBuild process or a hung instance of devenv.exe that was causing it. 

The other thing I'd suggest is setting your max number of parallel build processes to see if that fixes it. Try setting it to 1.

![image](https://user-images.githubusercontent.com/538025/80767778-f2091400-8b05-11ea-9deb-d6d27264de13.png)

(I'm only suggesting the last option as a temporary workaround; obviously, that's not an acceptable long-term solution. But if it works, that'll be a good data point for me to pass on to the Android team.)

**Comment by pmahend1** [comment]
My colleague suggested it and I tried it, dint work. Seemed to work for him. I have restarted laptop multiple times, but after doing this change I believe I have not restarted my laptop. Will give it a try tomorrow morning.

**Comment by pmahend1** [comment]
@hartez restarting doesnt do anything. Android build disabling **shared runtime** yields the error `The last access/last write time on file "obj\Debug\90\android\bin\mono.android.jar" cannot be set. The process cannot access the file 'C:\Source\App4\App4\App4.Android\obj\Debug\90\android\bin\mono.android.jar' because it is being used by another process.	App4.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1804	`
