### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MichaelNovikov** [xamarin/Xamarin.Forms#10599]
### Description
Can't compile my application o anymore in Visual Studio 16.5.34

Severity	Code	Description	Project	File	Line	Suppression State
Error		XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Collections.DictionaryEntry NLog.Internal.DictionaryAdapter`2/MyEnumerator::get_Entry()' in assembly: 'NLog.dll' ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Mono.Cecil.MetadataReader.GetTypeSpecification(UInt32 rid)
   at Mono.Cecil.MetadataReader.LookupToken(MetadataToken token)
   at Mono.Cecil.MetadataReader.ReadTypeMemberReference(MetadataToken type, String name, UInt32 signature)
   at Mono.Cecil.MetadataReader.ReadMemberReference(UInt32 rid)
   at Mono.Cecil.MetadataReader.GetMemberReference(UInt32 rid)
   at Mono.Cecil.MetadataReader.LookupToken(MetadataToken token)
   at Mono.Cecil.Cil.CodeReader.ReadOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeReader.ReadCode()
   at Mono.Cecil.Cil.CodeReader.ReadFatMethod()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()		 	0

**Comment by StephaneDelcroix** [comment]
we'd need to know if it's an android or iOS app, we'd need a real reproduction project... and then we won't be able to help you but we'll redirect this issue to either xamarin-android or ios

**Comment by MichaelNovikov** [comment]
> we'd need to know if it's an android or iOS app, we'd need a real reproduction project... and then we won't be able to help you but we'll redirect this issue to either xamarin-android or ios

Of course! The description says that this is an android project.

**Comment by Flaviocrtt** [comment]
@MichaelNovikov Did you found a work around?

**Comment by samhouts** [comment]
@MichaelNovikov Please tell us what your complete version info is (https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/version-logs#version-information), and also what version of Xamarin.Forms you're using. Can you please attach a small project that demonstrates this issue? Thanks!
