### ISSUE TITLE
[Bug] Crash with Android 5.x and x64 devices

### ISSUE THREAD

**Issue by stevecluk** [xamarin/Xamarin.Forms#10613]
### Description
I have an app that's been in the Play Store for a few years now. It was recently updated with the latest nugets and Forms, and the Pre-Launch report started showing crashes in the Huawei p8 Lite.
The crash only seems to happen on x64 devices (and emulators) that are running Android 5.0 or 5.1.  Android 5.x 32-bit devices, and all 6+ devices are fine.

The main crash I was seeing was a result of trying to check if a folder exists from the MainActivity's OnCreate(), showing a Dll issue: 
android.runtime.JavaProxyThrowable: System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
  at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <ac2cc6a1f7c64bf5b08e0682cda293fb>:0 
  at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <ac2cc6a1f7c64bf5b08e0682cda293fb>:0 
  at System.IO.FileSystem.DirectoryExists (System.ReadOnlySpan`1[T] fullPath, Interop+ErrorInfo& errorInfo) [0x00000] in <ac2cc6a1f7c64bf5b08e0682cda293fb>:0 
  at System.IO.FileSystem.DirectoryExists (System.ReadOnlySpan`1[T] fullPath) [0x00000] in <ac2cc6a1f7c64bf5b08e0682cda293fb>:0 
  at System.IO.Directory.Exists (System.String path) [0x0001e] in <ac2cc6a1f7c64bf5b08e0682cda293fb>:0 

To reproduce the problem, I'd created an empty Xamarin Forms app using the latest Visual Studio, and tried to run it (debug or release) on the Android x64 emulator, which also crashed on startup but with a different library error this time.
As with the Interop issue, this crash only happens on 64-bit builds of 5.0/5.1 emulator (and devices), where as 32-bit builds work fine.  Android 6+ devices run either x86/x64 fine.

05-08 11:55:05.178: E/AndroidRuntime(7531): Process: com.companyname.crashtest, PID: 7531
05-08 11:55:05.178: E/AndroidRuntime(7531): java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libmonosgen-2.0.so" needed by "/data/app/com.companyname.crashtest-1/lib/x86_64/libmonodroid.so"; caused by library "libmonosgen-2.0.so" not found
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at java.lang.System.loadLibrary(System.java:989)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:80)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:48)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.os.Looper.loop(Looper.java:135)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at java.lang.reflect.Method.invoke(Native Method)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
05-08 11:55:05.178: E/AndroidRuntime(7531): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

I had also tried updating to the latest Forms 4.6.0.726, and Xamarin.Essentials 1.5.3.1, but still crashes.

### Steps to Reproduce

1. Create a new Xamarin.Forms project (or use the zipped template project provided)
2. Build and deploy as-is on an Android 5.x 64-bit emulator (or Huawei P8 Lite device)

### Expected Behavior
The app doesn't crash.

### Actual Behavior
The app crashes complaining about libraries

### Basic Information

- Version with issue: 
- Last known good version:
- IDE: Visual Studio 2019 v16.5.4
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.16.0.13
  - Android: Xamarin.Android 10.2.0.100
- Android Support Library Version: N/A
- Nuget Packages: 
	NETStandard.Library v2.0.3
	Xamarin.Forms 4.6.0.726
	Xamarin.Essentials 1.5.3.1
- Affected Devices:  64-bit Android 5.0 or 5.1 emulators (or Huawei P8 Lite device at least)

### Screenshots
N/A

### Reproduction Link
N/A

### Workaround
N/A

**Comment by stevecluk** [comment]
Adding a dropbox link to the test project
[https://www.dropbox.com/s/7l8ci0s61r556jy/CrashTest.zip?dl=0](url)

**Comment by PureWeen** [comment]
```
Time	Device Name	Type	PID	Tag	Message
	pixel_2_lollipop_5_0_-_api_21_x64	Error	3987	AndroidRuntime	java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libmonosgen-2.0.so" needed by "/data/app/com.companyname.Xamarin.Forms.Sandbox-1/lib/x86_64/libmonodroid.so"; caused by library "libmonosgen-2.0.so" not found
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:989)
	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:80)
	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:48)
	at android.app.ActivityThread.installProvider(ActivityThread.java:4964)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4559)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4499)
	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
  Force finishing activity com.companyname.Xamarin.Forms.Sandbox/crc645b466b186780a260.MainActivity
```

**Comment by PureWeen** [comment]
@stevecluk I've poked the Android team to see if they have any thoughts

**Comment by stevecluk** [comment]
Thanks - this used to work with older builds, I'd just come across it when updating an app I'd released a few years ago to the latest packages.  I'd wondered if a workaround might have been to upload an APK/AAB for 5.x devices only that just had 32-bit support (which worked locally), but Google Play requires 64-bit now for all updates so that's a non-starter, and I'm seeing quite a few crashes for people on those legacy devices.

**Comment by PureWeen** [comment]
It looks like this is a known issues with pre 6.0 android devices and it's related to using shared runtime/fast deployment

I tested and for me when I turn off shared runtime then it's able to deploy and run without issues

For your debug builds you can set
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
  </PropertyGroup>
```

 This will allow some of the benefits of the shared runtime such as faster dev turnaround when an assembly changes.

**Comment by martinstoeckli** [comment]
I can reproduce the same error with my project https://github.com/martinstoeckli/SilentNotes/tree/master/src/SilentNotes.Android, with:

- Android emulator x86_64 - Lollipop 5.0 - API 21 - Phone M-DPI 5.1''.
- VisualStudio 16.6.1
- Xamarin.Android.SDK 10.3.1.4

With PureWeen's workaround it does not abort immediately, instead it throws an exception when calling GalaSoft.MvvmLight.Ioc.SimpleIoc.Default.Reset():

```
System.DllNotFoundException
  Message=libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
```

Interestingly the same error occurs when compiling in release mode. Other devices, e.g. Android 10.0 -API 29 do not have this problem. Really hope it is an emulator problem only.
