### ISSUE TITLE
[Bug] [Debugging] [Deployment] Debugging with Android 10 device Error

### ISSUE THREAD

**Issue by Rikudouensof** [xamarin/Xamarin.Forms#10707]
### Description

I have a project that runs fine on my Nokia android device. To update its reach, I updated my device to android 10. I went to the SDK manager and got the android v29.

With my AMD PC, a debug only using real devices.

I changed the target framework to v29, Android 10-Q.

I am getting deployment issues

### Steps to Reproduce

1.  Create a Xamarin. Forms project that targets Android 9.
2. Update framework and Nugget package to update
3. Run

### Expected Behavior
Build and deploy successfully

### Actual Behavior
Gives the error

>Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0010:  Deployment failed
Mono.AndroidTools.InstallFailedException: Unexpected install output: Error: Failed to parse APK file: /data/local/tmp/Mono.Android.Platform.ApiLevel_29.apk
Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/Mono.Android.Platform.ApiLevel_29.apk
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:486)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1075)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22021)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4876)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4128)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/Mono.Android.Platform.ApiLevel_29.apk
	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1597)
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1582)
	at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:479)
	... 10 more
at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\548\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 345
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\548\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AndroidDeviceExtensions.<PushAndInstallPackage>d__11.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AndroidDeviceExtensions.<PushAndInstallPackage>d__11.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AndroidDeviceExtensions.<InstallSharedPlatformAsync>d__24.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Devices\AndroidDeviceExtensions.cs:line 478
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<InstallSharedPlatformAsync>d__110.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<EnsureCorrectSharedRuntimes>d__107.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<RunAsync>d__106.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.AndroidTools.AndroidDeploySession.<RunLoggedAsync>d__104.MoveNext() in E:\A\_work\548\s\External\androidtools\Xamarin.AndroidTools\Sessions\AndroidDeploySession.cs:line 119		 	0	

### Basic Information

- Version with issue: 4.6.0.772
- Last known good version:
- IDE: Visual studio 2019 v16.5.4
- Platform Target Frameworks: Android 10 (Q)
  - iOS:  8.0 (not the issue)
  - Android: 10.0
  - UWP: Windows 10 1903 18362 (not the issue)
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

### Screenshots

[Image of error](https://ibb.co/68DR0Y7)

### Reproduction Link

[Public git of error](https://github.com/Rikudouensof/NaijEmer)

### Workaround

Still stuck (15-04-2020 14:11 GMT +1)

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

**Comment by Rikudouensof** [comment]
I am not sure what you are asking, but please go into details all, anything you think/believe / discovered could help.

**Comment by jonathanpeppers** [comment]
@Rikudouensof at build time, some APK files are generated in:

* Windows - `%localappdata%\Xamarin.Android\Cache`
* Mac - `~/Library/Caches/Xamarin.Android/`

Can you delete this directory and try again?

It seems like this file is not a valid APK: 
```
Mono.AndroidTools.InstallFailedException: Unexpected install output: Error: Failed to parse APK file: /data/local/tmp/Mono.Android.Platform.ApiLevel_29.apk
```

**Comment by Rikudouensof** [comment]
Ok, let me see to this. @jonathanpeppers.

**Comment by Rikudouensof** [comment]
@jonathanpeppers it is working properly now, thanks.

**Comment by VictorKochetkov** [comment]
Same issue faced:
- on Visual Studio for Mac (8.6.2) - build is success, but every deploy finished with same error
- on Visual Studio for Windows (16.6.1) - build is success, deploy is working randomly - sometimes it is successfully, but rarely

**Comment by jonathanpeppers** [comment]
@VictorKochetkov did you try the workaround? https://github.com/xamarin/Xamarin.Forms/issues/10707#issuecomment-630271548

Xamarin.Android's deployment workflow will be changing soon, so this error wouldn't happen at all in the future.

**Comment by VictorKochetkov** [comment]
Yes, I tried - no effect.
In future - ok, but what to do right now?) I'm unable to deploy, debug app :(
Any suggestions?

**Comment by jonathanpeppers** [comment]
Ok, yours is actually failing to install _your app_: `myapp-Signed.apk`. This is a different issue.

Are you comfortable uploading the `.apk` here? Or email me privately? Use my email listed on [Github](https://github.com/jonathanpeppers). Thanks!

**Comment by PureWeen** [comment]
Closing this for now. @VictorKochetkov if you're still having issues and can upload an apk I'll reopen

**Comment by hadigityat** [comment]
@VictorKochetkov I'm facing the same issue on Visual Studio for Mac (8.6.8), were you able to fix it?

**Comment by VictorKochetkov** [comment]
> @VictorKochetkov I'm facing the same issue on Visual Studio for Mac (8.6.8), were you able to fix it? 

This issue is still appears. But I have some workaround) Just check/uncheck multidex feature in project properties temporarily fixes the issue.

**Comment by jonathanpeppers** [comment]
@VictorKochetkov can you attach a [diagnostic MSBuild log](https://docs.microsoft.com/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) the next time you hit the error?
