### ISSUE TITLE
[Bug] CollectionView throws java.lang.IllegalStateException on Android when using RemainingItemsThresholdReachedCommand

### ISSUE THREAD

**Issue by ppetrov** [xamarin/Xamarin.Forms#10825]
### Description
I'm trying to use RemainingItemsThreshold and RemainingItemsThresholdReachedCommand to load more data on demand but I'm seeing this exception spammed to the Outlet when scrolling at the end of the CollectionView. However it works perfectly on iOS(version 12.4.6) iPad mini 2.

### Steps to Reproduce

1.  Scroll CollectionView to the end .

### Expected Behavior
No exception and correct spacing between items.

### Actual Behavior
No spacing between the items and the following exception:
05-22 16:44:15.465 W/RecyclerView(19594): Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
05-22 16:44:15.465 W/RecyclerView(19594): java.lang.IllegalStateException:  crc643f46942d9dd1fff9.CollectionViewRenderer{61416c6 VFED..... ......ID 0,0-2506,1458 #2}, adapter:crc643f46942d9dd1fff9.GroupableItemsViewAdapter_2@b61b423, layout:android.support.v7.widget.LinearLayoutManager@3116f7f, context:android.view.ContextThemeWrapper@c6264a1
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2890)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:5300)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:12022)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:7180)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc6414252951f3f66c67.RecyclerViewScrollListener_2.n_onScrolled(Native Method)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc6414252951f3f66c67.RecyclerViewScrollListener_2.onScrolled(RecyclerViewScrollListener_2.java:29)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4961)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1954)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:3187)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.View.dispatchTouchEvent(View.java:13471)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2888)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:56)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:66)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.PlatformRenderer.n_dispatchTouchEvent(Native Method)
05-22 16:44:15.465 W/RecyclerView(19594): 	at crc643f46942d9dd1fff9.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:55)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
05-22 16:44:15.465 W/RecyclerView(19594): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:754)
05-22 16:44:15.465 W/RecyclerView(19594): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.app.Activity.dispatchTouchEvent(Activity.java:3494)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
05-22 16:44:15.465 W/RecyclerView(19594): 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
05-22 16:44:15.465 W/RecyclerView(19594): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:712)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.View.dispatchPointerEvent(View.java:13719)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6153)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5931)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5380)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5433)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5399)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5558)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5407)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5615)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5380)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5433)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5399)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5407)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5380)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8471)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8373)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8326)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8586)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8545)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8613)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.Choreographer.doFrame(Choreographer.java:690)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.os.Handler.handleCallback(Handler.java:873)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.os.Looper.loop(Looper.java:214)
05-22 16:44:15.467 W/RecyclerView(19594): 	at android.app.ActivityThread.main(ActivityThread.java:7080)
05-22 16:44:15.467 W/RecyclerView(19594): 	at java.lang.reflect.Method.invoke(Native Method)
05-22 16:44:15.467 W/RecyclerView(19594): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
05-22 16:44:15.467 W/RecyclerView(19594): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

### Basic Information

- Version with issue: 4.6.0.800
- Last known good version: I haven't tested on any other XF version
- IDE: VS 2019 16.6.0
- Platform Target Frameworks: 
  - iOS:  Works fine on 12.4.6 iPad mini 2
  - Android: Android 9.0 - API 28
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Galaxy Tab S5e : SM-T720 (I've only this device) and didn't test on simulator.

### Screenshots

![Screenshot_20200522-170018](https://user-images.githubusercontent.com/84007/82676140-90dce800-9c4e-11ea-90c8-77a8b31f5acd.jpg)

**Comment by cabal95** [comment]
Same issue. The pure-android fix for this appears to be to perform the update on the next UI pass: https://stackoverflow.com/questions/42944005/recyclerview-cannot-call-this-method-in-a-scroll-callback

So it seems like CollectionView should do this itself before calling the command/event.

If you are loading data from a network API call then that probably fixes it by itself. The reason is that if you have an `await` on a network call then a by product of that is to force the executing code to continue after a delay - thus a later UI pass.

**Workaround**: My project already has an ICommand implementation that is a wrapper for async commands. It also implements a feature that prevents concurrent calls, so the command will not be executed again while a previous call is still running. When I already have data ready to be loaded - for example if I'm testing and just adding in mock items - I just insert an `await Task.Delay(1);` in the call and that seems to fix it.

Again, the trick is to just introduce some sort of delay which forces your code to continue after the current UI pass completes.

**Comment by vhugogarcia** [comment]
Hello @cabal95 , I'm interested on your solution. However, I'm not clear exactly where you put the Task.Delay. Did you add it on the constructor of the viewmodel or where exactly?

**Comment by RCLuciano** [comment]
Hello @cabal95, I add the workaround and the issue was fixed, not error shows, but there is an abnormal behavior. most of the entries is being duplicated in the list.

**Comment by cabal95** [comment]
@RCLuciano I'm not sure why you would be running into that issue. It might be an unrelated bug, though I can't say for sure. We haven't noticed any duplication in our list from using this method. It might be possible that your "load more" code is executing multiple times by the collection view.
