### ISSUE TITLE
[Bug] UWP: CollectionView in CarouselView crashes when resizing the window

### ISSUE THREAD

**Issue by JogyBlack** [xamarin/Xamarin.Forms#10897]
### Description
Xamarin.Forms app with a UWP project. A CarouselView contains a template with a CollectionView inside. When the page is displayed in a window, and the user starts resizing the window, at some point the app crashes.

### Steps to Reproduce

This is the Page XAML:
```
  <CarouselView ItemsSource="{Binding CarouselItems}">
    <CarouselView.ItemTemplate>
      <DataTemplate>
        <CollectionView ItemsSource="{Binding Items}">
          <CollectionView.ItemTemplate>
            <DataTemplate>
              <Label Text="{Binding Text}" />
            </DataTemplate>
          </CollectionView.ItemTemplate>
        </CollectionView>
      </DataTemplate>
    </CarouselView.ItemTemplate>
  </CarouselView>
```
The ViewModel is a simple one:
```
  public class TestItemViewModel
  {
    public string Text { get; set; }
  }

  public class TestViewModel
  {
    public List<TestItemViewModel> Items { get; set; }
  }

  public class TestPageViewModel
  {
    public List<TestViewModel> CarouselItems { get; set; }
  }
```
The BindingContext of the page:
```
      TestPageViewModel vm = new TestPageViewModel();
      vm.CarouselItems = new List<TestViewModel>();
      vm.CarouselItems.Add(new TestViewModel() { Items = new List<TestItemViewModel>() { new TestItemViewModel() { Text = "Item1" }, new TestItemViewModel() { Text = "Item2" } } });
      BindingContext = vm;
```

### Expected Behavior
The app should not crash when resized.

### Actual Behavior
The app crashes when resized:
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

No useful stack trace is available.

### Basic Information

- Version with issue: 4.6
- Last known good version: Same crash with previous versions, ever since CarouselView was introduced
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP: 16299
- Nuget Packages:
- Affected Devices: Windows Desktop

**Comment by JogyBlack** [comment]
[TestCarousel2.zip](https://github.com/xamarin/Xamarin.Forms/files/4705020/TestCarousel2.zip)
Sample project - compile and run under Windows, then grab the border of the app window and start resizing it. After some resizes it crashes.

**Comment by jsuarezruiz** [comment]
Thanks for the reproduction sample. I have done some tests and can reproduce the issue. Could it be the same as https://github.com/xamarin/Xamarin.Forms/issues/10673 fixed by https://github.com/xamarin/Xamarin.Forms/pull/10686?. I will do more tests to verify it.

**Comment by fntc** [comment]
Getting that error when resizing:

`System.IndexOutOfRangeException: Can't set CarouselView to position -1. ItemsSource has 3 items.
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.UpdateFromPosition()
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs changedProperty)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.UpdateInitialPosition()
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.OnListSizeChanged(Object sender, SizeChangedEventArgs e)
`

Xamarin.Forms 4.7.0.968

**Comment by Xonshiz** [comment]
On Xamarin Forms V4 and just came across this scenario. Getting the same error. Any workaround for this?
