### ISSUE TITLE
System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by todorspetkov** [xamarin/Xamarin.Forms#10944]
### Description
Observing the following Exception in Firebase Crashlytics only on Android 5.0.x devices, 90% on Huawei devices. Release build (no shared mono runtime). Anyone seen somthething similar?

Fatal Exception: android.runtime.JavaProxyThrowable: System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <1b7a5cd4b5194667aea235f87b2a861e>:0 
  at System.Guid.NewGuid () [0x00000] in <1b7a5cd4b5194667aea235f87b2a861e>:0 
  Comune.InitializeComponent () [0x00182] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at xxx.Views.SelezioneComune..ctor (System.Boolean isCambia) [0x0000c] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at xxx.App.OnStart () [0x000aa] in <1170faa3308346b08cbc4f21dc5916bc>:0 
  at Xamarin.Forms.Application.SendStart () [0x00000] in <9608dd67eb804f0494e04a66ff90c168>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStateChanged () [0x0001b] in <63e7c9910ab446ac9b78b1ac3ac3e5bb>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00046] in <63e7c9910ab446ac9b78b1ac3ac3e5bb>:0 
  at xxx.Droid.MainActivity.OnStart () [0x00000] in <db697bb0cebf40899ddd1dbba31ef430>:0 
  at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <26ea6ddb724e4be2b66b6bde37c83c15>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.14(intptr,intptr)
       at crc6473e84085518c5ff7.MainActivity.n_onStart(MainActivity.java)
       at crc6473e84085518c5ff7.MainActivity.onStart(MainActivity.java:85)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
       at android.app.Activity.performStart(Activity.java:6032)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
       at android.app.ActivityThread.access$1200(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

### Basic Information

Minimum Android version : Android 5.0 (API level 21)
Target Android version : Android 10.0 (API level 29)
=== Visual Studio Community 2019 for Mac ===

Version 8.6.2 (build 6)
Installation UUID: 69833a91-0eac-4ae5-b6a6-d5db1c20fbb4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Version: 3.1.300
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	2.1.18

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/todor/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.1
SDK Build Tools Version: 30.0.0 rc4

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/todor/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:22 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:42 UTC

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Build Information ===

Release ID: 806020006
Git revision: c742dc3fcbf76855738eef57ce41d65f91acbf27
Build date: 2020-05-28 15:22:51-04
Build branch: release-8.6
Xamarin extensions: c742dc3fcbf76855738eef57ce41d65f91acbf27

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by todorspetkov** [comment]
Additional info: Compile Android Target Framework = Android 10.0 (Q).

**Comment by jsuarezruiz** [comment]
@samhouts Could we move this issue to https://github.com/xamarin/xamarin-android/issues and move forward to get more information?

**Comment by todorspetkov** [comment]
Here is a full stack trace (logcat) from a Huawei P8 Lite Android API 21. This only happens on some Android API 21 devices.
-----------------------------------------------------------------------------
06-05 05:54:53.935: I/MonoDroid(20521): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'PanCardView.Droid.CardsViewRenderer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Random' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
06-05 05:54:53.935: I/MonoDroid(20521):   at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
06-05 05:54:53.935: I/MonoDroid(20521):   at Interop+Sys..cctor () [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):    --- End of inner exception stack trace ---
06-05 05:54:53.935: I/MonoDroid(20521):   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath) [0x00006] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.IO.File.Exists (System.String path) [0x00043] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FileImageSourceHandler.LoadImageAsync (Xamarin.Forms.ImageSource imagesource, Android.Widget.ImageView imageView, System.Threading.CancellationToken cancellationToken) [0x0000c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.ImageViewExtensions.UpdateBitmap (Android.Widget.ImageView imageView, Xamarin.Forms.IImageElement newView, Xamarin.Forms.IImageElement previousView, Xamarin.Forms.ImageSource newImageSource, Xamarin.Forms.ImageSource previousImageSource) [0x001bf] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Random.GenerateGlobalSeed () [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Random..cctor () [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):    --- End of inner exception stack trace ---
06-05 05:54:53.935: I/MonoDroid(20521):   at PanCardView.Droid.CardsViewRenderer..cctor () [0x00000] in <2c8a147a111949b3bd5c382644efebe0>:0 
06-05 05:54:53.935: I/MonoDroid(20521):    --- End of inner exception stack trace ---
06-05 05:54:53.935: I/MonoDroid(20521):   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):    --- End of inner exception stack trace ---
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001d] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Reflection.RuntimeConstructorInfo.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00086] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Reflection.RuntimeConstructorInfo.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x0022b] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x0009c] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <96e786663b0547dda3a2b357695888ab>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object source, System.Type visualType, System.Object[] args) [0x000af] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandler (System.Type type, System.Object source, Xamarin.Forms.IVisual visual, System.Object[] args) [0x00060] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandlerForObject[TOut] (System.Object obj, System.Object[] args) [0x00041] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00005] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c4] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c4] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c4] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c4] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000c4] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x0016c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000dd] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00033] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild (Xamarin.Forms.Page page, System.Boolean layout) [0x0000d] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal (Xamarin.Forms.Page newRoot) [0x00061] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage (Xamarin.Forms.Page newRoot) [0x000e6] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x00020] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x0000c] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.AppOnPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs args) [0x00035] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00012] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Application.set_MainPage (Xamarin.Forms.Page value) [0x0008b] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Junker.App.OnStart () [0x00065] in <07bcc23a4f5543bba50d8c5e8b514d6e>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Application.SendStart () [0x00000] in <1afe74fdb5894902ba3079cf55eb36e4>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStateChanged () [0x0001b] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnStart () [0x00046] in <507a3bfe8d9744f7bb3ac35ad413a0b7>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Junker.Droid.MainActivity.OnStart () [0x00000] in <7005ba6e7a6b40dcaed5e603deb28a12>:0 
06-05 05:54:53.935: I/MonoDroid(20521):   at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <eaa205f580954a64824b74a79fa87c62>:0
