### ISSUE TITLE
[Bug] [UWP] Shell app FlyOutBehavior="Locked" throws System.NullReferenceException after upgrade to 4.7

### ISSUE THREAD

**Issue by brianro** [xamarin/Xamarin.Forms#11096]
### Description
A working shell app in 4.6 breaks during startup after upgrading to 4.7 if FlyoutBehavior="Locked".

Error 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.ShellSplitView.UpdateFlyoutBackdropColor()
   at Xamarin.Forms.Platform.UWP.ShellRenderer.OnPaneOpening()
   at Windows.UI.Xaml.FrameworkElement.OnApplyTemplate()
   at Xamarin.Forms.Platform.UWP.ShellRenderer.OnApplyTemplate()

**NB: May be related to https://github.com/xamarin/Xamarin.Forms/pull/11009/commits/8e187515bc8b28d2e2a4a21bfefde1d0433fd61c**

### Steps to Reproduce

1. Taking working UWP shell app using 4.6 (Xanimals)
2. Check working
3. Add FlyoutBehavior="Flyout" to Shell element
4. Run app - works
5. Upgrade Xamarin.Forms to 4.7
6. App fails during load

### Expected Behavior
App loads and draws menu

### Actual Behavior
App throws exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.ShellSplitView.UpdateFlyoutBackdropColor()
   at Xamarin.Forms.Platform.UWP.ShellRenderer.OnPaneOpening()
   at Windows.UI.Xaml.FrameworkElement.OnApplyTemplate()
   at Xamarin.Forms.Platform.UWP.ShellRenderer.OnApplyTemplate()

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: 4.6.0.967
- IDE: VS2019
- Platform Target Frameworks: UWP
  - iOS:  Not tested
  - Android: Not tested
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Change FlyOutBehavior="Locked" to FlyoutBehavior="Flyout".

**Comment by brianro** [comment]
@samhouts @PureWeen Thank you for getting this fixed. Much appreciated for the rapid response.
