### ISSUE TITLE
[Bug] Errors After AndroidX Update

### ISSUE THREAD

**Issue by developersimsek** [xamarin/Xamarin.Forms#11171]
### Description
Hi,
I had to update the project to AndroidX because a nougat AndroidX packages wanted my app installed on Google Play. The project is not debugged after the update. Can you please help urgently to solve the error?

### Steps to Reproduce

1. The Xamarin.Forms package has been upgraded to the latest version.
2. The project was migrated to AndroidX with Migrate To AndroidX option.
3. Latest versions of all libraries in the application, including AndroidX libraries, have been installed.
4. Bin / obj and nuget folders have been cleared.

### Expected Behavior

Debugging the project without errors

### Actual Behavior

- Exception in thread "main" java.lang.IllegalArgumentException
- at java.util.concurrent.ThreadPoolExecutor.(ThreadPoolExecutor.java:1314)
- at java.util.concurrent.ThreadPoolExecutor.(ThreadPoolExecutor.java:1202)
- at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
- at com.xamarin.androidx.jetifierWrapper.Main.executeJetifier(Main.java:222)
- at com.xamarin.androidx.jetifierWrapper.Main.main(Main.java:142)

### Basic Information

Xamarin Forms: 4.7.0.968

Microsoft Visual Studio Enterprise 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

ASP.NET and Web Tools 2019 16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services 16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019 16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0 16.6.948.25768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools 16.6.948.25768
Azure Functions and Web Jobs Tools

C# Tools 3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DevExpress Reporting Extension 1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress Reporting Tools Extension 1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool 1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension 1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus 1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitLab Extension for Visual Studio 1.0.189
A Visual Studio Extension that brings the GitLab Flow into Visual Studio.

IntelliCode Extension 1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools 2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio 0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager 2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers 1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio 16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager 5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension 1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools 16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools 16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7 16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview) 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog 1.0
Information about my package

VisualStudio.Foo 1.0
Information about my package

VisualStudio.Mac 1.0
Mac Extension for Visual Studio

VisualSVN 7.2.0
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2019 VisualSVN Software Ltd. All rights reserved.

Xamarin 16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
Mono: 165f4b0
Java.Interop: xamarin/java.interop@2cab35c
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK 13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots
![ErrorList](https://user-images.githubusercontent.com/23637417/85385126-9a59b880-b54a-11ea-9b89-61919f76ee80.PNG)

### Reproduction Link

[Output.txt](https://github.com/xamarin/Xamarin.Forms/files/4818370/Output.txt)

**Comment by developersimsek** [comment]
Hi,

Create a Xamarin.Forms project from scratch / New and create The project was migrated to AndroidX with Migrate To AndroidX option. Then I updated the libraries again. (No 3rd party nuget is installed.) The result is still the same. I add the newly created project. Can you please support urgently?

Thank you,
Good work...

[MaliTakvim.zip](https://github.com/xamarin/Xamarin.Forms/files/4818575/MaliTakvim.zip)
