### ISSUE TITLE
[Bug] .NET CORE WPF ActivityIndicator runtime crash

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#11204]
### Description
System.InvalidOperationException: 'Specified element is already the logical child of another element. Disconnect it first.'

callstack:
```
   at System.Windows.FrameworkElement.ChangeLogicalParent(DependencyObject newParent)
   at System.Windows.FrameworkElement.AddLogicalChild(Object child)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at Xamarin.Forms.Platform.WPF.ScrollViewRenderer.LoadContent()
   at Xamarin.Forms.Platform.WPF.ScrollViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.<>c__DisplayClass4_0.<HandleChildAdded>b__0()
   at Xamarin.Forms.Platform.WPF.Helpers.UiHelper.ExecuteInUiThread(Action action)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.HandleChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.WPF.LayoutRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.PageRenderer.UpdateContent()
   at Xamarin.Forms.Platform.WPF.PageRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.WPF.ViewRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.Platform.GetOrCreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.CreateOrResizeContent(FrameworkElement parent, VisualElement visualElement)
   at Xamarin.Forms.Platform.WPF.FormsContentLoader.OnSizeContentChanged(FrameworkElement parent, Object page)
   at Xamarin.Forms.Platform.WPF.Controls.FormsContentControl.LightContentControl_SizeChanged(Object sender, SizeChangedEventArgs e)
   at System.Windows.SizeChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
```

### Steps to Reproduce

1. Create .net core app
2. Create page with activity indicator
```
<Grid ColumnSpacing="0" RowSpacing="0">
        <StackLayout>
                  <Label Text="Default text"
        </StackLayout>

        <!--  INDICATOR  -->
        <ActivityIndicator
            HorizontalOptions="Center"
            IsRunning="{Binding IsBusy, Mode=OneWay}"
            IsVisible="{Binding IsBusy, Mode=OneWay}"
            VerticalOptions="Center"
            WidthRequest="100" />
    </Grid>
```

### Expected Behavior
Display activity indicator

### Actual Behavior
Crash

### Basic Information

- Version with issue: 4.8.0.1033-nightly
- .NET Core: net5.0

**The application works with .NET Framework 4.7.2**

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
