### ISSUE TITLE
Building release version for android failed

### ISSUE THREAD

**Issue by xDaijobu** [xamarin/Xamarin.Forms#11295]
### Description
I have an error when compiling in Release and generating the APK, in Debug mode if it compiles and it works, in Release I have the following error: The "LinkAssemblies" task failed unexpectedly.

> Severity Code Description Project File Line Suppression State
Error The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'SkiaSharp.SKImageInfo SkiaSharp.SKBitmap::DecodeBounds(System.ReadOnlySpan1<System.Byte>)' in assembly: 'SkiaSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve !0& modreq(System.Runtime.InteropServices.InAttribute) System.ReadOnlySpan1<System.Byte>::GetPinnableReference()
at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
at Mono.Linker.Steps.MarkStep.ProcessQueue()
--- End of inner exception stack trace ---
at Mono.Linker.Steps.MarkStep.ProcessQueue()
at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
at Mono.Linker.Steps.MarkStep.Process()
at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.LinkAssemblies.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() Duren.Android

### Steps to Reproduce
1.  Unzip the attached example and open the solution ( Visual Studio 2017 )
2.  Build & Release 

### Basic Information
Linker configured for Sdk Assemblies Only in Android build options

Information
Target framework - Android 9 ( Pie )
Visual Studio 2017 - v15.9.24
Skiasharp.Views.Forms - 1.68.3
Skiasharp 1.68.3
Xamarin.Forms - v4.5.0.725
Xamarin.Android SDK 9.1.7.0

### Screenshots
**Visual Studio 2017** 
![2017](https://user-images.githubusercontent.com/22674537/86440758-3ba7f200-bd35-11ea-90fa-df61717ce900.png)
![image](https://user-images.githubusercontent.com/22674537/86441120-e9b39c00-bd35-11ea-832c-135b55313392.png)

**Visual Studio 2019**
![image](https://user-images.githubusercontent.com/22674537/86440907-845fab00-bd35-11ea-8d6e-c9ce074b7045.png)
![image](https://user-images.githubusercontent.com/22674537/86440970-a2c5a680-bd35-11ea-86d4-f3b5141fb3b8.png)

### Reproduction Link
[App5.zip](https://github.com/xamarin/Xamarin.Forms/files/4868205/App5.zip)

Thanks,
Cristover

**Comment by rmarinho** [comment]
HI @xDaijobu just tested this on vs2019 and it works, but i think i can reproduce this on vs2017. Any particular issue why you have to run vs2017? can you use vs2019?

@mattleibow do you know what might be happening ?

**Comment by rmarinho** [comment]
If i **disable the linker** or use **link user and sdk assemblies** it works fine on release mode on vs2017. 

this seems a issue only when using link sdk assemblies.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'SkiaSharp.SKImageInfo SkiaSharp.SKBitmap::DecodeBounds(System.ReadOnlySpan`1<System.Byte>)' in assembly: 'SkiaSharp.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve !0& modreq(System.Runtime.InteropServices.InAttribute) System.ReadOnlySpan`1<System.Byte>::GetPinnableReference()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	App5.Android			
```

**Comment by xDaijobu** [comment]
> HI @xDaijobu just tested this on vs2019 and it works, but i think i can reproduce this on vs2017. Any particular issue why you have to run vs2017? can you use vs2019?

when archiving a xamarin forms (android) app in vs2019 (the computer that we usually use to make APKs)
for some reason,  the release apk file can't be installed
so that's why we are using vs2017 :)

**Comment by xDaijobu** [comment]
2 days ago, i had make a issue in skiasharp

Ref :  [https://github.com/mono/SkiaSharp/issues/1371](url)

**Comment by mattleibow** [comment]
@rmarinho or @PureWeen this looks to be another case of the VS2017 / VS2019 issue of types. In VS2019, I think the Span<T> is in mscorlib, but in VS2017 it is not :(

**Comment by mattleibow** [comment]
Linking https://github.com/mono/SkiaSharp/issues/1371
