### ISSUE TITLE
[Bug] UWP crashes when changing a page and calling CollectionView.ScrollTo

### ISSUE THREAD

**Issue by daltonks** [xamarin/Xamarin.Forms#11564]
### Description

UWP can easily crash when changing the App's MainPage and calling CollectionView.ScrollTo.

When choosing to animate the scroll:
```
   at Xamarin.Forms.Platform.UWP.ScrollHelpers.<GetApproximateTargetAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.ScrollHelpers.<AnimateToItemAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.ItemsViewRenderer`1.<ScrollTo>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.ItemsViewRenderer`1.<ScrollToRequested>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

When choosing not to animate the scroll:
```
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Xamarin.Forms.Platform.UWP.ScrollHelpers.<JumpToItemAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.ItemsViewRenderer`1.<ScrollTo>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.ItemsViewRenderer`1.<ScrollToRequested>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

### Steps to Reproduce

1. Create a CollectionView on a page
2. Set MainPage to the page with the CollectionView and call CollectionView.ScrollTo immediately afterwards

Or you can check out my reproduction link here: https://github.com/daltonks/Xamarin.Forms.UWP.CollectionView.Scroll.Crash

### Expected Behavior

It doesn't crash and scrolls properly

### Actual Behavior

It crashes

### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: Don't know
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages: Xamarin.Essentials
- Affected Devices: Windows 10

### Reproduction Link

https://github.com/daltonks/Xamarin.Forms.UWP.CollectionView.Scroll.Crash

### Workaround

None. Can't easily catch the exception either, because you cannot await ScrollTo

**Comment by themronion** [comment]
Still not fixed btw...
