### ISSUE TITLE
[Bug] Could not load file or assembly Mono.Cecil [Android]

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/Xamarin.Forms#12026]
### Description

When I attempt to build my Android project, I get the following error:
> Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The system cannot find the file specified.
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()	

I tried installing Mono.Cecil in the project but that did not change anything.

### Steps to Reproduce

1.  Take an older Android project, use latest version of VS2019
2.  Try to build it
3.  Follow advice to add missing packages related to AndroidX packages
4.  Rebuild, new error relating to Mono.Cecil as pasted above

### Expected Behavior

The project migrates and builds just fine.

### Actual Behavior

Cannot build.

### Basic Information

- Version with issue:  Xamarin Forms 4.8
- Last known good version: maybe 4.4?
- IDE: VS2019 Enterprise  v16.7.2
- Platform Target Frameworks: 
  - Android:  Targeting Android 10, min. Android 7.1
- Android Support Library Version: 28.0.0.3, and added Xamarin.AndroidX.MediaRouter v1.1.0.3 as instructed (as described here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/androidx-migration)
- Affected Devices: n/a

**Comment by mzhukovs** [comment]
Update: all I had to do was after adding the missing dependencies related to AndroidX as instructed via the errors in IDE upon building the old android project the first time, I had to REMOVE the old support library references. It wasn't clear from the documentation that this could be done right after - and the resulting error was confusing. All good now.
