### ISSUE TITLE
[Bug] Cannot Build Android Project : Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0

### ISSUE THREAD

**Issue by ValonK** [xamarin/Xamarin.Forms#12051]
### Description

I cant build my Droid Project anymore, I'm getting this message
```
Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral or one of its dependencies. 
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()	
```

ive tried deleting packages, obj/bin, cleaning, rebuilding, installing Mono.Cecil, and even reseting VS, dont know what to try else 

### Basic Information

- IDE: Visual Studio
- Android Support Library Version: 10.0

- Nuget Packages:

```
<ItemGroup>
    <PackageReference Include="CardsView">
      <Version>2.6.3</Version>
    </PackageReference>
    <PackageReference Include="ExpandableView">
      <Version>1.0.10</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter">
      <Version>3.4.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>3.4.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>3.4.1</Version>
    </PackageReference>
    <PackageReference Include="MvvmCross">
      <Version>7.0.0</Version>
    </PackageReference>
    <PackageReference Include="MvvmCross.Forms">
      <Version>7.0.0</Version>
    </PackageReference>
    <PackageReference Include="Plugin.CurrentActivity">
      <Version>2.1.0.4</Version>
    </PackageReference>
    <PackageReference Include="Sharpnado.MaterialFrame">
      <Version>1.1.2</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-sqlcipher">
      <Version>1.7.335</Version>
    </PackageReference>
    <PackageReference Include="SQLiteNetExtensions.Async">
      <Version>2.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Annotation">
      <Version>1.1.0.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Collection">
      <Version>1.1.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Core">
      <Version>1.3.0.1</Version>
    </PackageReference>
		<PackageReference Include="Xamarin.Android.Support.Collections">
			<Version>28.0.0.3</Version>
		</PackageReference>
		<PackageReference Include="Xamarin.Android.Support.Annotations">
			<Version>28.0.0.3</Version>
		</PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI">
      <Version>1.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils">
      <Version>1.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.5.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Media">
      <Version>1.1.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.1.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.2.0.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData">
      <Version>2.2.0.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.1.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.5.3.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>4.8.0.1364</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Plugin.SharedTransitions">
      <Version>2.3.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
      <Version>1.1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration" Version="1.0.0-preview03" />
  </ItemGroup>

```
- Affected Devices:

All

**Comment by ValonK** [comment]
This Issue is beeing tracked [here](https://github.com/xamarin/AndroidX/issues/153)
