### ISSUE TITLE
[Bug] AndroidX not detaching Forms Fragment during transition

### ISSUE THREAD

**Issue by ahodder** [xamarin/Xamarin.Forms#12386]
### Description
We have a split native / forms app. Most of our app it native, however, we are migrating to forms. Previously our app was working fine, however, after upgrading android to AndroidX, we are getting a weird crash when navigating to a forms fragment then to native and back to forms again, stack trace below. 

We have a tab bar that allows for the selection of a few native pages and one forms page. Each of the pages lives in a FrameLayout that is the container that we swap the page fragments in and out of.

### Expected Behavior
Before AndroidX switching pages was working as expected.

### Actual Behavior
Now, returning to a previously seen forms page cause the attached exception.

### Basic Information

- Version with issue: 
AndroidX: 1.2.5.3
Forms: 4.8.0.1451

- Last known good version:
- IDE: Visual Studio as well as Rider
- Platform Target Frameworks: 
  - Android: api 29

### Crash
`java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
	at android.view.ViewGroup.addView(ViewGroup.java:5064)
	at android.view.ViewGroup.addView(ViewGroup.java:5004)
	at android.view.ViewGroup.addView(ViewGroup.java:4976)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:326)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:7068)
	at crc646a99559440df4eb7.RootFragment.n_onNavigationItemSelected(Native Method)
	at crc646a99559440df4eb7.RootFragment.onNavigationItemSelected(RootFragment.java:83)
	at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:204)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by jsuarezruiz** [comment]
I don't know if it's possible, but could you attach a small example where to reproduce the issue?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
