### ISSUE TITLE
[Bug] Big Sur: XamarinFormsPrevieweriOS cannot be opened because of a problem

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12841]
### Description

When running a Xamarin.Forms app in the iOS simulator on a Big Sur Mac, the following is displayed when the simulator boots:

<img width="328" alt="Screenshot 2020-11-13 at 19 30 01" src="https://user-images.githubusercontent.com/60286968/99102614-fd75e580-25e6-11eb-9db2-837c4d136a45.png">

Functionality seems to be normal though, including live reload functionality.

The only official MS documentation I found about XF/Big Sur compatibility is some old VS For Mac release notes, where **full** Xamarin.Forms/Big Sur compatibility was promised for **VS For Mac 8.7**. I am running VS For Mac 8.9 preview.

### Steps to Reproduce

1. Press build and run in VS For Mac for any Xamarin.Forms app on Big Sur, when the build target is set to iOS simulator.

### Expected Behavior

The incompatibility message should not be displayed.

### Actual Behavior

The incompatibility message is displayed.

### Basic Information

- Version with issue: Latest XF 5.0 preview release.
- Last known good version: None.
- IDE: VS For Mac 8.9 preview.
- Affected Devices: macOS Big Sur (11.0.1)

### Screenshots

<img width="328" alt="Screenshot 2020-11-13 at 19 30 01" src="https://user-images.githubusercontent.com/60286968/99102952-7bd28780-25e7-11eb-92ef-02bfe52e1e76.png">

> VS bug [#1250272](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1250272)

**Comment by jsuarezruiz** [comment]
I have done several tests using VS4Mac 8.8 with Xamarin.iOS 14.4.1.3 and Big Sur; and cannot reproduce the issue. 

Could you share your Visual Studio information?. Visual Studio > About Visual Studio > Show Details.

**Comment by Tommigun1980** [comment]
Hi @jsuarezruiz. It's 8.9 Preview build 265.

The error message seems to pop up every few minutes when working in VS, not just when making builds as I initially said.

Thanks.

**Comment by Tommigun1980** [comment]
> Hi @jsuarezruiz. Here is the information:
> 
> ```
> === Visual Studio Community 2019 for Mac (Preview) ===
> 
> Version 8.9 Preview (8.9 build 265)
> Installation UUID: a549e1fc-7a55-4ebc-8643-bcc713c2b009
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
> 
> 	Package version: 612000107
> 
> === Mono Framework MDK ===
> 
> Runtime:
> 	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
> 	Package version: 612000107
> 
> === Roslyn (Language Service) ===
> 
> 3.9.0-1.20507.6+4ed928935ce0e5db4327c168dfdad1c820a6a490
> 
> === NuGet ===
> 
> Version: 5.8.0.6860
> 
> === .NET Core SDK ===
> 
> SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
> SDK Versions:
> 	5.0.100
> 	5.0.100-rc.2.20479.15
> 	3.1.403
> 	3.1.402
> 	3.1.401
> 	2.1.811
> MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks
> 
> === .NET Core Runtime ===
> 
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	5.0.0
> 	5.0.0-rc.2.20475.5
> 	3.1.9
> 	3.1.8
> 	3.1.7
> 	2.1.23
> 	2.1.22
> 	2.1.21
> 
> === .NET Core 3.1 SDK ===
> 
> SDK: 3.1.403
> 
> === Xamarin.Profiler ===
> 
> Version: 1.6.15.68
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> === Updater ===
> 
> Version: 11
> 
> === Xamarin.Android ===
> 
> Version: 11.1.99.168 (Visual Studio Community)
> Commit: xamarin-android/master/71dc718
> Android SDK: /Users/myname/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		None installed
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 30.0.4
> SDK Build Tools Version: 30.0.2
> 
> Build Information: 
> Mono: be2226b
> Java.Interop: xamarin/java.interop/master@ac914ce
> ProGuard: Guardsquare/proguard/v7.0.0@84e8560
> SQLite: xamarin/sqlite/3.32.1@1a3276b
> Xamarin.Android Tools: xamarin/xamarin-android-tools/master@1878e43
> 
> === Microsoft OpenJDK for Mobile ===
> 
> Java SDK: /Users/myname/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Android SDK Manager ===
> 
> Version: 16.9.0.11
> Hash: 6cd0123
> Branch: remotes/origin/HEAD~1
> Build date: 2020-10-13 20:43:56 UTC
> 
> === Android Device Manager ===
> 
> Version: 16.9.0.8
> Hash: 3f57870
> Branch: remotes/origin/HEAD
> Build date: 2020-10-13 20:45:38 UTC
> 
> === Apple Developer Tools ===
> 
> Xcode 12.1 (17222)
> Build 12A7403
> 
> === Xamarin.Mac ===
> 
> Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.
> 
> === Xamarin.iOS ===
> 
> Version: 14.7.0.166 (Visual Studio Community)
> Hash: d91932dcd
> Branch: main
> Build date: 2020-10-21 10:50:26-0400
> 
> === Xamarin Designer ===
> 
> Version: 16.9.0.10
> Hash: 13c439740
> Branch: remotes/origin/fix-hotreload-signing
> Build date: 2020-10-16 01:32:54 UTC
> 
> === Build Information ===
> 
> Release ID: 809000265
> Git revision: 67bd2f44000a71ad9505ed487df7b1f4addd9f1d
> Build date: 2020-11-05 12:42:55-05
> Build branch: release-8.9
> Xamarin extensions: 67bd2f44000a71ad9505ed487df7b1f4addd9f1d
> 
> === Operating System ===
> 
> Mac OS X 10.16.0
> Darwin 20.1.0 Darwin Kernel Version 20.1.0
>     Sat Oct 31 00:07:11 PDT 2020
>     root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
> ```
> 
> The error message seems to pop up every few minutes when working in VS, not just when making builds as I initially said.
> 
> Thanks.

For whatever reason the error message has not popped up anymore. I have not updated VS in-between so maybe it only happens on the first time it’s run after updating?

**Comment by Tommigun1980** [comment]
@jsuarezruiz I said that it only seemed to happen on first boot after updating VS For Mac but this is incorrect, it does happen from time to time but the occurrence rate is only about a few times per day at most, with several days passing without that error message popping up once.

I also see the following in VS logs every time I boot it:
```
ERROR [2020-11-23 23:23:04Z]: Failed assertion: Why is Session property `null` for Xamarin.Designer.Forms.XamarinStudioXamlPreviewerView
   at Xamarin.Designer.Forms.XamarinStudioXamlController.OnSourceEditorContentChanged(System.Object sender, System.EventArgs e) in /Users/runner/work/1/s/Designer/Xamarin.Designer.Forms/Xamarin.FormsPreviewer.MonoDevelop/Xamarin.Designer.Forms/XamarinStudioXamlController.cs:line 103
   at MonoDevelop.Ide.Gui.Documents.DocumentController.NotifyContentChanged() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs:line 1018
   at MonoDevelop.Ide.Gui.Documents.DocumentController+<GetDocumentView>d__145.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs:line 731
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Documents.DocumentView, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<GetDocumentView>d__145 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentController.GetDocumentView()
   at Xamarin.Designer.Forms.XamarinStudioXamlController+<OnInitializeView>d__25.MoveNext() in /Users/runner/work/1/s/Designer/Xamarin.Designer.Forms/Xamarin.FormsPreviewer.MonoDevelop/Xamarin.Designer.Forms/XamarinStudioXamlController.cs:line 123
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Documents.DocumentView, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(Xamarin.Designer.Forms.<OnInitializeView>d__25 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at Xamarin.Designer.Forms.XamarinStudioXamlController.OnInitializeView()
   at MonoDevelop.Ide.Gui.Documents.DocumentController+<InternalInitializeView>d__170.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs:line 1141
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Documents.DocumentView, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<InternalInitializeView>d__170 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentController.InternalInitializeView()
   at MonoDevelop.Ide.Gui.Documents.DocumentController+DefaultControllerExtension.OnInitializeView() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs:line 1423
   at MonoDevelop.Ide.Gui.Documents.DocumentControllerExtension.OnInitializeView() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentControllerExtension.cs:line 132
   at MonoDevelop.Ide.Gui.Documents.DocumentControllerExtension.OnInitializeView() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentControllerExtension.cs:line 132
   at MonoDevelop.Ide.Gui.Documents.DocumentControllerExtension.OnInitializeView() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentControllerExtension.cs:line 132
   at MonoDevelop.VersionControl.VersionControlDocumentController.<>n__0()
   at MonoDevelop.VersionControl.VersionControlDocumentController+<OnInitializeView>d__12.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs:line 129
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Documents.DocumentView, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<OnInitializeView>d__12 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.VersionControl.VersionControlDocumentController.OnInitializeView()
   at MonoDevelop.Ide.Gui.Documents.DocumentControllerExtension.OnInitializeView() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentControllerExtension.cs:line 132
   at MonoDevelop.Ide.Gui.Documents.DocumentController+<GetDocumentView>d__145.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs:line 724
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Documents.DocumentView, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<GetDocumentView>d__145 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentController.GetDocumentView()
   at MonoDevelop.Ide.Gui.Document+<InitializeViewAsync>d__52.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs:line 277
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(<InitializeViewAsync>d__52 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 316
   at MonoDevelop.Ide.Gui.Document.InitializeViewAsync()
   at MonoDevelop.Ide.Gui.Documents.DocumentManager+<ShowView>d__42.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 662
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Document, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<ShowView>d__42 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.ShowView(MonoDevelop.Ide.Gui.DocumentOpenInformation documentOpenInfo)
   at MonoDevelop.Ide.Gui.Documents.DocumentManager+<LoadFile>d__41.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 634
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Document, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<LoadFile>d__41 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.LoadFile(FilePath fileName, MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Ide.Gui.Documents.DocumentControllerDescription binding, MonoDevelop.Projects.WorkspaceObject project, MonoDevelop.Ide.Gui.FileOpenInformation fileInfo, ITimeTracker`1 timer)
   at MonoDevelop.Ide.Gui.Documents.DocumentManager+<RealOpenFile>d__40.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 538
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.ValueTuple`2[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[MonoDevelop.Ide.Gui.Document, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start(<RealOpenFile>d__40 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.RealOpenFile(MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Ide.Gui.FileOpenInformation openFileInfo, ITimeTracker`1 timer)
   at MonoDevelop.Ide.Gui.Documents.DocumentManager+<BatchOpenDocument>d__39.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs:line 393
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[MonoDevelop.Ide.Gui.Document, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].Start(<BatchOpenDocument>d__39 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Documents.DocumentManager.BatchOpenDocument(MonoDevelop.Core.ProgressMonitor monitor, FilePath fileName, MonoDevelop.Projects.Project project, Int32 line, Int32 column, IShellNotebook dockNotebook)
   at MonoDevelop.Ide.Gui.Workbench+<OpenDocumentsInContainer>d__121.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 1132
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start(<OpenDocumentsInContainer>d__121 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 471
   at MonoDevelop.Ide.Gui.Workbench.OpenDocumentsInContainer(MonoDevelop.Core.ProgressMonitor pm, FilePath baseDir, System.Collections.Generic.List`1 docViews, System.Collections.Generic.List`1 list, MonoDevelop.Components.DockNotebook.DockNotebookContainer container)
   at MonoDevelop.Ide.Gui.Workbench+<OnLoadingWorkspaceUserPreferences>d__120.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 1058
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(<OnLoadingWorkspaceUserPreferences>d__120 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 316
   at MonoDevelop.Ide.Gui.Workbench.OnLoadingWorkspaceUserPreferences(System.Object s, MonoDevelop.Ide.UserPreferencesEventArgs args)
   at MonoDevelop.Ide.RootWorkspace+<RestoreWorkspacePreferences>d__108.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs:line 1018
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(<RestoreWorkspacePreferences>d__108 ByRef stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 316
   at MonoDevelop.Ide.RootWorkspace.RestoreWorkspacePreferences(MonoDevelop.Projects.WorkspaceItem item)
   at MonoDevelop.Ide.RootWorkspace+<BackgroundLoadWorkspace>d__106.MoveNext() in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs:line 942
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 1092
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:line 968
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:line 910
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run() in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 1073
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation+<>c.<.cctor>b__7_0(System.Object state) in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 379
   at MonoDevelop.Ide.DispatchService+GtkSynchronizationContext+TimeoutProxy.HandlerInternal(IntPtr data) in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs:line 76
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run() in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:line 145
   at MonoDevelop.Ide.Extensions.IdeCustomizer.OnRun(System.Func`1 postInit, System.Action shutdown) in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IdeCustomizer.cs:line 150
   at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options) in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 190
   at MonoDevelop.Ide.IdeStartup.Main(System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) in /Users/builder/azdo/_work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 720
   at VisualStudio.Startup.VisualStudioMain.Main(System.String[] args) in /Users/builder/azdo/_work/1/s/main/src/core/VisualStudio.Startup/VisualStudio.Startup/VisualStudioMain.cs:line 40
```

Don't know if it's related at all but I guess more info is better than too little.

**Comment by Tommigun1980** [comment]
I can’t unfortunately provide a repro as it’s not project dependent, and happens with any project (including bug repro projects downloaded from this site).
