### ISSUE TITLE
Can't compile empty Uno Platform project in VS 16.9.0 Preview 1.0

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12909]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cant-compile-empty-Uno-Platform-project/1249971?preview=true)._

---
Hello 
When I try to create and compile Uno Platform project in VS 16.9.0 Preview 1.0
I get next compile errors

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0414	The type 'ThemeResource' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	UnoApp3VS2019Preview.Droid	C:\DelphiStuff\_VisStudio-2019-My-Demos\UnoPlatform\UnoApp3VS2019Preview\UnoApp3VS2019Preview\UnoApp3VS2019Preview.Shared\MainPage.xaml	10	
Error	XLS0502	The type 'Page' does not support direct content.	UnoApp3VS2019Preview.Droid	C:\DelphiStuff\_VisStudio-2019-My-Demos\UnoPlatform\UnoApp3VS2019Preview\UnoApp3VS2019Preview\UnoApp3VS2019Preview.Shared\MainPage.xaml	10	
Error		Framework resource extraction failed. Could not find a part of the path 'C:\DelphiStuff\_VisStudio-2019-My-Demos\UnoPlatform\UnoApp3VS2019Preview\UnoApp3VS2019Preview\UnoApp3VS2019Preview.UWP\obj\x86\Debug\Microsoft.Extensions.DependencyInjection.Abstractions\en-us\Microsoft.Extensions.DependencyInjection.Abstractions.Resources.resw'.	UnoApp3VS2019Preview.UWP			
Error		Failed to generate Java type for class: AndroidX.Core.View.Accessibiity.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DelphiStuff\_VisStudio-2019-My-Demos\UnoPlatform\UnoApp3VS2019Preview\UnoApp3VS2019Preview\UnoApp3VS2019Preview.Droid\obj\Debug\100\android\src\mono\androidx\core\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	UnoApp3VS2019Preview.Droid
```

---
#### Feedback Bot on 11/11/2020, 05:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we transfer this issue to https://github.com/unoplatform/uno/issues?

**Comment by Redth** [comment]
Unfortunately we can't transfer across orgs, so please open an issue with uno as @jsuarezruiz mentioned if this is still a problem.  Thanks!
