### ISSUE TITLE
[Bug] Release build crashes on Android 4.4 KitKat

### ISSUE THREAD

**Issue by Ben-FarSoft** [xamarin/Xamarin.Forms#13413]
### Description

Building an brand new app to new emulated Android 4.4 device crashes if in Release mode, but works in Debug mode. Further testing has showed that it has got to do with the embedded runtime. If in Release mode I tick the Use Shared Runtime and make sure the Mono Shared Runtime is installed then I can get it to work.

### Steps to Reproduce

1. Create new blank Mobile app(Xamarin.Forms) but does same thing with blank Xamarin.Android app
2. Deploy in Release mode to Android 4.4 device and it crashes
3. Deploy in Debug and it works fine

### Expected Behavior

It should not crash

### Actual Behavior

It crashes

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1451
- Last known good version:4.7.0.474
- Platform Target Frameworks: 
  - Android: 4.4 KitKat

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA589
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework 6 Power Tools   0.9.2
Preview of useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:
1) View Entity Data Model (Read-only) - Displays a read-only view of the Code First model in the Entity Model Designer.
2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
3) View Entity Data Model DDL SQL - Displays the DDL SQL corresponding to the SSDL in the underlying EDM Model.
4) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

When right-clicking on an Entity Data Model (*.edmx) file, the following context menu function is supported:
Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Workaround

Make sure Mono runtime is installed on device and tick Use shared runtime in build options

**Comment by themronion** [comment]
In order for Xamarin to work on Android 4.4 u need to do some additional steps. Some small magic. I reccomend to develop apps setting the minimum version to 5.0 and forget about 4.4, since in the future exactly 5.0 will be the minumum supported version by MAUI and Forms

**Comment by Ben-FarSoft** [comment]
> 
> 
> In order for Xamarin to work on Android 4.4 u need to do some additional steps. Some small magic. I reccomend to develop apps setting the minimum version to 5.0 and forget about 4.4, since in the future exactly 5.0 will be the minumum supported version by MAUI and Forms

That is a problem, as we are forced to support 4.4. Some of the hardware we need to support with our app still comes only with 4.4.

**Comment by themronion** [comment]
The choice is up to u) So, here are some hacks that i remember i did to make it launch. In Android project settings turn on APPT2, then edit your .csproj file and add this line -     
```
<AndroidAapt2LinkExtraArgs>--no-version-vectors</AndroidAapt2LinkExtraArgs>
```
Then in the OnCreate method -
```
AppCompatDelegate.CompatVectorFromResourcesEnabled = true;
```
Dunno if its the right think to do and if all the steps are required, but it did the trick

**Comment by Ben-FarSoft** [comment]
@themronion thanks for the help, but unfortunately that also did not work. Luckily there is only two devices I know of that this currently affects and i can use my work around on them for now.

FYI. the devices in question are Datalogic Falcon X4 mobile scanners. They are still sold new with Android 4.4 and no play store.

**Comment by PureWeen** [comment]
This looks like it's a Xamarin.Android issue

I've attached a Xamarin.Android app that has the same exception

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/5845918/App1.zip)

```
01-20 17:48:54.552 3779-3779/com.companyname.app1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.companyname.app1, PID: 3779
    java.lang.UnsatisfiedLinkError: Couldn't load monosgen-2.0 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.companyname.app1-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.companyname.app1-1, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:358)
        at java.lang.System.loadLibrary(System.java:526)
        at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:86)
        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4790)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```
