### ISSUE TITLE
[Bug] Adding children to StackLayout sometimes crashes with exception "Check array index and length"

### ISSUE THREAD

**Issue by kevcrooks** [xamarin/Xamarin.Forms#14222]
### Description

In our app after creating and displaying a StackLayout, we later add multiple items using
`stackLayout.Children.Add(view)` inside a loop.

Occasionally this will throw an `ArgumentException`
"Destination array is not long enough to copy all the items in the collection. Check array index and length."

```
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
  at System.Collections.Generic.Dictionary`2+ValueCollection[TKey,TValue].CopyTo (TValue[] array, System.Int32 index) <0x104b66500 + 0x0015f> in <0c3d4da7367647c9a650750b1a4d0c53#f92e23ca71d8f6c19c98256109cb9156>:0
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) <0x1050f1838 + 0x000af> in <b9598bee51064c60be0f08abee8d363a#f92e23ca71d8f6c19c98256109cb9156>:0
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) <0x105044be0 + 0x00073> in <b9598bee51064c60be0f08abee8d363a#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged) <0x104d0c634 + 0x00053> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.Element.OnChildAdded (Xamarin.Forms.Element child) <0x104d435a8 + 0x00063> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.VisualElement.OnChildAdded (Xamarin.Forms.Element child) <0x104e21abc + 0x0002f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.Layout`1[T].OnChildAdded (Xamarin.Forms.Element child) <0x104d7e2b0 + 0x0001f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.Layout.OnInternalAdded (Xamarin.Forms.View view) <0x104d804d0 + 0x00097> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) <0x104d802dc + 0x00163> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
  at (wrapper delegate-invoke) <Module>.invoke_void_object_NotifyCollectionChangedEventArgs(object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) <0x1052a9718 + 0x0004f> in <c00e8e56dc9244bcb74e385bb57e9a59#f92e23ca71d8f6c19c98256109cb9156>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) <0x1052a99a8 + 0x0007b> in <c00e8e56dc9244bcb74e385bb57e9a59#f92e23ca71d8f6c19c98256109cb9156>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].InsertItem (System.Int32 index, T item) <0x1052a9304 + 0x00057> in <c00e8e56dc9244bcb74e385bb57e9a59#f92e23ca71d8f6c19c98256109cb9156>:0
  at System.Collections.ObjectModel.Collection`1[T].Add (T item) <0x104b5c570 + 0x0009f> in <0c3d4da7367647c9a650750b1a4d0c53#f92e23ca71d8f6c19c98256109cb9156>:0
  at Xamarin.Forms.ObservableWrapper`2[TTrack,TRestrict].Add (TRestrict item) <0x104d996d8 + 0x000b3> in <978ec34c5c9c4c4eb3d73b6da958bcd6#f92e23ca71d8f6c19c98256109cb9156>:0
```

This is happening on Xamarin.Forms `5.0.0.2012`.

We have seen the error above in AppCenter for an iOS user device, and occasionally reproduced locally on UWP.

The UWP stack trace is very similar:
```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.CopyTo(TValue[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Xamarin.Forms.Element.OnChildAdded(Element child)
   at Xamarin.Forms.VisualElement.OnChildAdded(Element child)
   at Xamarin.Forms.Layout`1.OnChildAdded(Element child)
   at Xamarin.Forms.Layout.OnInternalAdded(View view)
   at Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
```

Is there something we should be doing differently when adding children to a `StackLayout` to prevent this?

**Comment by charlesroddie** [comment]
Seems to be a threading issue related to creating views off UI thread

**Comment by rachelkang** [comment]
Hi, @kevcrooks - thanks for submitting this issue. Is this something you've experienced for the first time in XF 5.0.0.2012 or also on previous persons? Also, would you be able to share your project or a sample project that reproduces the issue so that we can take a closer look?
