### ISSUE TITLE
[Bug] Deploy on Android API 31 failed/crash

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#15120]
Hi,
i'm unable to deploy a app in an Android Pixel 5 Emulator with API31 in RELEASE-Mode.
App terminates immediately with this Stacktrace:

> Time	Device Name	Type	PID	Tag	Message
> 02-03 16:15:00.316	pixel_5_-_api_31_android_12	Info	9196	MonoDroid	Parameter name: enumType
>   at (wrapper managed-to-native) System.Enum.InternalGetUnderlyingType(System.RuntimeType)
>   at System.RuntimeType.GetEnumUnderlyingType () [0x0001d] in <f3792376f86b4b98b4bfdadc9292bfc3>:0 
>   at System.Enum.GetUnderlyingType (System.Type enumType) [0x00014] in <f3792376f86b4b98b4bfdadc9292bfc3>:0 
>   at System.Collections.Generic.EqualityComparer`1[T].CreateComparer () [0x000e1] in <f3792376f86b4b98b4bfdadc9292bfc3>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue]..ctor (System.Int32 capacity, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0001d] in <f3792376f86b4b98b4bfdadc9292bfc3>:0 
>   at System.Collections.Generic.Dictionary`2[TKey,TValue]..ctor () [0x00000] in <f3792376f86b4b98b4bfdadc9292bfc3>:0 
>   at Xamarin.Forms.VisualElement..ctor () <0x75e0b72b4e80 + 0x00072> in <23c19a60b6ca4c19b1ac9e3f840f8667>:0 
>   at Xamarin.Forms.Page..ctor () <0x75e0b728bf30 + 0x000fc> in <23c19a60b6ca4c19b1ac9e3f840f8667>:0 
>   at Xamarin.Forms.TemplatedPage..ctor () <0x75e0b72b29a0 + 0x00022> in <23c19a60b6ca4c19b1ac9e3f840f8667>:0 
>   at Xamarin.Forms.ContentPage..ctor () <0x75e0b7268ff0 + 0x00022> in <23c19a60b6ca4c19b1ac9e3f840f8667>:0 
>   at API31Crash.MainPage..ctor () [0x00000] in <dd7ed8aa8d10460ca2277b308637f04a>:0 
>   at API31Crash.App..ctor () [0x0000c] in <dd7ed8aa8d10460ca2277b308637f04a>:0 
>   at API31Crash.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00015] in <3dc413dc8a0245e998396a6b45cfcb82>:0 
>   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) <0x75e0baf027d0 + 0x00054> in <51237e4588334c2ba4d8114c0f6108b0>:0 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
> 	at crc6487dce9819796e5d4.MainActivity.n_onCreate(Native Method)
> 	at crc6487dce9819796e5d4.MainActivity.onCreate(Unknown Source:0)
> 	at android.app.Activity.performCreate(Activity.java:8051)
> 	at android.app.Activity.performCreate(Activity.java:8031)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

With another app the Stacktrace is slightly different:

> Time	Device Name	Type	PID	Tag	Message
> 02-03 15:26:47.051	pixel_5_-_api_31_android_12	Info	7012	MonoDroid	android.runtime.JavaProxyThrowable: System.ArgumentException: uniqueName must not contain a .
>   at Xamarin.Forms.ExportEffectAttribute..ctor (System.Type effectType, System.String uniqueName) [0x00013] in <942f50a2f8f34eb98b8b2ca60dd3cb90>:0 
>   at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
>   at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) <0x75e0bef2bcb0 + 0x00060> in <8de75f4b631543d08af441f47c3410f1>:0 
>   at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) <0x75e0bef2bdd0 + 0x00070> in <8de75f4b631543d08af441f47c3410f1>:0 
>   at System.Reflection.RuntimeAssembly.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) <0x75e0bef41140 + 0x00012> in <8de75f4b631543d08af441f47c3410f1>:0 
>   at Xamarin.Forms.Internals.ReflectionExtensions.GetCustomAttributesSafe (System.Reflection.Assembly assembly, System.Type attrType) <0x75e0b5af65a0 + 0x00048> in <942f50a2f8f34eb98b8b2ca60dd3cb90>:0 
>   at Xamarin.Forms.Internals.Registrar.RegisterAll (System.Type[] attrTypes, Xamarin.Forms.InitializationFlags flags) <0x75e0b5af8500 + 0x00305> in <942f50a2f8f34eb98b8b2ca60dd3cb90>:0 
>   at Xamarin.Forms.Internals.Registrar.RegisterAll (System.Type[] attrTypes) <0x75e0b5af84c0 + 0x00024> in <942f50a2f8f34eb98b8b2ca60dd3cb90>:0 
>   at Xamarin.Forms.Forms.SetupInit (Android.Content.Context activity, System.Reflection.Assembly resourceAssembly, System.Nullable`1[T] maybeOptions) [0x001a7] in <a5e986d8b6584931a2ca203c438907dc>:0 
>   at Xamarin.Forms.Forms.Init (Android.Content.Context activity, Android.OS.Bundle bundle) <0x75e0b9b3e5a0 + 0x000d0> in <a5e986d8b6584931a2ca203c438907dc>:0 
>   at xx.xx.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00041] in <513d92df7b7c4e80b87acb3e50fc0572>:0 
>   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) <0x75e0bc35d910 + 0x00054> in <174d78cce7ab45b3b32d79d04d3d8c4f>:0 
>   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.35(intptr,intptr,intptr)
> 	at crc649f3cf79821103ecf.MainActivity.n_onCreate(Native Method)
> 	at crc649f3cf79821103ecf.MainActivity.onCreate(Unknown Source:0)
> 	at android.app.Activity.performCreate(Activity.java:8051)
> 	at android.app.Activity.performCreate(Activity.java:8031)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7839)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Steps to Reproduce

1. Create an new Android Emulator with API = 31
![image](https://user-images.githubusercontent.com/6727366/152391192-7eaa3a90-4b5c-45da-a7e4-f3ef27e71edf.png)

2. Run attached sample app in Release Mode

### Expected Behavior
App should start

### Actual Behavior
App crashes

### Basic Information

- Version with issue: latest XF
- Last known good version: -
- Platform Target Frameworks: 
  - Android: Android 12
- Android Support Library / AndroidX Version: 
- NuGet Packages: Default XF Nugets. All upadated to latest version
- Affected Devices: 

### Environment

<details><summary>Show/Hide Visual Studio info</summary>
Microsoft Visual Studio Enterprise 2022
Version 17.0.5
VisualStudio.17.Release/17.0.5+32112.339
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA240
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

ResXManager   ResXManager
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.343 (d17-0@fb07a17)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.183 (remotes/origin/d17-0@a351f0f1f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.4.0.0 (8fc41ae82)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
```

</details>

### Reproduction Link
[API31Crash.zip](https://github.com/xamarin/Xamarin.Forms/files/7996684/API31Crash.zip)

### Workaround
Delete bin/obj folder before deploy, but without success

**Comment by AlleSchonWeg** [comment]
After a litte bit more researching, i found two similar issues:
https://github.com/xamarin/xamarin-android/issues/4291
and 
https://github.com/xamarin/xamarin-android/issues/1842
