### ISSUE TITLE
VS Crashes with a Xamarin.Forms solution

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15242]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-Crashes-with-a-XamarinForms-solution/1461086)._

---
[regression]
File->New-> Xamarin.Forms

VS Crashes

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
   at System.Lazy`1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at SkiaSharp.SkiaApi.sk_version_get_milestone()
   at SkiaSharp.SkiaSharpVersion.get_Native()
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean)
   at SkiaSharp.SKObject.. cctor()

Exception Info: System.TypeInitializationException
   at SkiaSharp.SKObject.get_Handle()
   at SkiaSharp.SKNativeObject.Dispose(Boolean)
   at SkiaSharp.SKPictureRecorder.Dispose(Boolean)
   at SkiaSharp.SKNativeObject.Finalize()

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
   at System.Lazy`1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at SkiaSharp.SkiaApi.sk_version_get_milestone()
   at SkiaSharp.SkiaSharpVersion.get_Native()
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean)
   at SkiaSharp.SKObject.. cctor()

Exception Info: System.TypeInitializationException
   at SkiaSharp.SKObject.get_Handle()
   at SkiaSharp.SKNativeObject.Dispose(Boolean)
   at SkiaSharp.SKPictureRecorder.Dispose(Boolean)
   at SkiaSharp.SKNativeObject.Finalize()

---
#### Feedback Bot on 6/27/2021, 07:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Matthew Leibowitz [MSFT] on 6/28/2021, 07:03 AM: 

<p>What OS is this running on and which version of SkiaSharp is this? The exception is saying that it cannot find the native library, which may mean you are running on Linux since the native library is separate? If you are, did you install the SkiaSharp.NativeAssets.Linux package and install fontconfig? If you can’t/don’t want to install fontconfig and don’t mind not having advanced font lookup, you can install the SkiaSharp.NativeAssets.Linux.NoDependencies package.</p>

#### Rido [MSFT] on 6/28/2021, 04:11 PM: 

<p>I’m running Microsoft Windows [Version 10.0.19043.1052] and latest public VS 2022 preview.</p>
<p>Skia seems like an internal VS dependency so I dont think the solution is to install fontconfig or Skia packages manually.</p>
<p>Is this a known issue in latest VS 2022? If so… what’s the suggested workaround?</p>

#### Ben Buttigieg [MSFT] on 6/29/2021, 02:41 AM: 

(private comment, text removed)
#### Matthew Leibowitz [MSFT] on 6/29/2021, 08:10 AM: 

<p>Are you getting this in VS and not an app?</p>
<p>That is very interesting. I suppose we must wait for the VS team to comment, but maybe you have some extension install that is using SkiaSharp? It might be that the extension assumes it is 32-bit and they did not include the 64-bit native library.</p>
<p>Do you have some extensions installed that do image-y things?</p>

#### Jon Dick [MSFT] on 7/21/2021, 09:10 AM: 

<p>Can you please add some more information about the project you are working with and extensions you have installed in VS?</p>

#### Feedback Bot on 7/27/2021, 06:30 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Feedback Bot on 10/19/2021, 08:35 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Feedback Bot solved on 8/12/2021, 03:04 AM, 0 votes: 

We are unable to investigate this issue further without the additional information requested. If you are able to provide more information, you can request the issue being reactivate below. See our [guidelines](https://aka.ms/vsfeedbackguidelines) for further information about our process.

#### Rido [MSFT] on 10/15/2021, 04:22 PM: 

<p>This still happens in the latest preview (RC)</p>
<p>Fault bucket 2130173575309439573, type 5<br>
Event Name: CLR20r3<br>
Response: Not available<br>
Cab Id: 0</p>
<p>Problem signature:<br>
P1: MSBuild.exe<br>
P2: 17.0.0.48003<br>
P3: d7a4224b<br>
P4: SkiaSharp<br>
P5: 2.80.1.0<br>
P6: bd8a820b<br>
P7: 4b<br>
P8: 30<br>
P9: System.DllNotFoundException<br>
P10:</p>
<p>Attached files:<br>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER79DC.tmp.dmp<br>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER81EC.tmp.WERInternalMetadata.xml<br>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER823B.tmp.xml<br>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8259.tmp.csv<br>
\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER82C7.tmp.txt<br>
\?\C:\Users\rido2\AppData\Local\Temp\WER8347.tmp.appcompat.txt</p>
<p>These files may be available here:<br>
\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MSBuild.exe_d071cbd575d4613582e5585cd8996669fcbd951_0c18b6e5_1b71247b-3edd-4a3a-a3fc-d1a580766d05</p>
<p>Application: devenv.exe<br>
Framework Version: v4.0.30319<br>
Description: The process was terminated due to an unhandled exception.<br>
Exception Info: System.DllNotFoundException<br>
at SkiaSharp.LibraryLoader.LoadLocalLibrary[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]<br>
at System.Lazy<code>1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Lazy</code>1[[System.IntPtr, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()<br>
at SkiaSharp.SkiaApi.sk_version_get_milestone()<br>
at SkiaSharp.SkiaSharpVersion.get_Native()<br>
at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean)<br>
at SkiaSharp.SKObject…cctor()</p>
<p>Exception Info: System.TypeInitializationException<br>
at SkiaSharp.SKObject.get_Handle()<br>
at SkiaSharp.SKNativeObject.Dispose(Boolean)<br>
at SkiaSharp.SKPictureRecorder.Dispose(Boolean)<br>
at SkiaSharp.SKNativeObject.Finalize()</p>

**Comment by jfversluis** [comment]
Seems like an old issue. If you still find this original author, please let us know if this is still an issue. Thanks

**Comment by shubhamjainy** [comment]
I am facing the same issue. Is there any fix or resolution?
