### ISSUE TITLE
App dies with NullReferenceException if converter returns null

### ISSUE THREAD

**Issue by ydanila** [xamarin/Xamarin.Forms#2027]
### Steps to Reproduce
1.   Derive basic multi binding support classes from here https://gist.github.com/Keboo/0d6e42028ea9e4256715
2.  Create multibinding converter
```
public class AndBooleanConverter : IMultiValueConverter
{
	public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
	{
		var result = true;

		foreach(var val in values)
		{
			if(val == null)
			{
				//	Binding.DoNothing
				//	DependencyProperty.UnsetValue 
				return null;
			}

			if(val is IConvertible)
			{
				result = result && ((IConvertible)val).ToBoolean(CultureInfo.CurrentCulture);
			}
			else
			{
				throw new ArgumentException("Not boolean values not supported");
			}
		}

		return result;
	}
}
```
3.  Add biding to Grid object 
`
<Grid.IsVisible>
	<extensions:MultiBinding Converter="{StaticResource AndBooleanConverter}">
		<Binding Path="IsNotBusy" />
		<Binding Path="IsLoaded" />
	</extensions:MultiBinding>
</Grid.IsVisible>`

### Expected Behavior
Nothing changes as returned value not convertible.
### Actual Behavior
Dies with such stack trace.
```
   at Xamarin.Forms.VisualElement.<>c.<.cctor>b__213_2(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)
   at Xamarin.Forms.Binding.Apply(Object newContext, BindableObject bindObj, BindableProperty targetProperty)
   at Xamarin.Forms.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, Boolean fromStyle)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.TrySetBinding(Object element, BindableProperty property, String localName, Object value, IXmlLineInfo lineInfo, Exception& exception)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, String xaml)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at TestApp.MainPage.InitializeComponent()
   at TestApp.MainPage..ctor()
   at TestApp.App..ctor()
   at TestApp.UWP.MainPage..ctor()
   at TestApp.UWP.TestApp_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage()
   at TestApp.UWP.TestApp_UWP_XamlTypeInfo.XamlUserType.ActivateInstance()
```
### Basic Information

- Version with issue: 2.5.122203, 2.5.280555
- IDE: VS 2017
- Platform Target Frameworks: 
  - UWP:  Tested only for UWP 16299

### Reproduction Link

Test app  [https://github.com/ydanila/XFBugTest](https://github.com/ydanila/XFBugTest)

**Comment by hartez** [comment]
As far as I can tell, this is behaving as expected. The values you are passing into your AndBooleanConverter's `Convert` method are `null` (because they do no exist), so the method returns `null` (line 21). The Grid's `IsVisible` property requires a `bool`; when the value of `null` is applied, it throws an exception.

**Comment by ydanila** [comment]
If this is expected behaviour, how in this case I can tell XF to ignore wrong value(s)?

In WPF and UWP could be used Binding.DoNothing or DependencyProperty.UnsetValue .

For this moment used ugly hack 
`return new object()`

**Comment by hartez** [comment]
@ydanila For the moment, your `return new object()` workaround is your best bet (or simply returning `true` or `false`, whichever makes the most sense). Forms does not currently have the equivalent of either `Binding.DoNothing` or `DependencyProperty.UnsetValue`.
