### ISSUE TITLE
BindableProperty defaultValue 'Default value did not match return type'

### ISSUE THREAD

**Issue by Dabbel** [xamarin/Xamarin.Forms#2182]
### Description

Note: I replaced my actual app name with AppName.

**Property of control**
`
public string Message
{
    get { return (string)GetValue(MessageProperty); }
    set { SetValue(MessageProperty, value); }
}
`

**BindableProperty of control**
`
public static readonly BindableProperty MessageProperty = BindableProperty.Create(nameof(Message), typeof(string), typeof(Flyout), defaultValue: "");
`

**StackTrace**
`
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'AppName.Controls.Flyout' threw an exception. ---> System.ArgumentException: Default value did not match return type
Parameter name: defaultValue
   at Xamarin.Forms.BindableProperty..ctor(String propertyName, Type returnType, Type declaringType, Object defaultValue, BindingMode defaultBindingMode, ValidateValueDelegate validateValue, BindingPropertyChangedDelegate propertyChanged, BindingPropertyChangingDelegate propertyChanging, CoerceValueDelegate coerceValue, BindablePropertyBindingChanging bindingChanging, Boolean isReadOnly, CreateDefaultValueDelegate defaultValueCreator)
   at Xamarin.Forms.BindableProperty.Create(String propertyName, Type returnType, Type declaringType, Object defaultValue, BindingMode defaultBindingMode, ValidateValueDelegate validateValue, BindingPropertyChangedDelegate propertyChanged, BindingPropertyChangingDelegate propertyChanging, CoerceValueDelegate coerceValue, CreateDefaultValueDelegate defaultValueCreator)
   at AppName.Controls.Flyout..cctor()
   --- End of inner exception stack trace ---
   at AppName.Controls.Flyout.get_Message()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xamarin.Forms.BindingExpression.BindingExpressionPart.TryGetValue(Object source, Object& value)
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)
   at Xamarin.Forms.Binding.Apply(Object newContext, BindableObject bindObj, BindableProperty targetProperty)
   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext)
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.Grid.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Xamarin.Forms.BindableObject.set_BindingContext(Object value)
   at AppName.Controls.Flyout..ctor()
   at AppName.View.Tasks.TaskList.InitializeComponent()
   at AppName.View.Tasks.TaskList..ctor()
   at AppName.ViewModel.VMMainPage.<SetDetailPage>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()`

### Expected Behavior
Working BindableProperty

### Actual Behavior
System.ArgumentException: Default value did not match return type
Parameter name: defaultValue

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: New NETSTANDARD project for porting from PCL, the PCL project runs on version 2.5.0.91635
- IDE: Visual Studio 2017.6.4
- Platform Target Frameworks:
  - Android: Not tested myself but this seems to be the same error https://github.com/tiger4589/Xamarin.Forms-CardView/issues/7
  - UWP:  16299
- Nuget Packages: Xamarin.Forms 2.5.0.280555

**Comment by StephaneDelcroix** [comment]
Could you please create a very simple project triggering this issue ? This is very concerning, I'd like to investigate this really soon...

**Comment by Dabbel** [comment]
[BindingDefaultValue.zip](https://github.com/xamarin/Xamarin.Forms/files/1847153/BindingDefaultValue.zip)

Hope this helps

**Comment by StephaneDelcroix** [comment]
Yes, it helped.

The BindableProperty failing is not `MessageProperty`, but `FontSizeProperty`.
```
public static readonly BindableProperty FontSizeProperty = BindableProperty.Create(nameof(FontSize), typeof(double), typeof(Flyout), 18);
```
the parameter `18` without any type information will be created as an Int32 by the compiler and boxed
```
ldc.i4.s 18
box [mscorlib]System.Int32
```

the BP constructor will then check if the default parameter (an `Int32`) is of type `Double` and fail.

the correct way to declare your BindableProperty would be like this
```
public static readonly BindableProperty FontSizeProperty = BindableProperty.Create(nameof(FontSize), typeof(double), typeof(Flyout), 18d);
```

**Comment by Dabbel** [comment]
With the generic version it worked in my old code.

Maybe this code should check if the defaultValue is assigneable to the returnType and not of the same type?
`
if (defaultValue != null && !returnType.IsInstanceOfType(defaultValue))
				throw new ArgumentException("Default value did not match return type", "defaultValue");`

**Comment by StephaneDelcroix** [comment]
of course the generic version worked

**Comment by Dabbel** [comment]
And what is about not being that strict with the type check and use IsAssigneableFrom?
