### ISSUE TITLE
[UWP] Embedding Forms page in second UWP Window throws exception

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#2229]
This problem can be reproduced with the Embedding.UWP project on the https://github.com/xamarin/Xamarin.Forms/tree/embedding-uwp-multiwindow branch.

Launching a second UWP window and then attempting to embed a Forms page throws an unhandled exception. The exception occurs in Platform.cs, at

```
_container = new Canvas
{
	Style = (Windows.UI.Xaml.Style)Windows.UI.Xaml.Application.Current.Resources["RootContainerStyle"]
};
```

StackTrace:
```
   at System.Runtime.InteropServices.WindowsRuntime.IMap`2.Lookup(K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Lookup[K,V](IMap`2 _this, K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Get[K,V](K key)
   at Xamarin.Forms.Platform.UWP.Platform..ctor(Page page)
   at Xamarin.Forms.Platform.UWP.WindowsPlatform..ctor(Page page)
   at Xamarin.Forms.Platform.UWP.PageExtensions.ToFrameworkElement(VisualElement visualElement)
   at Xamarin.Forms.Platform.UWP.PageExtensions.CreateFrameworkElement(ContentPage contentPage)
   at Xamarin.Forms.Platform.UWP.FormsEmbeddedPageWrapper.OnNavigatedTo(NavigationEventArgs e)
```

**Comment by wachs** [comment]
Complementing the message above, we updated the LoadApplication method in WindowsBasePage to store the Dispatcher of the current application.

Upon window creating we are using the following code:
```
var windows = CoreApplication.Views;
            var currentAV = ApplicationView.GetForCurrentView();
            var newAV = CoreApplication.CreateNewView();
            await newAV.Dispatcher.RunAsync(
                            CoreDispatcherPriority.Normal,
                            async () =>
                            {
                                var newWindow = Window.Current;
                                var newAppView = ApplicationView.GetForCurrentView();
                                Windows.UI.Xaml.Controls.Frame frameContent = new Windows.UI.Xaml.Controls.Frame();
                                frameContent.Navigate(typeof(MainPageLite), "");
                                newWindow.Content = frameContent;
                                newWindow.Activate();
                                await ApplicationViewSwitcher.TryShowAsStandaloneAsync(
                                    newAppView.Id,
                                    ViewSizePreference.UseMinimum,
                                    currentAV.Id,
                                    ViewSizePreference.UseMinimum);
                            });
```

MainPageLite is a native page, with LoadApplication, for each window there is a new Application of Xamarin.Forms.Core.

Another relevant aspect is: we changed the OnChildAdded on the class Element to populate the WindowId property in its own constructor.

Also, we changed the PropertyChanged method in the BindingExpression class to query for the correct Dispacther for executing the update in right UI Thread.

Update:
Today, we moved the WindowId property to BindableObject class, to populate that in Behavior class.

**Comment by vcx** [comment]
See PR #2432

**Comment by PureWeen** [comment]
build --uitests

**Comment by samhouts** [comment]
Removing labels because this is active and in progress :)
