### ISSUE TITLE
Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

### ISSUE THREAD

**Issue by demiskefelegn** [xamarin/Xamarin.Forms#2458]
### Description

we are encountering the below error in production environment, the crash is causing in Android Version 6.0.1 and 5.0. We could't be able to reproduce and trace the error, here is the error log from App Center

Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.n_dispatchTouchEvent(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.Platform_DefaultRenderer.dispatchTouchEvent(Platform_DefaultRenderer.java:54)
android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:2717)
android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5129)
android.view.ViewGroup.removeAllViews(ViewGroup.java:5082)
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onDestroyView(Native Method)
md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onDestroyView(FragmentContainer.java:59)
android.support.v4.app.Fragment.performDestroyView(Fragment.java:2480)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:158)
android.app.ActivityThread.main(ActivityThread.java:7237)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

- Version with issue:

Android 6.0.1 
Android 5.0

- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   

- Affected Devices:

Galaxy Note3
Galaxy S6
Galaxy S6 Edge

your help is appreciated,

Regards

**Comment by GalaxiaGuy** [comment]
Hi @demiskefelegn,

May I suggest getting the "Raw" output from AppCenter? My issue (https://github.com/xamarin/Xamarin.Forms/issues/2444) looked similar, but after selecting the "Raw" tab, I found there was more detail available.

Although, despite looking similar (starting with `Java.Interop.JavaLocationException`), I don't think they are the same problem.

**Comment by demiskefelegn** [comment]
Dear GalaxiaGuy

here is the ROW output

Package: com.ethiopianairlines.ethiopianairlines
Version Code: 19
Version Name: 1.1.1
Android: 5.0
Android Build: LRX21V
Manufacturer: samsung
Model: SM-N9005
CrashReporter Key: c7944416-6322-4a39-817c-d70472824800
Start Date: 2018-04-12T19:21:36.102Z
Date: 2018-04-12T19:29:43.291Z

Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type ETMobileApp.Droid.AwesomeLabelRenderer from native handle 0xbefd540c (key_handle 0x131a6d5b).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00000] in <303b75409d4e4a17bc65607d320bb98e>:0
  at (wrapper dynamic-method) System.Object.c7acf54d-a0a8-4bfc-8575-ba6c358856dd(intptr,intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for ETMobileApp.Droid.AwesomeLabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <303b75409d4e4a17bc65607d320bb98e>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <303b75409d4e4a17bc65607d320bb98e>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:64)
      at android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:2600)
      at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4672)
      at android.view.ViewGroup.removeAllViews(ViewGroup.java:4623)
      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onDestroyView(Native Method)
      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onDestroyView(FragmentContainer.java:59)
      at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2480)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:145)
      at android.app.ActivityThread.main(ActivityThread.java:5938)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:580)
2   java.lang.Thread.getAllStackTraces(Thread.java:522)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:788)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)
5   md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_dispatchTouchEvent(VisualElementRenderer_1.java:-2)
6   md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:64)
7   android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:2600)
8   android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4672)
9   android.view.ViewGroup.removeAllViews(ViewGroup.java:4623)
10  md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onDestroyView(FragmentContainer.java:-2)
11  md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onDestroyView(FragmentContainer.java:59)
12  android.support.v4.app.Fragment.performDestroyView(Fragment.java:2480)
13  android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
14  android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
15  android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
16  android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
17  android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
18  android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
19  android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
20  android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
21  android.os.Handler.handleCallback(Handler.java:739)
22  android.os.Handler.dispatchMessage(Handler.java:95)
23  android.os.Looper.loop(Looper.java:145)
24  android.app.ActivityThread.main(ActivityThread.java:5938)
25  java.lang.reflect.Method.invoke(Method.java:-2)
26  java.lang.reflect.Method.invoke(Method.java:372)
27  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
28  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Thread 50769:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
2   java.lang.Thread.run(Thread.java:818)

Thread 50770:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
5   java.lang.Thread.run(Thread.java:818)

Thread 50771:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
2   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
3   java.lang.Thread.run(Thread.java:818)

Thread 50773:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
2   java.lang.Thread.run(Thread.java:818)

Thread 50774:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$GCDaemon.run(Daemons.java:341)
2   java.lang.Thread.run(Thread.java:818)

Thread 50783:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:143)
2   android.os.Looper.loop(Looper.java:130)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 50785:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50792:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50793:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50803:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

**Comment by demiskefelegn** [comment]
Dear GalaxiaGuy

here is the ROW output

Package: com.ethiopianairlines.ethiopianairlines
Version Code: 19
Version Name: 1.1.1
Android: 5.0
Android Build: LRX21V
Manufacturer: samsung
Model: SM-N9005
CrashReporter Key: c7944416-6322-4a39-817c-d70472824800
Start Date: 2018-04-12T19:21:36.102Z
Date: 2018-04-12T19:29:43.291Z

Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type ETMobileApp.Droid.AwesomeLabelRenderer from native handle 0xbefd540c (key_handle 0x131a6d5b).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <303b75409d4e4a17bc65607d320bb98e>:0
  at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00000] in <303b75409d4e4a17bc65607d320bb98e>:0
  at (wrapper dynamic-method) System.Object.c7acf54d-a0a8-4bfc-8575-ba6c358856dd(intptr,intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for ETMobileApp.Droid.AwesomeLabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <303b75409d4e4a17bc65607d320bb98e>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <303b75409d4e4a17bc65607d320bb98e>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_dispatchTouchEvent(Native Method)
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:64)
      at android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:2600)
      at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4672)
      at android.view.ViewGroup.removeAllViews(ViewGroup.java:4623)
      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onDestroyView(Native Method)
      at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onDestroyView(FragmentContainer.java:59)
      at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2480)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
      at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:145)
      at android.app.ActivityThread.main(ActivityThread.java:5938)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:580)
2   java.lang.Thread.getAllStackTraces(Thread.java:522)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:788)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)
5   md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_dispatchTouchEvent(VisualElementRenderer_1.java:-2)
6   md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.dispatchTouchEvent(VisualElementRenderer_1.java:64)
7   android.view.ViewGroup.cancelTouchTarget(ViewGroup.java:2600)
8   android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4672)
9   android.view.ViewGroup.removeAllViews(ViewGroup.java:4623)
10  md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onDestroyView(FragmentContainer.java:-2)
11  md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onDestroyView(FragmentContainer.java:59)
12  android.support.v4.app.Fragment.performDestroyView(Fragment.java:2480)
13  android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1422)
14  android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
15  android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
16  android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
17  android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
18  android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
19  android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
20  android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
21  android.os.Handler.handleCallback(Handler.java:739)
22  android.os.Handler.dispatchMessage(Handler.java:95)
23  android.os.Looper.loop(Looper.java:145)
24  android.app.ActivityThread.main(ActivityThread.java:5938)
25  java.lang.reflect.Method.invoke(Method.java:-2)
26  java.lang.reflect.Method.invoke(Method.java:372)
27  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
28  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Thread 50769:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
2   java.lang.Thread.run(Thread.java:818)

Thread 50770:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
5   java.lang.Thread.run(Thread.java:818)

Thread 50771:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
2   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
3   java.lang.Thread.run(Thread.java:818)

Thread 50773:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
2   java.lang.Thread.run(Thread.java:818)

Thread 50774:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$GCDaemon.run(Daemons.java:341)
2   java.lang.Thread.run(Thread.java:818)

Thread 50783:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:143)
2   android.os.Looper.loop(Looper.java:130)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 50785:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50792:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50793:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

Thread 50803:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1220)
2   sun.misc.Unsafe.park(Unsafe.java:299)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:818)

**Comment by GalaxiaGuy** [comment]
@demiskefelegn In the email that notified me of this comment the stack trace was longer. I think you cut off a bit that is important, specifically `System.MissingMethodException: No constructor found for ETMobileApp.Droid.AwesomeLabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)`

That suggests it is the same problem, something calling the missing `Label(IntPtr javaReference, JniHandleOwnership transfer)` constructor.

I assume you aren't subclassing the Android Label fast renderer (since the fast renderers are sealed)? If you are subclassing the normal renderer you may be able to work around it by adding:

```
pubilc AwesomeLabelRenderer(IntPtr javaReference, JniHandleOwnership transfer) : base(javaReference, transfer)
{
}
```

**Comment by demiskefelegn** [comment]
thank you, i will try your sugguestion
