### ISSUE TITLE
[UWP] ImageSource.FromResource(Source) with embedded image => System.Reflection.TargetException

### ISSUE THREAD

**Issue by davefxy** [xamarin/Xamarin.Forms#2597]
### Description
Tried to get an embedded resource from XAML :
 Image Source="{local:ImageResource WorkingWithImages.beach.jpg}" 
 or from cs file :
 new Label { Text = "WorkingWithImages.beach.jpg embedded resource" }.

### Steps to Reproduce

1. Convert the WorkingWithImages sample to Cross-Platform, Net Standard Library.
https://github.com/xamarin/xamarin-forms-samples/WorkingWithImages
I used the latest version of the sample(April 13, 2018) for the conversion to Net Standard Library.
2.   Run the app and it will break with a System.Reflection.TargetException error.
3. I am not familiar enough with this error to troubleshoot using the Xamarin.Forms source any further.

### Expected Behavior
Return the ImageSource for the embedded beach.jpg image.
### Actual Behavior
Causes a System.Reflection.TargetException error as a result of this line of code in the ImageResourceExtension method in the file EmbeddedImageResourceExtension.cs :
			var imageSource = ImageSource.FromResource(Source); 
### Basic Information
I am using the most current version of Xamarin Forms. I also performed this test with the Xamarin.Forms source as described by this Website : https://blog.xamarin.com/debugging-xamarin-forms/
I also ran the Android version and the error did not occur. I stepped through the same code (in ImageResourceExtension method) and it successfully returned the image.

The line of code causing the issue is in this file :
  Xamarin.Forms\Xamarin.Forms.Core\ImageSource.cs module, 
in this method :
  public static ImageSource FromResource(string resource, Assembly sourceAssembly = null)
on this line:
sourceAssembly = (Assembly)callingAssemblyMethod.Invoke(null, new object[0]);
with this error:
System.Reflection.TargetException
  HResult=0x80131603
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xamarin.Forms.ImageSource.FromResource(String resource, Assembly sourceAssembly) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Core\ImageSource.cs:line 76
   at XFPkgTest.ImageResourceExtension.ProvideValue(IServiceProvider serviceProvider) in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest\EmbeddedImageResourceExtension.cs:line 21
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.ProvideValue(Object& value, ElementNode node, Object source, XmlName propertyName) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\ApplyPropertiesVisitor.cs:line 237
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\ApplyPropertiesVisitor.cs:line 102
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlNode.cs:line 149
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlNode.cs:line 143
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlNode.cs:line 145
   at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlNode.cs:line 203
   at Xamarin.Forms.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlLoader.cs:line 141
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, String xaml) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlLoader.cs:line 89
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\XamlLoader.cs:line 68
   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType) in D:\GotHub_Projs\Xamarin.Forms\Xamarin.Forms.Xaml\ViewExtensions.cs:line 36
   at XFPkgTest.EmbeddedImagesXaml.InitializeComponent() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest\obj\Debug\netstandard2.0\XFPkgTest.EmbeddedImagesXaml.xaml.g.cs:line 19
   at XFPkgTest.EmbeddedImagesXaml..ctor() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest\EmbeddedImagesXaml.xaml.cs:line 12
   at XFPkgTest.App..ctor() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest\App.xaml.cs:line 28
   at XFPkgTest.UWP.MainPage..ctor() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest.UWP\MainPage.xaml.cs:line 24
   at XFPkgTest.UWP.XFPkgTest_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 255
   at XFPkgTest.UWP.XFPkgTest_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in D:\UWP\Android\Test\XFPkgTest\XFPkgTest\XFPkgTest.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 476
   
Using the immediate window to examine the callingAssemblyMethod at the time of the error:
   {System.Reflection.Assembly GetCallingAssembly()}
       Attributes: Public | Static | HideBySig | RequireSecObject
    CallingConvention: Standard
    ContainsGenericParameters: false
    CustomAttributes: Count = 0
    DeclaringType: {System.Reflection.Assembly}
    IsAbstract: false
    IsAssembly: false
    IsConstructedGenericMethod: false
    IsConstructor: false
    IsFamily: false
    IsFamilyAndAssembly: false
    IsFamilyOrAssembly: false
    IsFinal: false
    IsGenericMethod: false
    IsGenericMethodDefinition: false
    IsHideBySig: true
    IsPrivate: false
    IsPublic: true
    IsSecurityCritical: true
    IsSecuritySafeCritical: false
    IsSecurityTransparent: false
    IsSpecialName: false
    IsStatic: true
    IsVirtual: false
    MemberType: Method
    MetadataToken: 100674009
    MethodHandle: {System.RuntimeMethodHandle}
    MethodImplementationFlags: IL
    Module: {System.Private.CoreLib.dll}
    Name: "GetCallingAssembly"
    ReflectedType: {System.Reflection.Assembly}
    ReturnParameter: {System.Reflection.Assembly }
    ReturnType: {System.Reflection.Assembly}
    ReturnTypeCustomAttributes: {System.Reflection.Assembly }

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   

Universal Windows Target Version: 10.0.16299.0
Xamarin.Forms   <Version>2.5.1.444934</Version>
Microsoft.NETCore.UniversalWindowsPlatform     <Version>6.1.2</Version>

- Android Support Library Version: 
- Nuget Packages:

- Affected Devices:

### Reproduction Link

[EmbeddedImageTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1972260/EmbeddedImageTest.zip)

**Comment by hartez** [comment]
The attached repro project doesn't seem to even work on Android, but I can confirm that if you clone the https://github.com/xamarin/xamarin-forms-samples repo and try to run the WorkingWithImages project in UWP, this error does occur.

**Comment by davefxy** [comment]
You are correct about my last attempt to recreate the problem. I came up with a better one by stripping my original sample port to the minimum. Here it is. It is interesting I couldn't recreate the problem with a new project.
[WorkingWithImagesTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1976737/WorkingWithImagesTest.zip)

**Comment by davefxy** [comment]
I discovered the reason my first attempt didn't reproduce the same results as the originally ported sample. There was an additional lines in the ported sample repo project that weren't in the new project I created to reproduce the problem. The following lines were in the WorkingWithImages.csproj that were not in my newly created projects EmbeddedImageTest.csproj:
  <ItemGroup>
    <EmbeddedResource Update="EmbeddedImagesXaml.xaml">
      <Generator>MSBuild:Compile</Generator>
    </EmbeddedResource>
  </ItemGroup>
