### ISSUE TITLE
Can not tap on ui element

### ISSUE THREAD

**Issue by IlyaDhtvzGhbltn** [xamarin/Xamarin.Forms#2771]
### Description
I detected very strange behavior on Xamarin UI test. The issue is - framework can not tap on some marked elements. This absolutely random problem. Issue may appear on Physical Device or Simulator, Android or iOS, old or new OS Systems.
### Steps to Reproduce

Any Element, in any moment when you try to tap him can be not react. The second Tap can help.

### Expected Behavior
Tap on marked Element, then Open new View.
### Actual Behavior
Tap not worked like on logs.
### Basic Information

- IDE: Visual Studio 2017
- Platform Target Frameworks : Xamarin.Forms 2.4.0
- Nunit : 3.1
- Xamarin UI test : 2.2.4
- Affected Devices: Samsung A310F (physical).
- Android target Sdk Version : 19

### Logs

```
[5/18/2018 12:57:16 PM Informational] ------ Run test started ------

[5/18/2018 12:57:56 PM Informational] Waiting for element matching Marked("IDTransHistory").
[5/18/2018 12:58:03 PM Informational] Using element matching Marked("IDTransHistory").
[5/18/2018 12:58:04 PM Informational] Tapping coordinates [ 532, 1114 ].
[5/18/2018 12:58:05 PM Informational] Waiting for element matching Marked("Filter").
[5/18/2018 12:58:08 PM Informational] Using element matching Marked("Filter").
[5/18/2018 12:58:08 PM Informational] Tapping coordinates [ 684, 96 ].
[5/18/2018 12:58:24 PM Informational] Error while performing Tap(Marked("Date.Start"))
Exception: System.Exception: Unable to find element. Query for Marked("Date.Start") gave no results.
   at Xamarin.UITest.SharedApp.FirstWithLog[T](T[] results, ITokenContainer tokenContainer)
   at Xamarin.UITest.Android.AndroidApp.<Tap>c__AnonStoreyB.<>m__0()
   at Xamarin.UITest.Utils.ErrorReporting.With(Action func, Object[] args, String memberName)
[5/18/2018 12:58:24 PM Informational] Waiting for element matching Marked("Filter").
[5/18/2018 12:58:28 PM Informational] Using element matching Marked("Filter").
[5/18/2018 12:58:28 PM Informational] Tapping coordinates [ 684, 96 ].
[5/18/2018 12:58:32 PM Informational] Using element matching Marked("Date.Start").
[5/18/2018 12:58:32 PM Informational] Tapping coordinates [ 71, 298 ].
[5/18/2018 12:58:35 PM Informational] Using element matching Text("2018").
[5/18/2018 12:58:35 PM Informational] Tapping coordinates [ 139, 228 ].
==========

```
Ok, as you can see the element marked Filter was using -> Tapping coordinates [ 684, 96 ]. That's mean that element is exist on monitor. But first time this not worked. Test on Single Device may be failed today and passed tomorrow. Perfectly floating error.
### Scenario Code

```
app.WaitForElement(x => x.Marked("IDTransHistory"));
app.Tap(x => x.Marked("IDTransHistory"));
try
        {
            app.WaitForElement(x => x.Marked("Filter"));
            app.Tap(x => x.Marked("Filter"));
        }
        catch (Exception)
        {
            try
            {
                app.Tap(x => x.Marked("Button.Home"));
                app.Tap(x => x.Marked("IDTransHistory"));
            }
            catch (Exception)
            {
                try
                {
                    app.Tap(x => x.Marked("Button.Home"));
                    app.Tap(x => x.Marked("IDTransHistory"));
                }
                catch (Exception)
                {
                    app.Tap(x => x.Marked("Button.Home"));
                    app.Tap(x => x.Marked("IDTransHistory"));
                }
            }
        }
```

**Comment by pauldipietro** [comment]
What happens if you update to the 3.0 stable or 3.1-pre? Can you upload a reproduction, even if it requires a number of runs to reproduce?

**Comment by IlyaDhtvzGhbltn** [comment]
@pauldipietro  if I use NUnit 3.0  :: 
` Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing`

**Comment by pauldipietro** [comment]
I mean XF 3.0/3.1, as the report indicates you're on 2.4 ("Platform Target Frameworks: Xamarin.Forms 2.4.0"), unless I'm misreading.

**Comment by IlyaDhtvzGhbltn** [comment]
XF 3.0 is unstable. We received  some ui errors on XF 3.0. and now our app worck stable on 2.4 only.

**Comment by PureWeen** [comment]
No updates in the last 30 days. If you're still having an issue please let us know and we can re-open
