### ISSUE TITLE
Xamarin.Forms.Platform.Android.SwitchRenderer.UpdateOnColor () throws NRE Exception on android

### ISSUE THREAD

**Issue by softsan** [xamarin/Xamarin.Forms#3147]
### Description
We updated latest of Xamarin.forms v 3.1.0.583944 and on android 8.0 it crashes with exception details below. We used `switch` in one of the page:

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.Android.SwitchRenderer.UpdateOnColor () [0x00078] in <7999cc4bd5664eca8a72469344172ca3>:0 
  at Xamarin.Forms.Platform.Android.SwitchRenderer.Android.Widget.CompoundButton.IOnCheckedChangeListener.OnCheckedChanged (Android.Widget.CompoundButton buttonView, System.Boolean isChecked) [0x00016] in <7999cc4bd5664eca8a72469344172ca3>:0 
  at Android.Widget.CompoundButton+IOnCheckedChangeListenerInvoker.n_OnCheckedChanged_Landroid_widget_CompoundButton_Z (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_buttonView, System.Boolean isChecked) [0x0000f] in <d6a544155d4e4629ab4abf6b6d559591>:0 
  at (wrapper dynamic-method) System.Object.44c09ad3-6222-4d7d-85b9-34891139c349(intptr,intptr,intptr,bool)
	at md51558244f76c53b6aeda52c8a337f2c37.SwitchRenderer.n_onCheckedChanged(Native Method)
	at md51558244f76c53b6aeda52c8a337f2c37.SwitchRenderer.onCheckedChanged(SwitchRenderer.java:46)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
	at android.widget.Switch.setChecked(Switch.java:1075)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
 

### Expected Behavior
It should work with `Switch` control.
### Actual Behavior
App crashes on opening that particular page containing the `Switch` control 
### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 3.0.0.561731
- IDE: VS for mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android 8 onwards.
  - 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms -Version 3.1.0.583944
- Affected Devices: Android Google pixel, pixel 2

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by LateNiteWorker** [comment]
The same NRE happened to me when I upgraded to Xamarin.Forms 3.1.0.583944 (from 2.5.x).
Target device: Samsung Galaxy S7, Android 8.

The error happens after I open the page with Switch that has IsToggled=true, and tap on it to turn it off. The NRE occurs during the tap.
In this case, when I open the page, the Switch (when IsToggled=true) is rendered the same as if IsToggled would be false.

On the other hand, if I open the page with Switch that has IsToggled=false, I can tap on it and it toggles and renders OK.

**Comment by PureWeen** [comment]
This is only an issue when using the non appcompat and will be fixed in this PR

https://github.com/xamarin/Xamarin.Forms/pull/3099

One fix would be to start using AppCompat
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat

But if that's not possible it will be fixed in an upcoming service release.

**Comment by ajfear1975** [comment]
Hi. I am getting similar behaviour in Switches which are rendered as true initially. I am using the latest AppCompat in my XF project (27.0.2.1).  This is fine on iOS. 
https://forums.xamarin.com/discussion/91713/switch-example-in-xaml?

**Comment by godevrepo** [comment]
Same issue here as @ajfear1975. True initialized Switches are crashing the app even though we are using AppCompat.

**Comment by PureWeen** [comment]
@ajfear1975  @godevrepo   if you can open a new issue with an example that would be helpful.  Are you also on the latest 3.1 version of XF?

**Comment by godevrepo** [comment]
Sure, I'll do that tomorrow. But i am on the latest version on NuGet 3.1.0.583944 which is from 06/20, so could the fix possibly not be included?

**Comment by PureWeen** [comment]
The fix for this only applied to non AppCompat so if you're having the issue while using AppCompat then it's a different issue

**Comment by godevrepo** [comment]
Nevermind, tested it today and it works. It just made me wondering as I was inheriting from FormsAppCompatActivity and had this issue.
