### ISSUE TITLE
[Android] Crash when page has bottom tabs after update to 3.1.0.637273 only under release build

### ISSUE THREAD

**Issue by xalikoutis** [xamarin/Xamarin.Forms#3294]
### Description
After updated to 3.1.0 Service Release 1 every page with bottom tab pages crashes, but only if Android app is build with release and runs under it
### Steps to Reproduce

1. Android app with bottom tab pages
2. Build Release with (Bundle assemblies, enable multi-dex, sdk assemblies only)
3. Run it

### Expected Behavior
To run
### Actual Behavior
When you visit a page with bottom tabs crashes with the following stack trace
```
ExceptionDispatchInfo.Throw ()
Java.Lang.RuntimeException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(android.content.res.ColorStateList)' on a null object reference
ExceptionDispatchInfo.Throw ()
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms)
MenuBuilder.Add (System.Int32 group, System.Int32 id, System.Int32 categoryOrder, Java.Lang.ICharSequence title)
IMenuExtensions.Add (Android.Views.IMenu self, System.Int32 groupId, System.Int32 itemId, System.Int32 order, System.String title)
TabbedPageRenderer.SetupBottomNavigationView (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
TabbedPageRenderer.OnChildrenCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
TabbedPageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e)
VisualElementRenderer`1[TElement].SetElement (TElement element)
IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element)
Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Support.V4.App.FragmentManager fragmentManager, Android.Content.Context context)
FragmentContainer.OnCreateView (Android.Views.LayoutInflater inflater, Android.Views.ViewGroup container, Android.OS.Bundle savedInstanceState)
Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_inflater, System.IntPtr native_container, System.IntPtr native_savedInstanceState)
(wrapper dynamic-method) System.Object.317f1106-6a08-4b54-9ced-0b242d850f62(intptr,intptr,intptr,intptr,intptr)
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(android.content.res.ColorStateList)' on a null object reference
android.support.design.internal.BottomNavigationItemView.setTextColor(BottomNavigationItemView.java:250)
android.support.design.internal.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:278)
android.support.design.internal.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)
android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:291)
android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1051)
android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1078)
android.support.design.internal.BottomNavigationMenu.addInternal(BottomNavigationMenu.java:56)
android.support.v7.view.menu.MenuBuilder.add(MenuBuilder.java:475)
md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
android.os.Handler.handleCallback(Handler.java:789)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:172)
android.app.ActivityThread.main(ActivityThread.java:6637)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version:3.1.0.583944
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.1  
- Android Support Library Version: 27.0.2

**Comment by pauldipietro** [comment]
I just tested this against an 8.1 emulator and can't reproduce a crash. Would you mind uploading a reproduction of your own?

**Comment by nhdanh** [comment]
I have same problem on my project. It crashed when I update XF

**Comment by PureWeen** [comment]
@nhdanh  can you upload a reproduction? We haven't been able to cause it to crash internally

**Comment by Daniel-NP** [comment]
I have the same problem. UWP works fine, Android crashes (Debug-Mode). Android Support Library Version: 27.0.2.1. Xamarin.Forms v3.1.0.583944 also doesn't work.
After 2 hours of nuget-hell I deleted the bin- and obj-folders and tada.... it worked -.-

**Comment by minaairsupport** [comment]
I have the same issue , how you fix this issue and why its closed

**Comment by PureWeen** [comment]
@minaairsupport can you create a new issue with a reproduction so we can address your issue?

**Comment by vincentcastagna** [comment]
Hello @PureWeen 

I'm meeting this prob, only in release mode, app crashes on every tabbedPage for which I set the toolbarPlacement to bottom. 

```
 On<Xamarin.Forms.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
            On<Xamarin.Forms.PlatformConfiguration.Android>().SetBarSelectedItemColor(Constants.PrimaryColorOrange);
```
When I remove these line no more crash. 

**Error :** 

```
MonoDroid	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.internal.BaselineLayout" on path: DexPathList[[zip file "/data/app/com.MyProject.app-AWwG7bMaYlEiJgEc6jyCpA==/base.apk"],nativeLibraryDirectories=[/data/app/com.MyProject.app-AWwG7bMaYlEiJgEc6jyCpA==/lib/arm64, /data/app/com.MyProject.app-AWwG7bMaYlEiJgEc6jyCpA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:84)
	at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:77)
	at android.support.design.internal.BottomNavigationItemView.<init>(BottomNavigationItemView.java:73)
	at android.support.design.internal.BottomNavigationMenuView.getNewItem(BottomNavigationMenuView.java:571)
	at android.support.design.internal.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:507)
	at android.support.design.internal.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:62)
	at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
	at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
	at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1096)
	at android.support.design.internal.BottomNavigationMenu.addInternal(BottomNavigationMenu.java:55)
	at android.support.v7.view.menu.MenuBuilder.add(MenuBuilder.java:482)
	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onCreateView(Native Method)
	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onCreateView(FragmentContainer.java:33)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

I'm on Xamarin Forms 3.5.0.129452 & Xamarin.Android libraries 28.0.0.1 and targetting Android pie 9.0

**Comment by pjc0247** [comment]
Also happened to me, Update nuget package and remove `bin` and `obj` dir solves my problem.

**Comment by pjc0247** [comment]
I think this is temporary solution, after some modifications it happens again.
