### ISSUE TITLE
System.Reflection.TargetException: Object does not match target type. on navigating backwards

### ISSUE THREAD

**Issue by StephanBis** [xamarin/Xamarin.Forms#3597]
### Description
The app runs fine and exactly as expected on Android. But when I test it out on UWP the app crashes whenever I navigate back from a NavigationPage (detail page). I attached a stack trace at the end of this issue.

### Steps to Reproduce

1. Go into a details view
2. Try to navigate back (physical back button or PopAsync())

### Expected Behavior
That the master view gets shown as it does in Android

### Actual Behavior
The app crashes with a System.Reflection.TargetException: Object does not match target type.

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: N/A
- IDE: Visual Studio 2017 Enterprise 15.8.0
- Platform Target Frameworks: 
  - Android: 9 (also 8.1 worked fine)  
  - UWP: 17134  
- Android Support Library Version: 27.0.2 
- Nuget Packages: AutoMapper, Autofac, RestSharp, Telerik.UI.for.Xamarin, Vapolia.XamarinFormsGesture, Newtonsoft.Json, Microsoft.IdentityModel.Clients.ActiveDirectory

### Stack trace
   ```
at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xamarin.Forms.BindingExpression.BindingExpressionPart.TryGetValue(Object source, Object& value)
   at Xamarin.Forms.BindingExpression.Unapply()
   at Xamarin.Forms.Binding.Unapply(Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.Grid.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Xamarin.Forms.Element.OnBindingContextChanged()
   at Xamarin.Forms.View.OnBindingContextChanged()
   at Xamarin.Forms.Grid.OnBindingContextChanged()
   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Telerik.XamarinForms.Common.UWP.RadViewContainer.UpdateChildAndContent()
   at Telerik.XamarinForms.Common.UWP.RadViewContainer.OnLoaded(Object sender, RoutedEventArgs e)

```

**Comment by kingces95** [comment]
I'm unable to reproduce this issue on UAP with latest 3.2.0 branch. Please include a reproduction.

Thanks!

**Comment by StephanBis** [comment]
Thank you for your reply.
My project contains sensitive information and I can't really delete parts of it. How do you suggest we proceed?

**Comment by StephanBis** [comment]
Thanks for your reply.
We've found the problem. We are using the Telerik.Xamarin.UI.ListView control and it throws the mentioned exception whenever we want to bind to a three-level deep property in a ListView template. One and two levels property access is working fine.

This result in an exception:
`<Label Text="{Binding Prop1.Prop2.Prop3}" />`

This does not:
`<Label Text="{Binding Prop1.Prop2}" />`

We'll mention this problem to Telerik, so you can close this issue.
Thank you for your time.
