### ISSUE TITLE
System.NullReferenceException when editing XAML with Xamarin Live Reload

### ISSUE THREAD

**Issue by RaulBastian** [xamarin/Xamarin.Forms#3658]
When editing a XAML file, for instance, the background color of a ListView, with Xamarin Live Reload I get the following exception in UWP:

```
Exception thrown at 0x740DDDC2 (KernelBase.dll) in App1.UWP.exe: WinRT originate error - 0x80004003 : 'System.NullReferenceException: Object reference not set to an instance of an object.

at Xamarin.Forms.Platform.UWP.ListViewRenderer.<OnCollectionChanged>b__15_0()
at Xamarin.Forms.Platform.UWP.WindowsBasePlatformServices.<>c__DisplayClass2_0.<BeginInvokeOnMainThread>b__0()'.

Exception thrown at 0x740DDDC2 (KernelBase.dll) in App1.UWP.exe: WinRT originate error - 0x80004003 : 'System.NullReferenceException: Object reference not set to an instance of an object.

   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()'.

Exception thrown at 0x740DDDC2 (KernelBase.dll) in App1.exe: WinRT originate error - 0x80004003 : 'Object reference not set to an instance of an object.'.
```

### Steps to Reproduce
1.  Launch UWP application with Xamarin Live Reload.
2.  Edit Xaml file and save.

Sample XAML file:
```
<?xml version="1.0" encoding="utf-8" ?>
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
                  xmlns:local="clr-namespace:Northwind.Forms.Effects"
                  xmlns:behavior="clr-namespace:Northwind.Forms.EventToCommandBehavior"
                  prism:ViewModelLocator.AutowireViewModel="True"
                  x:Class="Northwind.Forms.Views.NorthwindMasterDetail">
    <MasterDetailPage.Master>
        <ContentPage Title="Menu">
            <ListView BackgroundColor="Yellow"  ItemsSource="{Binding MenuItems}">
                <ListView.Behaviors>
                    <behavior:EventToCommandBehavior EventName="ItemSelected" 
                                                     Command="{Binding NavigateCommand}">
                    </behavior:EventToCommandBehavior>
                </ListView.Behaviors>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout>
                                <Label Text="{Binding .}"></Label>
                                <Label Text="{Binding .}"></Label>
                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </ContentPage>
    </MasterDetailPage.Master>
</MasterDetailPage>

```

ViewModel:
```
public class NorthwindMasterDetailViewModel : BindableBase
	{
        private DelegateCommand<SelectedItemChangedEventArgs> navigateCommand = null;
        private INavigationService navigationService = null;
        private ObservableCollection<string> menuItems = null;


        public NorthwindMasterDetailViewModel(INavigationService navigationService)
        {
            this.navigationService = navigationService;
            this.MenuItems = new ObservableCollection<string>(new string[] { "Customers","Products" });
            
        }

        public ObservableCollection<string> MenuItems {
            get
            {
                return menuItems;
            }
            set
            {
                this.menuItems = value;
            }
        }


        public DelegateCommand<SelectedItemChangedEventArgs> NavigateCommand {
            get {
                return navigateCommand ?? (navigateCommand = new DelegateCommand<SelectedItemChangedEventArgs>(async (parameter) => {
                    await navigationService.NavigateAsync(parameter.SelectedItem.ToString());
                }));
            }
        }

        
	}
```

- IDE: Visual Studio 2017 15.8.1
- Platform Target Frameworks:
  - UWP:  Fall Creators Update 16299 
- Nuget Packages: PRISM.Core v7.0.0.396, Xamarin Live Reload v0.3.27, Xamarin.Forms v3.1.0.697729
- Affected Devices: Windows 10 Professional

**Comment by rmarinho** [comment]
Hi can you try this from the website docs and see if it helps:

"Editing XAML while debugging UWP may cause a runtime crash. Workaround: Use Start without Debugging (Ctrl + F5) instead of Start Debugging (F5)." 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload#known-issues

**Comment by RaulBastian** [comment]
Hi, I did, I tried it as stated in the docs, 'without debugging'. I also tried in debug mode, release mode, and directly from the deployed app from Windows 10.

**Comment by PureWeen** [comment]
Live Reload issues aren't handled here

Can you bring this issue up in the Gitter channel for Live Reload?
https://gitter.im/xamarin/live-reload

They should be able to help you there
