### ISSUE TITLE
[Feedback] System.NotImplementedException in Xamarin WPF

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3737]
### Description

<p>When clearing a observablecollection or removing an item from it, we get a 

System.NotImplementedException: 'The method or operation is not implemented.'

error in the WPF implementation of Xamarin. In Android and UWP, the error does not occur.</p><p><br></p><p><span style="display:inline !important;float:none;background-color:rgba(255, 255, 255, 1);color:rgb(33, 33, 33);font-size:14px;font-style:normal;font-variant:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:left;text-decoration:none;text-indent:0px;text-transform:none;white-space:normal;word-spacing:0px;">We attach a mini solution with which you can reproduce the problem. We have noticed that if we enclose the Clear() method in a try / catch structure, the Exception is ignored and the program continues correctly (list clears and rebuilds).This exception only happens in WPF, UWP and Android work correctly.</span><b></b><i></i><u></u><sub></sub><sup></sup><strike></strike><br></p><p><b></b><i></i><u></u><sub></sub><sup></sup><strike></strike><br></p>
<a href="https://developercommunity.visualstudio.com/content/problem/272352/systemnotimplementedexception-in-xamarin-wpf.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632874">original linked feedback ticket</a>.

### Source

[678647](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678647)

**Comment by SoundAxis** [comment]
Same problem in my application, here's what I saw with the events being called:

ListView Item clicked:
ItemsPage Disappear
ItemsPage Appear
Item Appear
ItemsPage Disappear

Back button clicked:
Item Disappear
ItemsPage Appear
Item Appear
Item Disappear

**Comment by john4242** [comment]
I think I am getting the same error, for me it's a ListView (TemplatedItemList), but it sounds similar.
I can also attach a stack trace:

```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at Xamarin.Forms.Internals.TemplatedItemsList`2.System.Collections.IList.Contains(Object item) in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:line 276
   at System.Windows.Data.ListCollectionView.InternalContains(Object item)
   at System.Windows.Data.ListCollectionView.Contains(Object item)
   at System.Windows.Controls.ItemCollection.Contains(Object containItem)
   at System.Windows.Controls.Primitives.Selector.CoerceSelectedItem(DependencyObject d, Object value)
   at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValue(DependencyProperty dp, Object value)
   at System.Windows.DependencyObject.CoerceValue(DependencyProperty dp)
   at System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ListView.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.RefreshOrDefer()
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:line 771
   at Xamarin.Forms.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:line 1097
   at Xamarin.Forms.Internals.TemplatedItemsList`2.OnItemsSourceChanged(Boolean fromGrouping) in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:line 945
   at Xamarin.Forms.Internals.TemplatedItemsList`2.BindableOnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:line 661
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName) in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:line 150
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName) in D:\a\1\s\Xamarin.Forms.Core\Element.cs:line 381
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:line 620
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:line 417
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget) in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:line 173
   at Xamarin.Forms.BindingExpression.Apply(Boolean fromTarget) in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:line 57
   at Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0() in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:line 615
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at TestApp.WPF.App.Main()
```

**Comment by jsuarezruiz** [comment]
Can you attach an repro sample?

**Comment by DennisWelu** [comment]
This looks related to these two:
- https://github.com/xamarin/Xamarin.Forms/issues/3648
- https://github.com/xamarin/Xamarin.Forms/issues/3309

And yes I suffer from this as well! :-)

**Comment by jsuarezruiz** [comment]
Ok, I will review it!

**Comment by jsuarezruiz** [comment]
PR sent!
