### ISSUE TITLE
[Feedback] Microsoft's exception handling (non)strategy

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3870]
### Description

Im getting an Ambiguous match found with the following stack trace:
 ```  
      at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperty(Type type, String name)
   at Xamarin.Forms.Setter.&lt;Xamarin.Forms.Xaml.IValueProvider.ProvideValue&gt;b__9_0()
   at Xamarin.Forms.Xaml.TypeConversionExtensions.&lt;&gt;c__DisplayClass1_0.&lt;ConvertTo&gt;b__0()
   at Xamarin.Forms.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider)
   at Xamarin.Forms.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 minfoRetriever, IServiceProvider serviceProvider)
   at Xamarin.Forms.Xaml.ValueConverterProvider.Convert(Object value, Type toType, Func`1 minfoRetriever, IServiceProvider serviceProvider)
   at Xamarin.Forms.Setter.Xamarin.Forms.Xaml.IValueProvider.ProvideValue(IServiceProvider serviceProvider)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.ProvideValue(Object&amp; value, ElementNode node, Object source, XmlName propertyName)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.FillResourceDictionariesVisitor.Visit(ElementNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, String xaml)
   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, String xaml)
   at MSI.GRO.Mobile.Application.GroApplication.&lt;ReadResourceDictionaries&gt;d__5.MoveNext()
   ```
   I'm not reporting the fact that I got the exception, however I'm reporting on the lack of a decent exception handling strategy, one that will help all us poor developers out here to solve the problems with our code.
   
   In the exception i'm now getting (Ambiguous match found) I have no clue as to what property is ambiguous except spending untold hours going through my code, if that is where the problem is. Let alone if its somewhere deep inside XF code.
   
   However GetPropertyImpl does know what property it is. The first parameter to the method is the name of the property. It would take a minute's coding and nanoseconds of processing to include the name of the property in the message. If name was null or empty then (hopefully) that would be a different exception.
   
   Also I notice Exception has a Dictionary called Data. I don't recall ever seeing any data in this. Maybe once in many years of using visual studio.
   
   If an exception occurred then handling the exception correctly is more important then the overhead in actually handling the exception.
   
   As an aside it is perfectly valid to get an Ambiguous match exception. What if I new'd a property, which is perfectly valid in C# and a perfectly valid coding strategy.
   
   This is a reflection of using C# since its inception.
   
   I realise I'm pushing the proverbial up hill to not get a need more info to this report.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/323117/microsofts-exception-handling-nonstrategy.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672938">original linked feedback ticket</a>.

### Source

[689689](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/689689)

**Comment by nbevans** [comment]
Also:

UWP exception traces are even worse. Sometimes they are completely unusable! This is no fault of Xamarin though - it seems to be just how UWP is.

**Comment by StephaneDelcroix** [comment]
2 actionable points here:
- fix the root cause of the bug in XF. we shouldn't throw generic exception. do we have a repro ?
- send a PR for better exception message upstream every time we get one...
