### ISSUE TITLE
[UWP] PopAsync() crashes when navigating back to a page with a ListView with grouping after an item has been removed

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#3887]
### Description

Similar to Issue #3333, we're still seeing an exception from PopAsync() in v3.2.0.839982, however instead of a null reference it's now:
System.ArgumentException: 'Value does not fall within the expected range.'

### Steps to Reproduce

1. Add items to a bound ListView that uses grouping
   * Press the "Add Item" button in the attached example 3 times to add that manyitems
2. Navigate to the page displaying the list and delete one of the items (The "List View Page"
   * Select the "List View Page" sidebar menu item in the attached example
3. Delete one of the items
   * Using the "Remove" button in the attached example
4. Navigate away from the page displaying the list
   * Select the "Add Item Page" sidebar menu item in the attached example
5. Navigate back to the page display the list
   * Select the "List View Page" sidebar menu item in the attached example

### Expected Behavior

We should be able to navigate to back a page after removing an item without causing an exception

### Actual Behavior

The exception System.ArgumentException is thrown

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: Unknown, but it also crashes in 3.0.0.561731
- IDE: Visual Studio 2017 15.7.6
- Platform Target Frameworks:
  - UWP:  16299
- Affected Devices: UWP Windows Desktop

### Screenshots

1. Press the "Add Item" button in the attached example 3 times to add that manyitems
![image](https://user-images.githubusercontent.com/10836879/45978349-22c7c400-c01a-11e8-8de9-786c72414fe7.png)

3. Delete one of the items
![image](https://user-images.githubusercontent.com/10836879/45978371-35da9400-c01a-11e8-9ab2-64af7fbe3e3d.png)

Screenshot of the crash

![image](https://user-images.githubusercontent.com/10836879/45978392-468b0a00-c01a-11e8-932d-b9cbd7c23b3b.png)

### Reproduction Link

[Issue3333ArgumentException.zip](https://github.com/xamarin/Xamarin.Forms/files/2412818/Issue3333ArgumentException.zip)

**Comment by rmarinho** [comment]
still a issue with 3.3.0-pre1

**Comment by DennisWelu** [comment]
I have a very similar issue to this, minus the PopAsync. Maybe is related. Grouped ListVIew, removing/adding items dynamically...if I tap on an item that is not the first item in its group I'm getting this exception:

```
Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Windows.UI.Xaml.Controls.Primitives.Selector.put_SelectedIndex(Int32 value)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnElementItemSelected(Object sender, SelectedItemChangedEventArgs e)
   at Xamarin.Forms.ListView.OnSelectedItemChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)
   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnListItemClicked(Object sender, ItemClickEventArgs e)

```

**Comment by DennisWelu** [comment]
I can't figure it out exactly, but it seems to be a function of how many items are in the groups. If I have enough items in the groups then it doesn't happen. If I remove a bunch of items from a bunch of the groups (working with 32 groups in this case) then it starts crashing w/ the previously posted stack.

**Comment by DennisWelu** [comment]
FWIW... This was still an issue in XF 3.4.x (on UWP, not on iOS or Android) so I debugged into the ListViewRenderer and on the last line:

    List.SelectedIndex = index;

It would give the mentioned exception. The index appears calculated correctly as AFAIK. But the List only has a single item in it. So something is amiss by the time this method runs. So I went back to see how things were getting added to the list.

In my case I was using an extended ObservableCollection class that has an AddRange to avoid Add (and subsequent notification) call for each item. (This gets used for items in a group to simulate the expand/collapse of a group). When I switched to calling Add for each item instead of AddRange then the exception/crash went away. So that's my workaround for now!

**Comment by fbregeon** [comment]
Hello, 
i have similar problem in XF 3.6.
to workaround, i put XF ListView.SelectedItem to null.

To reproducde with attached project : 
1) add 3 items
2) go to "List View Page"
[Issue3333ArgumentException.zip](https://github.com/xamarin/Xamarin.Forms/files/3247652/Issue3333ArgumentException.zip)

3) remove all items 
4) go to "Add Item Page" 
5) add 3 items
6) go to "List View Page"
7) crash : 
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Controls.Primitives.Selector.put_SelectedIndex(Int32 value)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnElementItemSelected(Object sender, SelectedItemChangedEventArgs e)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.SetupVisualElement(VisualElement view)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.Load()
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.GetOrCreateRenderer(VisualElement self)
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.SetPage(Page page, Boolean isAnimated, Boolean isPopping)
   at Xamarin.Forms.Platform.UWP.NavigationPageRenderer.OnPopToRootRequested(Object sender, NavigationRequestedEventArgs e)
   at Xamarin.Forms.NavigationPage.<PopToRootAsyncInner>d__83.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.NavigationPage.<PopToRootAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Issue3333ArgumentException.FramePage.<NavigateTo>d__15.MoveNext() in C:\temp\Issue3333ArgumentException\Issue3333ArgumentException\Issue3333ArgumentException\FramePage.xaml.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Issue3333ArgumentException.FramePage.<OnMenuItemTapped>d__17.MoveNext() in C:\temp\Issue3333ArgumentException\Issue3333ArgumentException\Issue3333ArgumentException\FramePage.xaml.cs:line 62

**Comment by Ichiban08** [comment]
I see the exact same issue as DennisWelu on XF 4.1.0.581479

**Comment by nschoenberg** [comment]
I've got here by searching on google for ' Xamarin.Forms.Platform.UWP.ListViewRenderer.OnElementItemSelected'

So I have a very similar StackTrace in my App using XF 4.4. Can add more Details if required
