### ISSUE TITLE
java.lang.NoSuchMethodError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendBatchUpdate(FFIZFFFFFFFF)V"

### ISSUE THREAD

**Issue by JulienDollon** [xamarin/Xamarin.Forms#3981]
### Description

App crash while starting

### Basic Information

Version with issue: 3.2.0.839982
Platform Target Frameworks:
Android: Target Framework 8.1
Affected Devices:
Mate 9 | Android 7.0
Pixel | Android 8.0
Pixel 2 | Android 9
Galaxy S9

FATAL EXCEPTION: main
Process: com.app, PID: 12329
java.lang.NoSuchMethodError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendBatchUpdate(FFIZFFFFFFFF)V"
	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementTracker_AttachTracker.n_onViewAttachedToWindow(Native Method)
	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementTracker_AttachTracker.onViewAttachedToWindow(VisualElementTracker_AttachTracker.java:31)
	at android.view.View.dispatchAttachedToWindow(View.java:15553)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2955)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1648)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6763)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
	at android.view.Choreographer.doCallbacks(Choreographer.java:735)
	at android.view.Choreographer.doFrame(Choreographer.java:667)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by samhouts** [comment]
@JulienDollon Thank you for reporting this issue. Are you using Visual Studio for Mac or Windows? If you restart Visual Studio and rebuild the app, does it work?

**Comment by JulienDollon** [comment]
I do use VS for Mac. I've rebooted VS multiple times and cleaning solution / removing obj/debug folders this doesn't help.

**Comment by JulienDollon** [comment]
FYI it always worked before, the only thing I did is upgrade to 3.2 from 3.1

**Comment by samhouts** [comment]
Just confirming, you did it in this order?

- close VS
- delete bin/obj
- open VS

**Comment by JulienDollon** [comment]
Just did again just in case. Same thing.

**Comment by kingces95** [comment]
@JulienDollon Can you please attach a reproduction?

**Comment by StephanBis** [comment]
We are experiencing the exact same issue. Started when we upgraded to version 3.2.*. Our project is targeting Android 9.0 and we're running Visual Studio on Windows.
The strange part is that the app runs fine via ADB on our 9.0 and 8.1 emulator AND even on a 8.0 physical device. But when we actually run the app after installation, it results in an immediate crash.

**Comment by Aguilex** [comment]
@JulienDollon we've done some further research on this problem, and coincidentally, it looks like we may have already resolved this in VS for Mac 7.7 Preview 3 (build 7.7.0.1470), which is in the VS for Mac beta channel... we published this on October 2.  Would it be possible for you to switch to update to all of the preview builds in the beta channel, and let us know if the issue is resolved?

@StephanBis same request for you please... we published Visual Studio (on Windows) 15.9 Preview 3 on October 2 as well, and here too, we expect the issue to be resolved in this preview. Would you please confirm?

**Comment by JulienDollon** [comment]
Trying to use preview right now. @kingces95 how to attach a repro? First timer here.

**Comment by JulienDollon** [comment]
It is fixed with the new VS upgrade. Coooool!!

**Comment by JulienDollon** [comment]
Well played @Aguilex

**Comment by Aguilex** [comment]
Actually, credit goes to @samhouts as she made the connection between an internal bug report and this one. I'm glad we were able to solve the problem. And we're looking into our processes to identify how we missed this in the first place.

**Comment by qubuss** [comment]
Today I have this error and only in release and sign app. I have VS for Mac

**Comment by gidgol** [comment]
yep i have the same problem.....

**Comment by TermanEmil** [comment]
Deleting the all the obj and restarting VS helped me too.

**Comment by jrgsc** [comment]
Just got this issue today after switching from VS Community to VS Pro. Deleting the bin/obj folders then restarting VS did not work. 

Problem was resolved only after switching to VS Pro Preview.

**Comment by matpag** [comment]
Same problem for me with VS for Mac 7.6.11 (build 9) on Mojave 10.14.1. 
Deleting all the obj folders and restarting VS as suggested worked for me too.
