### ISSUE TITLE
Native Views feature throw error when use native splitview wrap forms'control

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#4050]
Fine code:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="FeatureSample.Views.MainView"
             xmlns:viewModelBase="clr-namespace:FeatureSample.ViewModels.Base;assembly=FeatureSample"
             viewModelBase:ViewModelLocator.AutoWireViewModel="True"
             xmlns:i18n="clr-namespace:FeatureSample.Services.LocalizationV2;assembly=FeatureSample"
             xmlns:ios="clr-namespace:UIKit;assembly=Xamarin.iOS;targetPlatform=iOS"
             xmlns:win="clr-namespace:Windows.UI.Xaml.Controls;assembly=Windows, Version=255.255.255.255,Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime;targetPlatform=Windows"
             xmlns:androidWidget="clr-namespace:Android.Widget;assembly=Mono.Android;targetPlatform=Android"       
             xmlns:androidLocal="clr-namespace:SimpleColorPicker.Droid;assembly=SimpleColorPicker.Droid;targetPlatform=Android">
    <NavigationPage.HasNavigationBar>false</NavigationPage.HasNavigationBar>
    <ContentPage.Content>
        <win:SplitView IsPaneOpen="true"
                       DisplayMode="Inline"
                                OpenPaneLength="296">
            <win:SplitView.Pane>
                <win:TextBlock Text="Pane"

                   FontSize="24"

                   VerticalAlignment="Center"

                   HorizontalAlignment="Center"/>
            </win:SplitView.Pane>
            <win:SplitView.Content>
                <win:TextBlock Text="Content"

                   FontSize="24"

                   VerticalAlignment="Center"

                   HorizontalAlignment="Center"/>
            </win:SplitView.Content>
            
        </win:SplitView>
    </ContentPage.Content>
</ContentPage>
```

Error code:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="FeatureSample.Views.MainView"
             xmlns:viewModelBase="clr-namespace:FeatureSample.ViewModels.Base;assembly=FeatureSample"
             viewModelBase:ViewModelLocator.AutoWireViewModel="True"
             xmlns:i18n="clr-namespace:FeatureSample.Services.LocalizationV2;assembly=FeatureSample"
             xmlns:ios="clr-namespace:UIKit;assembly=Xamarin.iOS;targetPlatform=iOS"
             xmlns:win="clr-namespace:Windows.UI.Xaml.Controls;assembly=Windows, Version=255.255.255.255,Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime;targetPlatform=Windows"
             xmlns:androidWidget="clr-namespace:Android.Widget;assembly=Mono.Android;targetPlatform=Android"       
             xmlns:androidLocal="clr-namespace:SimpleColorPicker.Droid;assembly=SimpleColorPicker.Droid;targetPlatform=Android">
    <NavigationPage.HasNavigationBar>false</NavigationPage.HasNavigationBar>
    <ContentPage.Content>
        <win:SplitView IsPaneOpen="true"
                       DisplayMode="Inline"
                                OpenPaneLength="296">
            <win:SplitView.Pane>
                <Entry Placeholder="test"></Entry>
            </win:SplitView.Pane>
            <win:SplitView.Content>
                <win:TextBlock Text="Content"

                   FontSize="24"

                   VerticalAlignment="Center"

                   HorizontalAlignment="Center"/>
            </win:SplitView.Content>
            
        </win:SplitView>
    </ContentPage.Content>
</ContentPage>
```

error message :

Position 18:18. Cannot assign property "Pane": Property does not exist, or is not assignable, or mismatching type between value and property

stack trace:
   ```
at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, String xaml)
   at Xamarin.Forms.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at FeatureSample.Views.MainView.InitializeComponent()
   at FeatureSample.Views.MainView..ctor()
```

**Comment by GalaxiaGuy** [comment]
I've not used native views, so the following is a guess:

Since `SplitView` is a UWP control, `SplitView.Pane` needs to be a UWP control, not a Forms view. Using `win:TextBox` instead of `Entry` may work.

None of the examples of native views I've seen try to embed native views within others so I don't know if this is even implemented.

**Comment by GalaxiaGuy** [comment]
I was looking at the code that handles the native views (mainly to see how possible #4048 would be) and it might be possible to do this. As a warning, this is just from browsing on Github - I've never tried to actual modify any of the code in question.

The methods here: https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.UAP/NativeBindingService.cs (and in the versions in the other platforms) could be made to handle Forms elements and get the native control from it instead of just checking for a native control directly.

For this issue specifically, I think it would only be possible in the `TrySetValue` case, but something like the following might work:

```csharp
public bool TrySetValue(object target, BindableProperty property, object value)
{
    var view = target as FrameworkElement;
    if (view == null)
    {
        // This is for handling #4048 native property on Xamarin Forms element
        if (target is Element element)
        {
            view = element.GetRenderer() as FrameworkElement;
            if (view == null)
                return false;
        }
    }
    // This is for handling #4050 assigning native value from a Xamarin Forms element
    if (value is Element element)
    {
        value = element.GetRenderer();
    }
    view.SetValue(property, value);
    return true;
}
```

**Comment by jingliancui** [comment]
that amazing，it's said that it is possible to use the native element to wrap the forms' element ?
Hope Xamarin.forms' team bring this feature asap.

**Comment by hartez** [comment]
This is not currently a supported scenario, but I'll move it to the Enhancements board so we can think about whether to support it in the future.

**Comment by jingliancui** [comment]
Got it . hope this help you:
Why i want this feature ,because some time the MasterDetailPage is hard to unify its feature for each platform . So i think use this feature to detail the action for each platform.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
