### ISSUE TITLE
Xamarin.form used DevExpress.Mobile.Grid error 

### ISSUE THREAD

**Issue by huanglang009** [xamarin/Xamarin.Forms#4182]
### Description
I failed to use DevExpress.Mobile.Grid 18.1 in the version of Vs17 15.8.4. Its XAML preview will appear wrong.
If I remove the gridGridControl ,it can work.
### Steps to Reproduce
1. 
![image](https://user-images.githubusercontent.com/17918276/47327297-47f23580-d69f-11e8-9ffc-e0ddee005ac0.png)
2. 
Creating LibraryClassLoader in shadow copy path C:\Users\JOEY\AppData\Local\Temp\AndroidDesignerJars994446485898105334
Setting id 1 on newly created ClassLoader

Trying to load class xamarindesigner.AndroidFormsPreviewerRenderer

Failed to process message Load
mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
	at mono.android.DesignerSession.load(DesignerSession.java:314)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at DevExpress.Mobile.DataGrid.Android.GridControlRenderer.OnAttachedToWindow () [0x00027] in <937935b5294242ed83fc7cd199f6e007>:0 
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.13(intptr,intptr)
	at md5e5922db9c610ffb731cc3ab124393be0.GridControlRenderer.n_onAttachedToWindow(Native Method)
	at md5e5922db9c610ffb731cc3ab124393be0.GridControlRenderer.onAttachedToWindow(GridControlRenderer.java:63)
	at android.view.View.dispatchAttachedToWindow(View.java:17445)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:334)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
	at mono.android.DesignerSession.load(DesignerSession.java:307)
	... 4 more

3. 
`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="LoginNavigation.MRGPage"
             Title="MRG" 
    xmlns:dxg="clr-namespace:DevExpress.Mobile.DataGrid;assembly=DevExpress.Mobile.Grid.v18.1" >
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Return" Clicked="ToolbarItem_Clicked_1" />
    </ContentPage.ToolbarItems>
    <ContentPage.Content>
            <ScrollView>
            <StackLayout VerticalOptions="StartAndExpand"  CompressedLayout.IsHeadless="true">
                <Button Text="Work" BackgroundColor="Red" Font="50" WidthRequest="200" Clicked="Button_Clicked" />
                <Entry x:Name="Barcode" Placeholder="Barcode" Completed="Barcode_Completed"/>
                
                <Button Text="data" BackgroundColor="Green" Font="40" WidthRequest="200" Clicked="Button_Clicked_1"  />
                <Entry x:Name="Barcode3" Placeholder="Barcode3"/>
                <dxg:GridControl x:Name="grid1" ItemsSource="{Binding}" NewItemRowVisibility="True" IsReadOnly="False" AutomationId="1" ClassId="1" StyleId="1" >
                </dxg:GridControl>
            </StackLayout>
            
        </ScrollView>
        
    </ContentPage.Content>
  
</ContentPage>
`
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/17918276/47327542-4a08c400-d6a0-11e8-94f6-874797cf402f.png)

### Reproduction Link

> VS bug [#712850](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/712850)

**Comment by StephaneDelcroix** [comment]
from @alanmcgovern 
> It should work in the new branch :stuck_out_tongue:
> #BugSolved
