### ISSUE TITLE
[Android] Previewer System.DllNotFoundException: e_sqlite3

### ISSUE THREAD

**Issue by Mvassli** [xamarin/Xamarin.Forms#4189]
### Description
Trying to preview Android app, but previewer throws an exception. 

### Expected Behavior
Previewer should render successfully 
### Actual Behavior
Crashed with exception

```
Creating LibraryClassLoader in shadow copy path C:\Users\Magnus\AppData\Local\Temp\AndroidDesignerJars3540164574073909296
Setting id 1 on newly created ClassLoader

Trying to load class xamarindesigner.AndroidFormsPreviewerRenderer

Failed to process message Load
mono.android.DesignerException: System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3
	at mono.android.DesignerException.fromThrowable(DesignerException.java:54)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:235)
	at mono.android.DesignerSession.load(DesignerSession.java:314)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:675)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3
  at (wrapper managed-to-native) SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_libversion_number()
  at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number () [0x00000] in <18970a0afc7f4ff79ddf6a2303a8754b>:0 
  at SQLitePCL.raw.SetProvider (SQLitePCL.ISQLite3Provider imp) [0x00008] in <6c81c50555334bedbd88534becf30d81>:0 
  at SQLitePCL.Batteries_V2.Init () [0x00005] in <089e75ea5306497b83b6e1606896c7dd>:0 
  at SQLite.SQLiteConnection..cctor () [0x00010] in <eaa146ee868043e287f5507c8701ad9e>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Artsfiske.MainPage.OnAppearing () [0x00008] in C:\Users\Magnus\source\repos\Artsfiske\Artsfiske\Artsfiske\MainPage.xaml.cs:21 
  at Xamarin.Forms.Page.SendAppearing () [0x00024] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:311 
  at Xamarin.Forms.Platform.Android.PageRenderer.OnAttachedToWindow () [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:42 
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a10f61e70eeb434e952fef884856c199>:0 
  at (wrapper dynamic-method) System.Object.11(intptr,intptr)
	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.n_onAttachedToWindow(Native Method)
	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.onAttachedToWindow(PageRenderer.java:55)
	at android.view.View.dispatchAttachedToWindow(View.java:17445)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:334)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:270)
	at mono.android.DesignerSession.load(DesignerSession.java:307)
	... 4 more


```
### Basic Information

- Version with issue:  3.1.0.697729
- Last known good version:
- IDE: VS Community 2017
- Platform Target Frameworks: 
  - Android: Android  8.1
- Nuget Packages: sql-lite-pcl (1.5.231),  SQLitePCLRaw.bundle_e_sqlite3

### Screenshots

![image](https://user-images.githubusercontent.com/44413320/47390952-e078cc00-d718-11e8-9200-834df67924de.png)
![image](https://user-images.githubusercontent.com/44413320/47391065-2170e080-d719-11e8-9a91-735841d7c4b3.png)

### Reproduction Link

> VS bug [#713941](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713941)

**Comment by samhouts** [comment]
@Mvassli Are you still experiencing this issue? If so, can you please attach a small project that demonstrates this issue? Thanks!

**Comment by drewgillies** [comment]
This is simply a limitation of the technology and is therefore an unsupported scenario--we shouldn't be loading a database in a previewer session. Closing.
