### ISSUE TITLE
Xamarin Forms iOS Previewer - no longer works after upgrading to Visual Studio 15.9.1

### ISSUE THREAD

**Issue by maitlandmarshall** [xamarin/Xamarin.Forms#4462]
### Description

Xamarin Forms iOS Previewer - no longer works after upgrading to Visual Studio 15.9.1

### Steps to Reproduce

1. Upgrade to VS 15.9.1 on Windows
2. Upgrade Xamarin.iOS on Mac to 12.2.1.10
3. Open Xamarin Forms Previewer

### Expected Behavior
You can see the rendered form

### Actual Behavior
The iOS renderer requires an active connection to your Mac agent to function. Please re-connect to your Mac to enable this feature.

In the iOSDesigner log file:
````
[2018-11-19 14:33:41.4] PERF: Deployment time: 2299ms
[2018-11-19 14:33:42.0] INFO: Last login: Mon Nov 19 14:32:58 2018

[2018-11-19 14:33:42.0] INFO:  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/maitland/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-19 14:33:42.0] INFO: Maitlands-MacBook-Pro-2:~ maitland$  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/maitland/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-19 14:33:42.0] INFO: Initializing CSProxyHost StdOut
[2018-11-19 14:33:42.0] INFO: Initializing CSProxyHost StdErr
[2018-11-19 14:33:42.1] INFO: 2018-11-19 14:34:21.446 mono64[57906:361466] 
[2018-11-19 14:33:42.1] INFO: Unhandled Exception:
[2018-11-19 14:33:42.1] INFO: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.DynamicRegistrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-19 14:33:42.1] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x10ea7ac40()
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-19 14:33:42.1] INFO: [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at Registrar.DynamicRegistrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-19 14:33:42.1] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x10ea7ac40()
[2018-11-19 14:33:42.1] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:42.1] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-19 14:33:42.1] INFO: <<<<< Designer Remote Agent EOS >>>>>
[2018-11-19 14:33:42.2] ERROR: Could not connect to the remote mac:
System.IO.EndOfStreamException: The DesignerAgent crashed before it initialized
   at MonoTouch.Design.Client.SshAgentLauncher.StartCSProxyHost(SshClient client, String csproxyHostPath) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 116
   at MonoTouch.Design.Client.SshAgentLauncher.LaunchAsync(ConnectionInfo info, String csproxyHostDirectory, CancellationToken token) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 78
   at MonoTouch.Design.Client.SshAgentLauncher.<>c__DisplayClass6_0.<LaunchAsync>b__0() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.SshAgentLauncher.<LaunchAsync>d__6.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.RemoteDesignerAgent.<CreateConnectionAsync>d__16.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\RemoteDesignerAgent.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Forms.Previewer.VisualStudioIosXamlRenderer.<RenderXamls>d__5.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.VisualStudio\src\VisualStudio.Forms.Previewer\VisualStudioIosXamlRenderer.cs:line 37
[2018-11-19 14:33:42.3] INFO: VisualStudioIosXamlRenderer took 3207.5303ms to finish processing 1 scene(s).
[2018-11-19 14:33:44.6] PERF: Deployment time: 2313ms
[2018-11-19 14:33:45.0] INFO: AndroidXamlRenderer took 5971.7169ms to finish processing 4 scene(s).
[2018-11-19 14:33:45.3] INFO: Last login: Mon Nov 19 14:34:21 2018 from 192.168.0.77

[2018-11-19 14:33:45.3] INFO:  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/maitland/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-19 14:33:45.3] INFO: Maitlands-MacBook-Pro-2:~ maitland$  /Library/Frameworks/Mono.framework/Commands/mono64 /Users/maitland/Library/Caches/Xamarin/XMA/Agents/Designer/agent-128ba449cfdfbb78efcd87c831a9fd807dae2e5d/CSProxyHost.exe; echo "<<<<< Designer Remote Agent EOS >>>>>";
[2018-11-19 14:33:45.3] INFO: Initializing CSProxyHost StdOut
[2018-11-19 14:33:45.3] INFO: Initializing CSProxyHost StdErr
[2018-11-19 14:33:45.4] INFO: 2018-11-19 14:34:24.760 mono64[58211:363040] 
[2018-11-19 14:33:45.4] INFO: Unhandled Exception:
[2018-11-19 14:33:45.4] INFO: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.DynamicRegistrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-19 14:33:45.4] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x104719c40()
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-19 14:33:45.4] INFO: [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar+ObjCType.Add (Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00019] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar.RegisterTypeUnsafe (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x01181] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.Registrar.RegisterType (System.Type type, System.Collections.Generic.List`1[System.Exception]& exceptions) [0x00013] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at Registrar.DynamicRegistrar.Register (System.Type type) [0x00003] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0016a] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.RegisterAssembly (System.IntPtr a) [0x00007] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.register_assembly (System.IntPtr assembly, System.Int32& exception_gchandle) [0x00005] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO: --- End of stack trace from previous location where exception was thrown ---
[2018-11-19 14:33:45.4] INFO:   at (wrapper managed-to-native) System.Object.wrapper_native_0x104719c40()
[2018-11-19 14:33:45.4] INFO:   at ObjCRuntime.Runtime.EnsureInitialized () [0x0004b] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at AppKit.NSApplication.Init () [0x00016] in <8bd87b64da7f487db4b141d49d248114>:0 
[2018-11-19 14:33:45.4] INFO:   at CSProxyHost.MainClass.Main (System.String[] args) [0x000b0] in <859b10803c674bad953a45c2be47ba13>:0 
[2018-11-19 14:33:45.5] INFO: <<<<< Designer Remote Agent EOS >>>>>
[2018-11-19 14:33:45.5] ERROR: Could not connect to the remote mac:
System.IO.EndOfStreamException: The DesignerAgent crashed before it initialized
   at MonoTouch.Design.Client.SshAgentLauncher.StartCSProxyHost(SshClient client, String csproxyHostPath) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 116
   at MonoTouch.Design.Client.SshAgentLauncher.LaunchAsync(ConnectionInfo info, String csproxyHostDirectory, CancellationToken token) in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 78
   at MonoTouch.Design.Client.SshAgentLauncher.<>c__DisplayClass6_0.<LaunchAsync>b__0() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.SshAgentLauncher.<LaunchAsync>d__6.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\SshAgentLauncher.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTouch.Design.Client.RemoteDesignerAgent.<CreateConnectionAsync>d__16.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.iOS\MonoTouch.Design.Client\Connection\RemoteDesignerAgent.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.Forms.Previewer.VisualStudioIosXamlRenderer.<RenderXamls>d__5.MoveNext() in E:\A\_work\28\s\Xamarin.Designer.VisualStudio\src\VisualStudio.Forms.Previewer\VisualStudioIosXamlRenderer.cs:line 37
[2018-11-19 14:33:45.6] INFO: VisualStudioIosXamlRenderer took 3289.8491ms to finish processing 3 scene(s).
````

**Comment by maitlandmarshall** [comment]
Fixed in Visual Studio 15.9.2

https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#issues-fixed-in-1592
