### ISSUE TITLE
Xamarin Forms 3.4 Android 4.2.X and 4.4.X Crash

### ISSUE THREAD

**Issue by OmegaPrimeZ3** [xamarin/Xamarin.Forms#4476]
### Description
Since updating our project to Xamarin Forms 3.4, end users have reported crashes on 4.2.X and 4.4.X devices. Application opens then immediately crashes with the your app has stopped message. Stack Trace attached.

### Expected Behavior
App doesnt crash

### Actual Behavior
App Crashes

### Basic Information

I/MonoDroid( 8488): UNHANDLED EXCEPTION:
I/MonoDroid( 8488): Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
I/MonoDroid( 8488):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <de97da4d1dd24b0c9a7b6ab6fc6aafc7>:0
I/MonoDroid( 8488):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <de97da4d1dd24b0c9a7b6ab6fc6aafc7>:0
I/MonoDroid( 8488):   at Android.Views.View.Draw (Android.Graphics.Canvas canvas) [0x00031] in <9bd62627b8d54b0c86391160af131fee>:0
I/MonoDroid( 8488):   at Xamarin.Forms.Platform.Android.ScrollViewRenderer.Draw (Android.Graphics.Canvas canvas) [0x0000d] in <02db0bcb95874f4db06b80f38eac4adf>:0
I/MonoDroid( 8488):   at Android.Views.View.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x00011] in <9bd62627b8d54b0c86391160af131fee>:0
I/MonoDroid( 8488):   at (wrapper dynamic-method) System.Object.46(intptr,intptr,intptr)
I/MonoDroid( 8488):   --- End of managed Java.Lang.Error stack trace ---
I/MonoDroid( 8488): java.lang.StackOverflowError
I/MonoDroid( 8488): 	at android.view.HardwareCanvas.<init>(HardwareCanvas.java:29)
I/MonoDroid( 8488): 	at android.view.GLES20Canvas.<init>(GLES20Canvas.java:101)
I/MonoDroid( 8488): 	at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:39)
I/MonoDroid( 8488): 	at android.view.GLES20RecordingCanvas.obtain(GLES20RecordingCanvas.java:45)
I/MonoDroid( 8488): 	at android.view.GLES20DisplayList.start(GLES20DisplayList.java:61)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13330)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.widget.ListView.drawChild(ListView.java:3363)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2465)
I/MonoDroid( 8488): 	at android.widget.ListView.dispatchDraw(ListView.java:3358)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.AbsListView.draw(AbsListView.java:3824)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
I/MonoDroid( 8488): 	at android.widget.ScrollView.draw(ScrollView.java:1603)
I/MonoDroid( 8488): 	at md51558244f76c53b6aeda52c8a337f2c37.ScrollViewRenderer.n_draw(Native Method)
I/MonoDroid( 8488): 	at md51558244f76c53b6aeda52c8a337f2c37.ScrollViewRenderer.draw(ScrollViewRenderer.java:51)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13364)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14190)
I/MonoDroid( 8488): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
I/MonoDroid( 8488): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
I/MonoDroid( 8488): 	at android.view.View.draw(View.java:14476)
I/MonoDroid( 8488): 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
I/MonoDroid( 8488): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2329)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13369)
I/MonoDroid( 8488): 	at android.view.View.getDisplayList(View.java:13411)
I/MonoDroid( 8488): 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
I/MonoDroid( 8488): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
I/MonoDroid( 8488): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2377)
I/MonoDroid( 8488): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
I/MonoDroid( 8488): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
I/MonoDroid( 8488): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
I/MonoDroid( 8488): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
I/MonoDroid( 8488): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
I/MonoDroid( 8488): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
I/MonoDroid( 8488): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
I/MonoDroid( 8488): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
I/MonoDroid( 8488): 	at android.os.Handler.handleCallback(Handler.java:733)
I/MonoDroid( 8488): 	at android.os.Handler.dispatchMessage(Handler.java:95)
I/MonoDroid( 8488): 	at android.os.Looper.loop(Looper.java:149)
I/MonoDroid( 8488): 	at android.app.ActivityThread.main(ActivityThread.java:5045)
I/MonoDroid( 8488): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/MonoDroid( 8488): 	at java.lang.reflect.Method.invoke(Method.java:515)
I/MonoDroid( 8488): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
I/MonoDroid( 8488): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
I/MonoDroid( 8488): 	at dalvik.system.NativeStart.main(Native Method)
D/PROPERTY(  152): get media.dump_output.befconv: 0
D/PROPERTY(  152): get media.dump_output.aftconv: 0

**Comment by rmarinho** [comment]
Hi, thanks for taking the time to submit the bug. IS hard from the stack trace to figure the issue. We know is related with ScrollViewRenderer but without having a small repo to look is really hard to pinpoint and fix the issue. 

Can you please try to provide a repro. 

Thanks

**Comment by OmegaPrimeZ3** [comment]
Example project attached
[ExampleCrash-master.zip](https://github.com/xamarin/Xamarin.Forms/files/2629893/ExampleCrash-master.zip)

**Comment by samhouts** [comment]
@OmegaPrimeZ3 Does the attached reproduction crash for you? It doesn't crash on my 4.4 emulator.

**Comment by OmegaPrimeZ3** [comment]
Yes, this crashes on multiple 4.2 and 4.4 devices

**Comment by kingces95** [comment]
Hm. I haven't got a 4.4 device and this works on the emulator.

**Comment by samhouts** [comment]
We'll see if we can track down a device to test this one, @OmegaPrimeZ3 . In the meantime, can you provide more information about the devices that you used? Thanks!

**Comment by jeremymarabel** [comment]
Hi, i ran into the same issue recently and found this thread. The crash has occurred on a Galaxy Tab3 10.1 (GT-P5220) running Android 4.4.2
@OmegaPrimeZ3 were you able to fix this ?
