### ISSUE TITLE
Xamarin vs 2015 

### ISSUE THREAD

**Issue by InadullaevMakhmudjon** [xamarin/Xamarin.Forms#4887]
# [The feature] 

Provide a concise description of the feature and the motivation for adding it to Xamarin.Forms

# API

### Properties

| API | Description |
| ------------- | ------------- |
| [name] | Gets or sets [description]. |

### Events

| API | Description |
| ------------- | ------------- |
| [name] | [API documentation/description] |
 
# Scenarios

# Backward Compatibility

# Difficulty : [low/medium/high]

**Comment by InadullaevMakhmudjon** [comment]
Xamarin vs 2015 gives me an error. How can I fix this
java.lang.NoClassDefFoundError: com/android/utils/ILogger
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.android.utils.ILogger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
Exception in thread "main"

**Comment by PureWeen** [comment]
@InadullaevMakhmudjon can you give more steps please or attach your project that you are getting the exception with? Your exception looks like it has to do with the Linker or possibly with Proguard. 

Have you tried VS 2017?

**Comment by charlesroddie** [comment]
Should close as VS2015 is obsolete.

**Comment by samhouts** [comment]
@InadullaevMakhmudjon Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
