### ISSUE TITLE
[WPF] Grouped ListView throws Index Out of Range exception when clicking outside of list

### ISSUE THREAD

**Issue by KasperinK** [xamarin/Xamarin.Forms#4890]
### Description
When clicking in a grouped listview but not on an actual item an exception is thrown that crashes the app.

### Steps to Reproduce
1. Create a Grouped ListView
2. Click on the blank area where there is no item

### Expected Behavior
Nothing

### Actual Behavior
Index Out of Range Exception is thrown and the app crashes.

### Basic Information
Click somewhere around the highlighted area, exception will be thrown and the app will crash.
![image](https://user-images.githubusercontent.com/39413152/50647961-93e31580-0f3f-11e9-88e7-c7f683fe37ab.png)

- Version with issue: 3.4.0.1008975
- Last known good version: 3.0.1.637273
- IDE: VS2017 15.9.3
- Platform Target Frameworks: 
  - WPF 
- Nuget Packages:
  - Xamarin.Forms
  - Xamarin.Forms.Platform.WPF

### Reproduction Link
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2724515/ListViewBug.zip)

**Comment by KasperinK** [comment]
Last Chance Exception Handling is throwing this message in our actual program (in case it helps):

An application error occurred.


Outer Message: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index
Outer Source: mscorlib
Outer Trace:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)

   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)

   at Xamarin.Forms.Platform.WPF.ListViewRenderer.OnNativeMouseUp(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner Message: Unknown

**Comment by GurramVenkataDeepakkumar** [comment]
Hi, I am also facing the same issue regarding grouped listview. do you find any solution to fix these issue? If it is fixed, Can you please suggest how to fix this crashed issue.

**Comment by KasperinK** [comment]
You could roll back to version 3.1.0.637273 but there is an issue with message boxes not wrapping text in that one so you would have to make your own dialogs. The only solution to get around it is to make a renderer and display the pages with a grouped listview as pure WPF and use their grouped ListBox instead. You have to do the same with any page that uses a time picker as well since WPF does not have a timepicker outside of the WPFToolkit. Sadly we abandoned Xamarin and just rewrote everything in pure WPF b/c there were just too many hurdles we were constantly wasting time on. In the end we spent more time fighting issues than it would take us to just rewrite everything for each platform.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
