### ISSUE TITLE
Android: ListView.ItemTapped always passes the first item when Combined with ViewCell.ContextActions

### ISSUE THREAD

**Issue by JeroMiya** [xamarin/Xamarin.Forms#5016]
[Edit: It turns out ContextActions doesn't appear to have any effect. ListView.ItemTapped appears to be broken regardless. Also other oddities are happening, see below for screenshot]

### Description
`ListView.ItemTapped` event is firing but I'm always getting passed the first item in `ItemsSource`. 

### Steps to Reproduce

1. ListView like this:
```
                            <ListView ItemsSource="{Binding Items}"
                                      ItemTapped="ListView_ItemTapped">
                                <ListView.ItemTemplate>
                                    <DataTemplate>
                                        <ViewCell>
                                            <!-- Etc.. -->
                                        </ViewCell>
                                  </DataTemplate>
                              </ListView.ItemTemplate>
                          </ListView>
```

### Expected Behavior
`ListView_ItemTapped` will get called when an item is tapped, and the `Item` passed via the event arguments will be the item that was tapped.

### Actual Behavior
`ListView_ItemTapped` is triggered, but the `Item` passed via the event arguments is always the first item in the `ItemsSource` collection.

Edit: Also, some weird things happening in the debugger. When I set e.Item as a watch, I get the item that was tapped. When I try to cast e.Item as the type of the item into a local variable, I get the first item in the `ItemsSource`. BUT, the original e.Item is still the correct one that was tapped:

![image](https://user-images.githubusercontent.com/320332/51397342-02fb6500-1b0f-11e9-9210-c736c37c4af4.png)

And this error occurs whenever I evaluate e.Item as a watch in the debugger:

```
System.ArgumentException: The field '<Item>k__BackingField' is not valid for this type.
   at Mono.Debugger.Soft.ObjectMirror.GetValues(IList`1 fields) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\ObjectMirror.cs:line 93
   at Mono.Debugger.Soft.ObjectMirror.GetValue(FieldInfoMirror field) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\ObjectMirror.cs:line 74
   at Mono.Debugging.Soft.FieldValueReference.get_Value() in E:\A\_work\785\s\external\debugger-libs\Mono.Debugging.Soft\FieldValueReference.cs:line 129
   at Mono.Debugging.Evaluation.ValueReference.GetChild(String name, EvaluationOptions options) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ValueReference.cs:line 274
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1042
   at ICSharpCode.NRefactory.CSharp.MemberReferenceExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in E:\A\_work\785\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\MemberReferenceExpression.cs:line 105
   at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 82
   at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in E:\A\_work\785\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1411
```

### Basic Information

- Version with issue: 3.4.1009999
- Last known good version: Unknown
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: Min 21, Target 28
- Android Support Library Version: v28.0.0

- Nuget Packages: Xamarin.Forms, Xamarin.Android.Support.Design, Newtonsoft.Json, Autofac, SkiaSharp, Tleerik.UI.for.Xamarin.

- Affected Devices: Emulator (Android 5.1 to Android 9.0), Pixel XL, possibly more

### Workaround
`ListView.ItemTapped` is exhibiting this behavior, but `ListView.ItemSelected` appears to be working correctly. I can work around this issue by using the `ItemSelected` event instead of `ItemTapped`, and then interpreting an item selection as if the user tapped the item, triggering for example a navigation, etc...

**Comment by rmarinho** [comment]
Hi @JeroMiya we tried to reproduce this but it wasn't possible, can you please try to reproduce this in a file new project and upload that sample project?!

Thanks

**Comment by samhouts** [comment]
@JeroMiya Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
