### ISSUE TITLE
[XVS] Build fails with master detail page

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#6104]
### Description

<div><b style="">Affected Build:</b><span style="">&nbsp;<span style="color:rgb(106, 106, 106);font-family:&quot;Segoe UI&quot;;font-size:13px;font-weight:normal;background-color:rgb(255, 255, 255);display:inline !important;">16.1.0 Preview 2.0 [28815.163.d16.1]</span></span><br></div><br><b>Steps to reproduce:</b><br><div><ol><li style="font-size:10.5pt;color:rgba(0, 0, 0, 0.9);">Create Xamarin.Form Blank App</li><li style="font-size:10.5pt;color:rgba(0, 0, 0, 0.9);">Build Solution</li><li style="font-size:10.5pt;color:rgba(0, 0, 0, 0.9);">Add new &quot;Master Detail Page&quot; to common project</li><li style="font-size:10.5pt;color:rgba(0, 0, 0, 0.9);">Build Solution</li></ol><div><font face="segoe ui vss (regular), segoe ui, -apple-system, blinkmacsystemfont, roboto, helvetica neue, helvetica, ubuntu, arial, sans-serif, apple color emoji, segoe ui emoji, segoe ui symbol"><b>Expected result: </b>Build successful</font></div><div><font face="segoe ui vss (regular), segoe ui, -apple-system, blinkmacsystemfont, roboto, helvetica neue, helvetica, ubuntu, arial, sans-serif, apple color emoji, segoe ui emoji, segoe ui symbol"><br></font></div><div><font face="segoe ui vss (regular), segoe ui, -apple-system, blinkmacsystemfont, roboto, helvetica neue, helvetica, ubuntu, arial, sans-serif, apple color emoji, segoe ui emoji, segoe ui symbol"><b>Actual result: </b>Build failed for missing references.</font></div></div>

### Source

[849975](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849975)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/57956052-5e5a1b80-7893-11e9-882c-5da3d7cfa878.png)

```
1>------ Build started: Project: App89, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.700-preview-009618\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
1>obj\Debug\netstandard2.0\MasterDetailPage1.xaml.g.cs(20,31,20,54): error CS0234: The type or namespace name 'MasterDetailPage1Master' does not exist in the namespace 'App89' (are you missing an assembly reference?)
1>MasterDetailPage1Master.xaml.cs(30,41,30,72): error CS0246: The type or namespace name 'MasterDetailPage1MasterMenuItem' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "App89.csproj" -- FAILED.
2>------ Build started: Project: App89.Android, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\Users\Chris\source\repos\App89\App89\bin\Debug\netstandard2.0\App89.dll'.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018: File name: 'C:\Users\Chris\source\repos\App89\App89\bin\Debug\netstandard2.0\App89.dll'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Xamarin.Android.Tools.Files.HashFile(String filename, HashAlgorithm hashAlg)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Xamarin.Android.Tools.Files.HashFile(String filename)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1369,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'App89.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018: File name: 'App89.Android.dll'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2192,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```
