### ISSUE TITLE
[BUG] MSB4018	The "XamlCTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#6171]
Get the following of recompilation of a project latest visual studio 
Xamrin 3.6.0.2

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "XamlCTask" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xamarin.Forms.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader)
   at Xamarin.Forms.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested)
   at Xamarin.Forms.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader)
   at Xamarin.Forms.Xaml.XamlParser.ParseXaml(RootNode rootNode, XmlReader reader)
   at Xamarin.Forms.Build.Tasks.XamlTask.ParseXaml(Stream stream, TypeReference typeReference)
   at Xamarin.Forms.Build.Tasks.XamlCTask.Execute(IList`1& thrownExceptions)
   at Xamarin.Forms.Build.Tasks.XamlTask.Execute()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FuelStockApp	C:\ProgramData\Xamarin\NuGet\xamarin.forms\3.6.0.264807\build\Xamarin.Forms.targets	107

**Comment by davidbuckleyni** [comment]
<Target Name="XamlC" AfterTargets="AfterCompile" Inputs="$(IntermediateOutputPath)$(TargetFileName)" Outputs="$(IntermediateOutputPath)XamlC.stamp" Condition=" '$(DesignTimeBuild)' != 'True' ">
		<XamlCTask
			Assembly = "$(IntermediateOutputPath)$(TargetFileName)"
			ReferencePath = "@(ReferencePath)"
			OptimizeIL = "true"
			DebugSymbols = "$(DebugSymbols)"
			DebugType = "$(DebugType)"
			KeepXamlResources = "$(XFKeepXamlResources)" />
		<Touch Files="$(IntermediateOutputPath)XamlC.stamp" AlwaysCreate="True" />
		<ItemGroup>
			<FileWrites Include="$(IntermediateOutputPath)XamlC.stamp" />
		</ItemGroup>
	</Target>

**Comment by samhouts** [comment]
@davidbuckleyni Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@davidbuckleyni  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
