### ISSUE TITLE
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.SearchBarRenderer from native handle 0x7fe862fc54 (key_handle 0xb1c5ad6).

### ISSUE THREAD

**Issue by Awinesh** [xamarin/Xamarin.Forms#6550]
There is Xamarin form using searchbar control  at title view of navigation page. It throws exception on rotation of android device when control is active i.e control has focus and opened keyword to enter text. 

### Steps to Reproduce

1. Create a project with xamarin form 4. Override titleview of navigation page form content page and use a searchbar in it.
2. Run application in android. 
3. Select searchbar to enter text.
4. Rotate device to landscape mode. It will throw this error. 
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.SearchBarRenderer from native handle 0x7fe862fc54 (key_handle 0xb1c5ad6).

- IDE: Visual studio 2017 professional
Xamarin form 4.1.0.496342-pre2
Android device: Samsung SM-M305F
Android version: 8.1.0

**Comment by kvpt** [comment]
This error is related to a problem in the dispose.
I'm trying to fix most of them but I haven't encounter this one yet.
Can you provide a sample which reproduce the issue please.

**Comment by rmarinho** [comment]
I added a branch with reproduction, seems that when the toolbar is being reset, and when removing the nativeview, this normally is because it was disposed before. Doesn''t happen with a Entry for example.

**Comment by kvpt** [comment]
@rmarinho Thanks for the repro. 
Do you reproduce the issue yourself ? 
I tested it but I don't reproduce it. 
I focus the SearchBar and rotate the device (emulator), nothing happen.
I went back to the home page and retried several times with no success.

What is strange with this case is that dispose is normaly triggered after the page has been popped and not rotated, unless the activity is configured to not handle the orientation change.

**Comment by kvpt** [comment]
I already made some changes in the NavigationPageRenderer dispose method.
But others methods change :
- ResetToolbar : The title view renderer is disposed before the view is removed (was also the case for dispose)
- UpdateTitleView : On some case it is possible that the renderer is disposed but the view not removed, need to change that too

**Comment by kvpt** [comment]
I succeed to reproduce it.

Here the complete stacktrace.
```cs
0x3B in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.ResetToolbar at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:718,4
0x27 in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.DeviceInfoPropertyChanged at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:542,5
0x33 in System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.<DeviceInfoPropertyChanged>d__72>
0x38 in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.DeviceInfoPropertyChanged
0x13 in Xamarin.Forms.Internals.DeviceInfo.OnPropertyChanged at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Core\DeviceInfo.cs:49,7
0x2A in Xamarin.Forms.Internals.DeviceInfo.set_CurrentOrientation at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Core\DeviceInfo.cs:21,5
0x37 in Xamarin.Forms.Forms.AndroidDeviceInfo.CheckOrientationChanged at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\Forms.cs:377,6
0x8 in Xamarin.Forms.Forms.AndroidDeviceInfo.ConfigurationChanged at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\Forms.cs:386,5
0x1B in Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnConfigurationChanged at D:\Workspace\Xamarin\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:66,4
```

Has expected, it is the `ResetToolbar` method which is trigerred by the rotation change.

**Comment by kvpt** [comment]
I can confirm that the latest fix included in #6467 fix the issue.
The root cause here, is that the renderer is disposed before the view is removed.

@samhouts Do you want a separate PR for this one too ?

I also have a question on the UpdateTitleView method ?

```cs
void UpdateTitleView()

...

if (_titleViewRenderer != null)
{
  var reflectableType = _titleViewRenderer as System.Reflection.IReflectableType;
  var rendererType = reflectableType != null ? reflectableType.GetTypeInfo().AsType() : _titleViewRenderer.GetType();
  if (titleView == null || Registrar.Registered.GetHandlerTypeForObject(titleView) != rendererType)
  {
    if (_titleView != null)
      _titleView.Child = null;
    Android.Platform.ClearRenderer(_titleViewRenderer.View);
    _titleViewRenderer.Dispose();
    _titleViewRenderer = null;
  }
}

...
```

I think that this bloc can cause issue too.
Because it dispose the old renderer before recreate it later, and never detach the view.
So it is possible for me that for an interval of time the titleview have no renderer and can cause crash.
I don't understand why it is done like that (with the registrar check), so I not modified it.

**Comment by kvpt** [comment]
@Awinesh As #6467 is now included in 4.2 branch, can you test if the latest 4.2 version fix your issue ?

**Comment by jfversluis** [comment]
@Awinesh I'm going to assume that @kvpt's PR fixed this. If not, feel free to reopen this.

Thank you!

**Comment by Srikanth540-L** [comment]
@samhouts we are facing random crash similar to above mentioned crash 
Xamarin forms version: 4.5
Stack Trace:
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FormsEditText from native handle 0x75 (key_handle 0x9d1c1f0).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <fe77140e95ab425f80b96ad501721d46>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <fe77140e95ab425f80b96ad501721d46>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <fe77140e95ab425f80b96ad501721d46>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <fe77140e95ab425f80b96ad501721d46>:0
  at Android.App.Activity.get_CurrentFocus () [0x0001f] in <fe77140e95ab425f80b96ad501721d46>:0
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnResume () [0x0001e] in <039dc6f9f40c4a668399f93931013d38>:0
  at MEC_Mobile.Droid.MainActivity.OnResume () [0x00000] in <e8ba780eaa5f4da988f5d0db2e91a4c3>:0
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <fe77140e95ab425f80b96ad501721d46>:0
  at (wrapper dynamic-method) System.Object.12(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.FormsEditText::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <fe77140e95ab425f80b96ad501721d46>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <fe77140e95ab425f80b96ad501721d46>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md51d7c7f7526562c6ae09f0b54043c9be9.MainActivity.n_onResume(Native Method)
      at md51d7c7f7526562c6ae09f0b54043c9be9.MainActivity.onResume(MainActivity.java:76)
      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
      at android.app.Activity.performResume(Activity.java:8116)
      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4526)
      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4572)
      at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
      at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
      at android.os.Handler.dispatchMessage(Handler.java:107)
      at android.os.Looper.loop(Looper.java:227)
      at android.app.ActivityThread.main(ActivityThread.java:7805)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Comment by samhouts** [comment]
@Srikanth540-L Do you have a reproduction project you can share? Thanks!

**Comment by EDMIStephen** [comment]
I am getting a very similar issue to @Srikanth540-L . Raised a bug https://github.com/xamarin/Xamarin.Forms/issues/11098

**Comment by EmilAlipiev** [comment]
@Srikanth540-L did you find any solution for that? i have exactly same exception?
