### ISSUE TITLE
[Bug] Obfuscation with progaurd on

### ISSUE THREAD

**Issue by AlenToma** [xamarin/Xamarin.Forms#7064]
### Description
Im not sure if i should post this as a bugg here or somewhere else, please advaice if i im wrong on posting it here.
Im using the latest `Skater .NET Obfuscator` to protect my dll. and its working just fine exept when i use it togather with `progard` and `sdk only` options.

Im getting this exception when i build my doid project

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Youtube.Manager.MainPage::DataBinder(Youtube.Manager.Models.Container.MethodInformation)' in assembly: 'Youtube.Manager.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Youtube.Manager.MainPage/<DataBinder>d__1
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkWithResolvedScope(TypeReference type)
   at Mono.Linker.Steps.MarkStep.MarkIfType(CustomAttributeArgument argument)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributeArguments(CustomAttribute ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Youtube.Manager.Droid	
```	

if you see the location im getting this error for is `Youtube.Manager.Models.Container.HttpHelper`

All the generic method cause problems somhow and i doint know why.

The class look loke this before `Obfuscation `
```
    public static class HttpHelper
    {
        private static readonly HttpClient client;

        public static string BaseUrl = "http://youtubemanager.ddns.net/xxx";
        static HttpHelper()
        {
            try
            {
                ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) =>
                {
                    //Debug.WriteLine(cert.GetSerialNumberString());
                    //Debug.WriteLine(cert.Issuer);
                    //Debug.WriteLine(cert.Subject);
                    return true;
                };
                var clientcert = new HttpClientHandler
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual
                };
                client = new HttpClient(clientcert);

                //client.BaseAddress = new Uri(Methods.BaseUrl);
            }
            catch (Exception e)
            {
                // 
            }
        }
        private static readonly SafeValueType<string, MethodInformation> cachedMethodInformation = new SafeValueType<string, MethodInformation>();
        public static MethodInformation GetInfo<T, P>(this Expression<Func<T, P>> expression, bool skipArgs = false)
        {


            MethodCallExpression callExpression = expression.Body as MethodCallExpression;
            var method = callExpression.Method;
            var argument = callExpression.Arguments;
            var key = typeof(T).ToString() + typeof(P).ToString() + method.Name + method.ReflectedType.FullName;
            var cached = cachedMethodInformation.ContainsKey(key);
            var item = cachedMethodInformation.GetOrAdd(key, new MethodInformation());
            if (!cached)
            {
                item.IsVoid = method.ReturnType == typeof(void) || method.ReturnType == typeof(Task);
                if (method.ReturnType.IsGenericType && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>))
                    item.CleanReturnType = method.ReturnType.GetActualType();
                else item.CleanReturnType = method.ReturnType;
            }
            var index = 0;
            item.Arguments.Clear();
            if (!skipArgs)
                foreach (var pr in method.GetParameters())
                {
                    var arg = argument[index];
                    var value = arg is ConstantExpression constExp ? constExp.Value : Expression.Lambda(arg).Compile().DynamicInvoke();
                    item.Arguments.Add(pr.Name, value);
                    index++;
                }

            if (!cached)
            {
                var mRoute = method.GetCustomAttribute<Route>();
                var classRoute = typeof(T).GetCustomAttribute<Route>()?.Url ?? "";
                var controller = typeof(T).Name.Substring(1).Replace("Controller", "");
                item.FullUrl = Path.Combine(BaseUrl, classRoute, controller, (mRoute != null && !string.IsNullOrEmpty(mRoute.Url) ? mRoute.Url : method.Name)).Replace("\\", "/");
                item.HttpMethod = mRoute?.HttpMethod ?? HttpMethod.GET;
            }
            return item;

        }


        public static async Task<P> ExecuteAsync<T, P>(Expression<Func<T, P>> expression)
        {
            object result = null;
            try
            {
                MethodInformation item = expression.GetInfo();
                switch (item?.HttpMethod ?? HttpMethod.GET)
                {
                    case HttpMethod.GET:
                        result = await GetAsync(item.FullUrl, item.Arguments, item.IsVoid ? null : item.CleanReturnType);
                        break;

                    case HttpMethod.POST:
                        result = await PostAsync(item.FullUrl, item.Arguments, item.IsVoid ? null : item.CleanReturnType);
                        break;

                    case HttpMethod.JSONPOST:
                        result = await PostAsJsonAsync(item.FullUrl, item.Arguments, item.IsVoid ? null : item.CleanReturnType);
                        break;
                }

                if (typeof(P).IsGenericType && typeof(P).GetGenericTypeDefinition() == typeof(Task<>))
                    result = new DynamicTaskCompletionSource(result, item.CleanReturnType).Task;
                else if (item.IsVoid) result = Task.CompletedTask;


                return (P)result;

            }
            catch (Exception e)
            {
                throw e;
            }
        }


        public static async Task<T> PostAsJsonAsync<T>(this string url, object parameter)
        {
            return (T)await (PostAsJsonAsync(url, parameter, typeof(T)));
        }

        public static async Task<T> GetTAsync<T>(this string url, object parameter = null)
        {
            return (T)await (GetAsync(url, parameter, typeof(T)));
        }

        public static async Task<T> PostAsync<T>(this string url, object parameter)
        {
            return (T)await (PostAsync(url, parameter, typeof(T)));
        }


        public static async Task<object> PostAsync(this string url, object parameter, Type castToType = null)
        {
            if (parameter == null)
                throw new Exception("POST operation need a parameters");
            var values = new Dictionary<string, string>();
            if (parameter is Dictionary<string, object>)
                values = (parameter as Dictionary<string, object>).ToDictionary(x => x.Key, x => x.Value?.ToString());
            else
            {
                values = parameter.GetType().GetProperties().ToDictionary(x => x.Name, x => x.GetValue(parameter)?.ToString());
            }

            var content = new FormUrlEncodedContent(values);
            var response = await client.PostAsync(url, content);
            var contents = await response.Content.ReadAsStringAsync();
            if (castToType != null && !string.IsNullOrEmpty(contents))
                return JsonConvert.DeserializeObject(contents, castToType);
            return null;
        }

        /// <summary>
        /// Post as json.
        /// </summary>
        /// <param name="url"></param>
        /// <param name="parameter"></param>
        /// <param name="castToType"></param>
        /// <returns></returns>
        public static async Task<object> PostAsJsonAsync(this string url, object parameter, Type castToType = null)
        {
            if (parameter == null)
                throw new Exception("POST operation need a parameters");
            var item = parameter is IDictionary<string, object> ? ((IDictionary<string, object>)parameter).Values.FirstOrDefault() : parameter;
            HttpContent contentPost = new StringContent(JsonConvert.SerializeObject(item), Encoding.UTF8, "application/json");


            var response = await client.PostAsync(new Uri(url), contentPost);
            var contents = await response.Content.ReadAsStringAsync();
            if (castToType != null && !string.IsNullOrEmpty(contents))
                return JsonConvert.DeserializeObject(contents, castToType);
            return null;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="url"></param>
        /// <param name="parameters"></param>
        /// <param name="castToType">The return json should be converted to </param>
        /// <returns></returns>
        public static async Task<object> GetAsync(this string url, object parameter = null, Type castToType = null)
        {
            if (parameter is IDictionary)
            {
                if (parameter != null)
                {
                    url += "?" + string.Join("&", (parameter as Dictionary<string, object>).Select(x => $"{x.Key}={x.Value ?? ""}"));
                }
            }
            else
            {
                var props = parameter?.GetType().GetProperties();
                if (props != null)
                    url += "?" + string.Join("&", props.Select(x => $"{x.Name}={x.GetValue(parameter)}"));
            }

            var responseString = await client.GetStringAsync(new Uri(url));
            if (castToType != null)
            {
                if (!string.IsNullOrEmpty(responseString))
                    return JsonConvert.DeserializeObject(responseString, castToType);
            }

            return null;
        }

        public static byte[] GetImage(string filename)
        {

            using (var webClient = new WebClient())
            {
                using (var stream = new MemoryStream())
                {
                    webClient.OpenRead(filename).CopyTo(stream);
                    return stream.ToArray();
                }
            }
        }

        public static string UrlDecode(string url)
        {
            return WebUtility.UrlDecode(url);
        }
    }

```
And like this after `Obfuscation `
```
    public static class HttpHelper
    {
        private readonly static HttpClient 60AAA;

        public static string BaseUrl;

        private readonly static SafeValueType<string, MethodInformation> 70AA1;

        static HttpHelper()
        {
            HttpHelper.BaseUrl = "http://youtubemanager.ddns.net/xxx";
            HttpHelper.70AA1 = new SafeValueType<string, MethodInformation>(null);
            try
            {
                ServicePointManager.ServerCertificateValidationCallback = (RemoteCertificateValidationCallback)Delegate.Combine(ServicePointManager.ServerCertificateValidationCallback, new RemoteCertificateValidationCallback((object sender, X509Certificate cert, X509Chain chain, SslPolicyErrors sslPolicyErrors) => true));
                HttpHelper.60AAA = new HttpClient(new HttpClientHandler()
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual
                });
            }
            catch (Exception exception)
            {
            }
        }

        public static async Task<P> ExecuteAsync<T, P>(Expression<Func<T, P>> expression)
        {
            HttpHelper.<ExecuteAsync>d__5<T, P> variable = new HttpHelper.<ExecuteAsync>d__5<T, P>();
            variable.expression = expression;
            variable.<>t__builder = AsyncTaskMethodBuilder<P>.Create();
            variable.<>1__state = -1;
            variable.<>t__builder.Start<HttpHelper.<ExecuteAsync>d__5<T, P>>(ref variable);
            return variable.<>t__builder.Task;
        }

        [AsyncStateMachine(typeof(
Current member / type: System.Threading.Tasks.Task`1<System.Object> Youtube.Manager.Models.Container.HttpHelper::GetAsync(System.String,System.Object,System.Type)
File path: E:\Projects\Youtube.Manager\Youtube.Manager.Models.Container\bin\Release\netstandard2.0\Youtube.Manager.Models.Container.dll

Product version: 2019.1.118.0
Exception in: System.Threading.Tasks.Task<System.Object> GetAsync(System.String,System.Object,System.Type)

Object reference not set to an instance of an object.
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(TypeReference ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 3220
at ..(CustomAttributeArgument ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 790
at ..(CustomAttribute , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 642
at ..(CustomAttribute , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 601
at ..(IMemberDefinition , List`1 , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 84
at ..(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 70
at Telerik.JustDecompiler.Languages.CSharp.CSharpAttributeWriter.(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\CSharp\CSharpAttributeWriter.cs:line 45
at ..(IMemberDefinition , IEnumerable`1 , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 40
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(IMemberDefinition , IEnumerable`1 ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 106
at ..WriteInternal(IMemberDefinition ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseLanguageWriter.cs:line 438

mailto: JustDecompilePublicFeedback@telerik.com


        public static byte[] GetImage(string filename)
        {
            byte[] array;
            using (WebClient webClient = new WebClient())
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    webClient.OpenRead(filename).CopyTo(memoryStream);
                    array = memoryStream.ToArray();
                }
            }
            return array;
        }

        public static MethodInformation GetInfo<T, P>(this Expression<Func<T, P>> expression, bool skipArgs = false)
        {
            object url;
            object obj;
            MethodCallExpression body = expression.Body as MethodCallExpression;
            MethodInfo method = body.Method;
            ReadOnlyCollection<Expression> arguments = body.Arguments;
            string str = string.Concat(typeof(T).ToString(), typeof(P).ToString(), method.Name, method.ReflectedType.FullName);
            bool flag = HttpHelper.70AA1.ContainsKey(str);
            MethodInformation orAdd = HttpHelper.70AA1.GetOrAdd(str, new MethodInformation(), false);
            if (!flag)
            {
                orAdd.IsVoid = (method.ReturnType == typeof(Void) ? true : method.ReturnType == typeof(Task));
                if (!method.ReturnType.IsGenericType || !(method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>)))
                {
                    orAdd.CleanReturnType = method.ReturnType;
                }
                else
                {
                    orAdd.CleanReturnType = method.ReturnType.GetActualType();
                }
            }
            int num = 0;
            orAdd.Arguments.Clear();
            if (!skipArgs)
            {
                ParameterInfo[] parameters = method.GetParameters();
                for (int i = 0; i < (int)parameters.Length; i++)
                {
                    ParameterInfo parameterInfo = parameters[i];
                    Expression item = arguments[num];
                    ConstantExpression constantExpression = item as ConstantExpression;
                    obj = (constantExpression != null ? constantExpression.Value : Expression.Lambda(item, Array.Empty<ParameterExpression>()).Compile().DynamicInvoke(Array.Empty<object>()));
                    orAdd.Arguments.Add(parameterInfo.Name, obj);
                    num++;
                }
            }
            if (!flag)
            {
                Route customAttribute = method.GetCustomAttribute<Route>();
                Route route = typeof(T).GetCustomAttribute<Route>();
                if (route != null)
                {
                    url = route.Url;
                }
                else
                {
                    url = null;
                }
                if (url == null)
                {
                    url = "";
                }
                string str1 = (string)url;
                string str2 = typeof(T).Name.Substring(1).Replace("Controller", "");
                orAdd.FullUrl = Path.Combine(HttpHelper.BaseUrl, str1, str2, (customAttribute == null || string.IsNullOrEmpty(customAttribute.Url) ? method.Name : customAttribute.Url)).Replace("\\", "/");
                orAdd.HttpMethod = (customAttribute != null ? customAttribute.HttpMethod : HttpMethod.GET);
            }
            return orAdd;
        }

        public static async Task<T> GetTAsync<T>(this string url, object parameter = null)
        {
            return (T)await HttpHelper.GetAsync(url, parameter, typeof(T));
        }

        public static async Task<T> PostAsJsonAsync<T>(string url, object parameter)
        {
            return (T)await HttpHelper.PostAsJsonAsync(url, parameter, typeof(T));
        }

        [AsyncStateMachine(typeof(
Current member / type: System.Threading.Tasks.Task`1<System.Object> Youtube.Manager.Models.Container.HttpHelper::PostAsJsonAsync(System.String,System.Object,System.Type)
File path: E:\Projects\Youtube.Manager\Youtube.Manager.Models.Container\bin\Release\netstandard2.0\Youtube.Manager.Models.Container.dll

Product version: 2019.1.118.0
Exception in: System.Threading.Tasks.Task<System.Object> PostAsJsonAsync(System.String,System.Object,System.Type)

Object reference not set to an instance of an object.
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(TypeReference ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 3220
at ..(CustomAttributeArgument ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 790
at ..(CustomAttribute , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 642
at ..(CustomAttribute , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 601
at ..(IMemberDefinition , List`1 , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 84
at ..(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 70
at Telerik.JustDecompiler.Languages.CSharp.CSharpAttributeWriter.(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\CSharp\CSharpAttributeWriter.cs:line 45
at ..(IMemberDefinition , IEnumerable`1 , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 40
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(IMemberDefinition , IEnumerable`1 ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 106
at ..WriteInternal(IMemberDefinition ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseLanguageWriter.cs:line 438

mailto: JustDecompilePublicFeedback@telerik.com


        public static async Task<T> PostAsync<T>(this string url, object parameter)
        {
            return (T)await HttpHelper.PostAsync(url, parameter, typeof(T));
        }

        [AsyncStateMachine(typeof(
Current member / type: System.Threading.Tasks.Task`1<System.Object> Youtube.Manager.Models.Container.HttpHelper::PostAsync(System.String,System.Object,System.Type)
File path: E:\Projects\Youtube.Manager\Youtube.Manager.Models.Container\bin\Release\netstandard2.0\Youtube.Manager.Models.Container.dll

Product version: 2019.1.118.0
Exception in: System.Threading.Tasks.Task<System.Object> PostAsync(System.String,System.Object,System.Type)

Object reference not set to an instance of an object.
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(TypeReference ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 3220
at ..(CustomAttributeArgument ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 790
at ..(CustomAttribute , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 642
at ..(CustomAttribute , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 601
at ..(IMemberDefinition , List`1 , Boolean , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 84
at ..(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 70
at Telerik.JustDecompiler.Languages.CSharp.CSharpAttributeWriter.(IMemberDefinition , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\CSharp\CSharpAttributeWriter.cs:line 45
at ..(IMemberDefinition , IEnumerable`1 , Boolean ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\AttributeWriter.cs:line 40
at Telerik.JustDecompiler.Languages.BaseImperativeLanguageWriter.(IMemberDefinition , IEnumerable`1 ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseImperativeLanguageWriter.cs:line 106
at ..WriteInternal(IMemberDefinition ) in C:\DeveloperTooling_JD_Agent1\_work\15\s\OpenSource\Cecil.Decompiler\Languages\BaseLanguageWriter.cs:line 438

mailto: JustDecompilePublicFeedback@telerik.com


        public static string UrlDecode(string url)
        {
            return WebUtility.UrlDecode(url);
        }
    }
}
```

### Steps to Reproduce

1. Obfuscation  your project using Skater .NET Obfuscator and use generic methods. 
2. Add reference to your project to the droid project
3. And simple build

### Expected Behavior
The project should build normally without having a problem. 
### Actual Behavior
Getting the exception above
### Basic Information

- Version with issue:`4.1.0.618606`
- Last known good version: dont know did, it never worked
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:`4.1.0.618606`

**Comment by StephaneDelcroix** [comment]
you should try to file against Xamarin.Android, the mono linker, or your obfuscator. the issue could be in any of those 3 parts, but it's very unlikely in XF
