### ISSUE TITLE
[Bug] Linking error regarding TextView Autosizing

### ISSUE THREAD

**Issue by gkonterman** [xamarin/Xamarin.Forms#7241]
### Description
I try to create a release build of my Xamarin Forms app but I get an linking error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Android.Widget.AutoSizeTextType Android.Support.V4.Widget.IAutoSizeableTextViewInvoker::get_AutoSizeTextType()' in assembly: 'Xamarin.Android.Support.Compat.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Widget.AutoSizeTextType
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	LogicTrade.StoreAssist.Consumer.Android.App			
```

Google learns me that this feature is enabled in v26 (I am forced to use v25).
https://forums.xamarin.com/discussion/137833/how-to-use-textview-setautosizetexttypewithdefaults-autosizetexttype-uniform

How to fix this, or what kind of workaround?

According to me, I am not using this feature at all.

### Expected Behavior
A valid build and .apk

### Actual Behavior
No valid build and no .apk

`Mono.Linker.MarkException: Error processing method: 'Android.Widget.AutoSizeTextType Android.Support.V4.Widget.IAutoSizeableTextViewInvoker::get_AutoSizeTextType()' in assembly: 'Xamarin.Android.Support.Compat.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Widget.AutoSizeTextType`

### Basic Information

- Version with issue: 4.2.0.709249
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 9.0 (v28)

### Screenshots

![image](https://user-images.githubusercontent.com/7427231/63504698-6220be00-c4d2-11e9-9ee9-4196cd466e71.png)

**Comment by gkonterman** [comment]
One workaround is to completely turn off the Linker, but that's not a sustainable solution

**Comment by jfversluis** [comment]
Maybe I'm not understanding correctly but you say

> Google learns me that this feature is enabled in v26 (I am forced to use v25).

Then you won't be able to use this at all, right?

A few lines later you say you're not using this feature. Did you write your own code to fit the text in the label then? Could you share the relevant code?

What probably happens (in release mode) is that there is no direct reference to whatever code you are trying to use and so the linker decides to strip the assembly while you are in fact using the code but there is no direct link to it. That is basically why a lot of the external libraries have the `Init();` calls to prevent that kind of behavior. 

It's probably a bit easier to explain with some code :) a reproduction would even be better.

**Comment by jfversluis** [comment]
@gkonterman we've chatted about this offline, I think this is resolved and closing this. If you think differently feel free to open it again.

For future readers: the "solution" was to thoroughly remove the obj/bin folders, restart VS, restart the computer while you're at it and it was working again. Error occurred after an upgrade from v3.1 to 4.2 so probably some mismatch between cached libraries and new libraries somewhere
