### ISSUE TITLE
MSB4018 The "XamlCTask" task failed unexpectedly -> When using icon Glyph="&#x001D;"

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7409]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/701461/msb4018-the-xamlctask-task-failed-unexpectedly-whe.html)._

---
VS2019 latest version crashes the XamlCTask when defining somewhere in a XAML file the following glyph icon within a Xamarin.Froms 4.1 App.xaml file: 

&lt;FontImageSource x:Key=&quot;icon&quot; Glyph=&quot;&amp;#x001D;&quot;/&gt;

When comment out the line the build works fine. 

Output:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The &quot;XamlCTask&quot; task failed unexpectedly.
System.Xml.XmlException: '&#29;', hexadecimal value 0x1D, is an invalid character. Line 366, position 53.

Server stack trace: 
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32&amp; charCount, EntityType&amp; entityType)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRef(Boolean expand, StringBuilder internalSubsetBuilder, EntityType&amp; entityType)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32&amp; charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Xamarin.Forms.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader)
   at Xamarin.Forms.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested)
   at Xamarin.Forms.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader)
   at Xamarin.Forms.Xaml.XamlParser.ParseXaml(RootNode rootNode, XmlReader reader)
   at Xamarin.Forms.Build.Tasks.XamlTask.ParseXaml(Stream stream, TypeReference typeReference)
   at Xamarin.Forms.Build.Tasks.XamlCTask.Execute(IList`1&amp; thrownExceptions)
   at Xamarin.Forms.Build.Tasks.XamlTask.Execute()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]&amp; outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&amp; msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. &lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()	MobileStyleguide	C:\Users\marspe00\.nuget\packages\xamarin.forms\4.1.0.673156\build\Xamarin.Forms.targets	107

---
#### Visual Studio Feedback System on 8/20/2019, 09:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Luca.Ziegler on 8/29/2019, 02:43 AM: 

Very annoying bug, a project clean generally solve this.

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
there's an excellent SO answer on this https://stackoverflow.com/a/28152666/1063783

&#x1D; is not valid in xml 1.0.

**Comment by StephaneDelcroix** [comment]
and the Xml reader we use doesn't support xml 1.1: https://developercommunity.visualstudio.com/content/problem/439314/xdocument-loadxml-fails-due-to-xml-version-number.html

there's nothing we can do here... closing
