### ISSUE TITLE
[ANDROID] Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

### ISSUE THREAD

**Issue by sinappsys** [xamarin/Xamarin.Forms#7567]
### Description
Appcenter reports many crashes on device: (HUAWEI P20 Lite, HUAWEI P20 Pro, Galaxy S7, Galaxy A5...):

### Xamarin Exception Stack:
Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer from native handle 0x79 (key_handle 0x88fb15d).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Android.Views.View.get_Parent () [0x0001f] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateParentPageTraversalOrder () [0x00009] in <b356e1b6c53b471db4568de2eac3880b>:0
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00116] in <b356e1b6c53b471db4568de2eac3880b>:0
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00012] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Element.set_Parent (Xamarin.Forms.Element value) [0x000e9] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Element.OnChildRemoved (Xamarin.Forms.Element child) [0x00000] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.VisualElement.OnChildRemoved (Xamarin.Forms.Element child) [0x00000] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Layout`1[T].OnChildRemoved (Xamarin.Forms.Element child) [0x00000] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Layout.OnInternalRemoved (Xamarin.Forms.View view) [0x00012] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0002b] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at (wrapper delegate-invoke) <Module>.invoke_void_object_NotifyCollectionChangedEventArgs(object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in <fa6f27e8a3414a1f8ef1920ac411c045>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00009] in <fa6f27e8a3414a1f8ef1920ac411c045>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].RemoveItem (System.Int32 index) [0x00021] in <fa6f27e8a3414a1f8ef1920ac411c045>:0
  at System.Collections.ObjectModel.Collection`1[T].Remove (T item) [0x00027] in <158a93d0ee4549e2b36d9f3105943896>:0
  at Xamarin.Forms.ObservableWrapper`2[TTrack,TRestrict].Clear () [0x00030] in <d3503cab547d4ef0b9ab4f454b2a1f78>:0
  at UXDivers.Artina.Grial.DashuserVIewModel.RefreshHeader (com.sinappsys.prizeme.manager.DashUserManagerData dataDash) [0x00395] in <bef85fea5f0f43b0a5e4e9d04d64789c>:0
  at UXDivers.Artina.Grial.DashuserVIewModel+<>c__DisplayClass17_0.<ExecuteRefreshWithoutLoaderCommand>b__0 () [0x00000] in <bef85fea5f0f43b0a5e4e9d04d64789c>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  at (wrapper dynamic-method) System.Object.38(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <cf405bdbc85b4c04aa3d5d64b02dbacc>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at mono.java.lang.RunnableImplementor.n_run(Native Method)
      at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
      at android.os.Handler.handleCallback(Handler.java:907)
      at android.os.Handler.dispatchMessage(Handler.java:105)
      at android.os.Looper.loop(Looper.java:216)
      at android.app.ActivityThread.main(ActivityThread.java:7625)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1558)
2   java.lang.Thread.getAllStackTraces(Thread.java:1608)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:970)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:55)
5   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
6   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
7   android.os.Handler.handleCallback(Handler.java:907)
8   android.os.Handler.dispatchMessage(Handler.java:105)
9   android.os.Looper.loop(Looper.java:216)
10  android.app.ActivityThread.main(ActivityThread.java:7625)
11  java.lang.reflect.Method.invoke(Method.java:-2)
12  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
13  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Thread 25234:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:784)

Thread 25235:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:784)

Thread 25236:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:297)
2   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:277)
3   java.lang.Daemons$Daemon.run(Daemons.java:103)
4   java.lang.Thread.run(Thread.java:784)

Thread 25255:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2163)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
8   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1172)
9   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
10  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11  java.lang.Thread.run(Thread.java:784)

Thread 25256:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2163)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
8   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1172)
9   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
10  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11  java.lang.Thread.run(Thread.java:784)

Thread 25257:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2163)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
8   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1172)
9   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
10  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11  java.lang.Thread.run(Thread.java:784)

Thread 25258:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2163)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
7   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1172)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10  java.lang.Thread.run(Thread.java:784)

Thread 25263:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101)
2   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
3   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
4   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
5   java.lang.Thread.run(Thread.java:784)

Thread 25268:
0   java.lang.Object.wait(Object.java:-2)
1   android.zrhung.appeye.AppEyeUiProbe$AppEyeUIPChecker.run(AppEyeUiProbe.java:141)
2   java.lang.Thread.run(Thread.java:784)

Thread 25270:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
2   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 25272:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2163)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
8   java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1172)
9   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
10  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11  java.lang.Thread.run(Thread.java:784)

Thread 25274:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:386)
2   android.os.Looper.loop(Looper.java:175)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 25279:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:386)
2   android.os.Looper.loop(Looper.java:175)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 25280:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:386)
2   android.os.Looper.loop(Looper.java:175)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 25283:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:386)
2   android.os.Looper.loop(Looper.java:175)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 25336:
0   com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-2)
1   com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
2   com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
3   com.android.okhttp.okio.Okio$2.read(Okio.java:136)
4   com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
5   com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
6   com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
7   com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
8   com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
9   com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
10  com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
11  com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
12  com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
13  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
14  com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
15  com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
16  com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)

### Basic Information

Xamarin.Forms: 4.2.0.709249
-Android SDK 28

DEVICE:
-Android: 9
-Android Build: HUAWEIANE-L21
-Manufacturer: HUAWEI
-Model: ANE-LX1

**Comment by jfversluis** [comment]
Hey there @sinappsys thanks for reporting!

I'm afraid this report is not really for us though, near the top I notice:

> Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer

Which indicates you are using this plugin: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout which is the source of this error. You might want to check if there is already an issue of it there or open one if there isn't.

Closing this for now, if you feel this is in error please let me know.
