### ISSUE TITLE
[Bug] [ANDROID] Error regarding LabelRenderer

### ISSUE THREAD

**Issue by Osmosis311** [xamarin/Xamarin.Forms#7663]
# Description

When running an Android XF project (4.2.0.815419), getting the following error:

`System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer from native handle 0xbfb4dfec (key_handle 0x39b827a). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
  at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
  at java.lang.Error: Java callstack:
  at at md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.n_invalidate(Native Method)
  at at md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.invalidate(FormsTextView.java:53)
  at at android.view.ViewRootImpl$InvalidateOnAnimationRunnable.run(ViewRootImpl.java:6868)
  at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
  at at android.view.Choreographer.doCallbacks(Choreographer.java:723)
  at at android.view.Choreographer.doFrame(Choreographer.java:655)
  at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
  at at android.os.Handler.handleCallback(Handler.java:790)
  at at android.os.Handler.dispatchMessage(Handler.java:99)
  at at android.os.Looper.loop(Looper.java:164)
  at at android.app.ActivityThread.main(ActivityThread.java:6494)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <266395aeef1642bab2007ca31686faf9>:0
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <266395aeef1642bab2007ca31686faf9>:0
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <266395aeef1642bab2007ca31686faf9>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <266395aeef1642bab2007ca31686faf9>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <266395aeef1642bab2007ca31686faf9>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <266395aeef1642bab2007ca31686faf9>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <266395aeef1642bab2007ca31686faf9>:0
  at Android.Views.View.n_Invalidate (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <266395aeef1642bab2007ca31686faf9>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)`

### Steps to Reproduce

1. Create an XF project
2. Add a label to MainPage that has the code listed below
3. Run the application

```xaml
<Label.FontSize>
                    <OnPlatform
                        x:TypeArguments="x:Double">
                        <OnPlatform.Platforms>
                            <On
                                Platform="iOS"
                                Value="16" />
                            <On
                                Platform="Android"
                                Value="14" />
                        </OnPlatform.Platforms>
                    </OnPlatform>
                </Label.FontSize>
                <Label.BackgroundColor>
                    <OnPlatform
                        x:TypeArguments="Color">
                        <OnPlatform.Platforms>
                            <On
                                Platform="iOS"
                                Value="DodgerBlue" />
                            <On
                                Platform="Android"
                                Value="Red" />
                        </OnPlatform.Platforms>
                    </OnPlatform>
                </Label.BackgroundColor>
```

### Expected Behavior

Application runs in simulator.

### Actual Behavior

Error occurs when form is rendered.

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version:
- IDE: Visual Studio Mac 8.3
- Platform Target Frameworks: 
  - Android: 28
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
this xaml snippet looks valid and shouldn't crash. please provide a repro project. Thanks

**Comment by samhouts** [comment]
@Osmosis311  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Srikanth540-L** [comment]
@samhouts  we are facing the same crash in most of our client apks , There is no proper approach to fix this crash since some are suggesting to added a constructor which is shown as missing constructor, I think adding missing constructor may solve the crash but may hide the underlying problem.
 Stack Trace:
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer from native handle 0x7fea86d254 (key_handle 0x3aab0b4).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <75a962323d624eafbc05f28f5ad47a61>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <75a962323d624eafbc05f28f5ad47a61>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <75a962323d624eafbc05f28f5ad47a61>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <75a962323d624eafbc05f28f5ad47a61>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <75a962323d624eafbc05f28f5ad47a61>:0
  at Android.Views.View.n_Invalidate (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <75a962323d624eafbc05f28f5ad47a61>:0
  at (wrapper dynamic-method) System.Object.41(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <75a962323d624eafbc05f28f5ad47a61>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <75a962323d624eafbc05f28f5ad47a61>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.n_invalidate(Native Method)
      at md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.invalidate(FormsTextView.java:45)
      at android.view.ViewRootImpl$InvalidateOnAnimationRunnable.run(ViewRootImpl.java:7538)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
      at android.view.Choreographer.doCallbacks(Choreographer.java:888)
      at android.view.Choreographer.doFrame(Choreographer.java:816)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
      at android.os.Handler.handleCallback(Handler.java:873)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:201)
      at android.app.ActivityThread.main(ActivityThread.java:6810)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1538)
2   java.lang.Thread.getAllStackTraces(Thread.java:1588)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:943)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)
5   md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.n_invalidate(FormsTextView.java:-2)
6   md51558244f76c53b6aeda52c8a337f2c37.FormsTextView.invalidate(FormsTextView.java:45)
7   android.view.ViewRootImpl$InvalidateOnAnimationRunnable.run(ViewRootImpl.java:7538)
8   android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
9   android.view.Choreographer.doCallbacks(Choreographer.java:888)
10  android.view.Choreographer.doFrame(Choreographer.java:816)
11  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
12  android.os.Handler.handleCallback(Handler.java:873)
13  android.os.Handler.dispatchMessage(Handler.java:99)
14  android.os.Looper.loop(Looper.java:201)
15  android.app.ActivityThread.main(ActivityThread.java:6810)
16  java.lang.reflect.Method.invoke(Method.java:-2)
17  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
18  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Thread 5550:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:180)
2   java.lang.Daemons$Daemon.run(Daemons.java:105)
3   java.lang.Thread.run(Thread.java:764)

Thread 5551:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:234)
5   java.lang.Daemons$Daemon.run(Daemons.java:105)
6   java.lang.Thread.run(Thread.java:764)

Thread 5552:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:299)
2   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:279)
3   java.lang.Daemons$Daemon.run(Daemons.java:105)
4   java.lang.Thread.run(Thread.java:764)

Thread 5571:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5573:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5574:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5593:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5595:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5598:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5599:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 5601:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2137)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
9   OE.run(SourceFile:5)
10  java.lang.Thread.run(Thread.java:764)

Thread 5602:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   azT.run(SourceFile:3)

Thread 5603:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2137)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
9   OE.run(SourceFile:5)
10  java.lang.Thread.run(Thread.java:764)

Thread 5611:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311)
2   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 5612:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:326)
2   android.os.Looper.loop(Looper.java:165)
3   android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by samhouts** [comment]
@Srikanth540-L What version of Xamarin.Forms are you using? Thanks!

**Comment by Srikanth540-L** [comment]
@samhouts   Xamarin forms version : 4.4 
Thanks!

**Comment by PureWeen** [comment]
@Srikanth540-L If you're seeing this exception on the latest 4.5 release then can you log an issue with a repro?

**Comment by matteopiccioni** [comment]
This issues happen to me too, it's rare but happens
 XF 4.5.0

**Comment by Srikanth540-L** [comment]
@matteopiccioni  Are you sure it happened on 4.5 , I have checked after updating from 4.4 to 4.5  but it didn't crash basically the crash occured when I change view around portrait to landscape and vice versa.

**Comment by matteopiccioni** [comment]
> @matteopiccioni Are you sure it happened on 4.5 , I have checked after updating from 4.4 to 4.5 but it didn't crash basically the crash occured when I change view around portrait to landscape and vice versa.

I had this crash with 4.5.. without change view from portrait to landscape
