### ISSUE TITLE
Can't compile on release mode

### ISSUE THREAD

**Issue by Mario-HL-Duarte** [xamarin/Xamarin.Forms#7731]
I'm not being able to compile my project on release mode anymore without "Use Shared Runtime" checked.

![image](https://user-images.githubusercontent.com/38980017/65823053-62288200-e225-11e9-990d-95f02d969e57.png)

> 2>  C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error : The method or operation is not implemented.

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, Stream symbolStream)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 117

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies) in D:\a\1\s\source\Xamarin.AndroidX.Migration\Migration\CecilMigrator.cs:line 50

> 2>C:\Users\mario\.nuget\packages\xamarin.androidx.migration\1.0.0-preview04\build\Xamarin.AndroidX.Migration.targets(212,9): error :    at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute() in D:\a\1\s\source\Xamarin.AndroidX.Migration\BuildTasks\CecilfyFiles.cs:line 35

If I check the option, I can compile, but not deploy to a device.

![image](https://user-images.githubusercontent.com/38980017/65823075-c0556500-e225-11e9-8b63-e893f193f059.png)

> ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by Mario-HL-Duarte** [comment]
The problem seems to be on **linker**

![image](https://user-images.githubusercontent.com/38980017/65823486-956f0f00-e22d-11e9-8cde-4d551b90bb25.png)

> ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by PureWeen** [comment]
@Mario-HL-Duarte can you attach a repro?


@mattleibow @Redth

**Comment by hudaIT** [comment]
Same problem for me too

**Comment by PureWeen** [comment]
@hudaIT do you have a repro you can attach?

**Comment by Redth** [comment]
Trying to reproduce here as well.

I'm using d8, r8, AndroidX nugets with the migration package, as well as AOT / LLVM and Link "Sdk Assemblies Only" here and it's working ok.

A repro would be helpful indeed, thanks!

**Comment by hudaIT** [comment]
> @hudaIT do you have a repro you can attach?

Can you please send me your email address to code@huda-it.at?
If it is welcomed i would send you send the link to a project via mail.

**Comment by Mario-HL-Duarte** [comment]
I am trying to recreate the problem in another application and attach it to you.
The problem was introduced in Visual Studio 16.4.0 Preview 1.
I installed the latest stable version of Visual Studio 2019 16.3.1 and was able to compile the application normally.

**Comment by hudaIT** [comment]
> I am trying to recreate the problem in another application and attach it to you.
> The problem was introduced in Visual Studio 16.4.0 Preview 1.
> I installed the latest stable version of Visual Studio 2019 16.3.1 and was able to compile the application normally.

Yeah i also think this is more an visual studio issue
