### ISSUE TITLE
[Bug] Target Parameter Count Exception when binding to string-indexed property.

### ISSUE THREAD

**Issue by davidpsaylor** [xamarin/Xamarin.Forms#7837]
### Description
We are porting a WPF app to Xamarin.Forms.  We have an object which can take a string index and return a sub-object.  We are able to bind to it in WPF, but on Xamarin.Forms it crashes with a TargetParameterCountException (Parameter count mismatch.)

### Steps to Reproduce
Add a binding to a path with a string index.  For example, `Text="{Binding Roles.PickList[DriverPilotTransport].Description}"`  Xamarin.Forms will fail to yield a value for the binding.  Crash occurs with or without 'single quotes'.

Simply run the attached sample.
 
### Expected Behavior
Evaluate the path using the string provided, 

### Actual Behavior
The path evaluation throws an exception when trying to use the string index accessor. 

### Basic Information
- Version with issue: Xamarin.Forms 4.2.0.709249
- Last known good version: Unknown
- IDE: VS 2019 16.3.2
- Platform Target Frameworks: 
  - iOS:  11.1
  - Android: 7.1
  - UWP:  16299 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms ONLY.
- Affected Devices: All.

### Screenshots
No screenshot available.

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3692880/App1.zip)

### Stack Trace
System.Reflection.TargetParameterCountException
  HResult=0x8002000E
  Message=Parameter count mismatch.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xamarin.Forms.BindingExpression.BindingExpressionPart.TryGetValue(Object source, Object& value)
   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)
   at Xamarin.Forms.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)
   at Xamarin.Forms.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, Boolean fromStyle)
   at Xamarin.Forms.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding)
   at App1.MainPage.InitializeComponent() in C:\source\repos\App1\App1\obj\Debug\netstandard2.0\MainPage.xaml.g.cs:line 26
   at App1.MainPage..ctor() in C:\source\repos\App1\App1\MainPage.xaml.cs:line 19
   at App1.App..ctor() in C:\source\repos\App1\App1\App.xaml.cs:line 14
   at App1.UWP.MainPage..ctor() in C:\source\repos\App1\App1.UWP\MainPage.xaml.cs:line 24
   at App1.UWP.App1_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage() in C:\source\repos\App1\App1.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 255
   at App1.UWP.App1_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\source\repos\App1\App1.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 476

**Comment by jfversluis** [comment]
Hi @davidpsaylor! Thanks for reporting!

This indeed doesn't work. What happens is that `DriverPilotTransport` is used as an actual string value which is used as the index. However, I don't believe this syntax works on WPF as well (for instance, see: https://stackoverflow.com/questions/16903244/wpf-binding-collection-with-index).

Could you maybe provide the WPF equivalent that you are trying to convert?

**Comment by davidpsaylor** [comment]
Hello, that binding does work on both WPF and Silverlight.  We actually reduced it down to `DriverPilotTransport` because Xamarin binding does not like spaces in there -- on WPF/SL we have it as `Driver/Pilot-Response`  with a slash and hyphen.

The stackoverflow you linked seems to be asking for a dynamic index, based on a variable. That is not what we are asking for.  We want a static string to be passed in as the index.

Below is the actual binding from the WPF XAML.
`<MyControls:MyToggleButton Content="Response"   IsChecked="{Binding CrewMemberResponseRole.EnumChoices[Driver/Pilot-Response].IsSelected, Mode=TwoWay, Converter={StaticResource nullableBoolConverter}}"               DataElement="{Binding CrewMemberResponseRole, Mode=TwoWay}" NVPNElement="{Binding CrewMemberResponseRole_NVPN, Mode=TwoWay}" HorizontalAlignment="Stretch" Margin="0"       Width="100" Height="60" Style="{DynamicResource ToggleButtonToggleListTwoState}" FontSize="14.667"  IsThreeState="False" FontFamily="Arial" />`

We expect it to be interpreted as a string and fed to the string indexer of PickList,  

```
public PickListMember this[string index]
{
    get
    {
        PickListMember member = null;

        var key = (index ?? "").ToKey();

        this.MemberLookup.TryGetValue(key, out member);

        return member;
    }
}
```

Please let me know if that is enough information.

Thank you for your help!

**Comment by StephaneDelcroix** [comment]
Thanks for the clarification. The problem here is the PickList contains 2 indexers (one taking string, one taking an int), and we resolve the wrong one.

Making the `int` indexer an explicit interface implementation "fixes" it. Use that as a workaround while we're fixing the bug.

**Comment by StephaneDelcroix** [comment]
also, stop the `#region` madness 🤪

**Comment by davidpsaylor** [comment]
Thanks!  Glad you will treat it as a defect.  I will use that workaround for now.
`#region` helps me look at just the method/property I want to and keep the scrollbar large.
