### ISSUE TITLE
[Bug] CollectionView XF4.3-pre3 crashes if EmptyView defined and ItemsSource is changed after ItemTemplate is changed

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#7943]
[CollectionViewItemsSourceEmptyView.zip](https://github.com/xamarin/Xamarin.Forms/files/3716370/CollectionViewItemsSourceEmptyView.zip)

### Description
After upgrade from XF4.2-sr2 to XF4.3-pre3, there is an issue with CollectionView: If you define an EmptyView, and you change the ItemTemplate and then the ItemsSource, the app crashes (Java.Lang.IllegalStateException
  Message=Observer md51558244f76c53b6aeda52c8a337f2c37.DataChangeObserver@7c308cb was not registered.)
If you don't define the EmptyView, it works fine. So the workaround is easy, don't use the EmptyView or provide your own.
I posted issue #7395 because the changed ItemTemplate was not applied. This is solved now (#7628), but because of this issue, if you run the app on XF4.2.0.848062 you don't see the ItemTemplate change, but at least it doesn't crash.
Only tested on Android.

### Steps to Reproduce
I made a very simple sample project to demonstrate this issue.
1. Run app. Click "Change Template", then "Change ItemsSource" => crash 
2. Run app again, but now click "Change ItemsSource" first, then "Change Template" => OK
3. Now click "Change ItemsSource" again => crash
3. Remove EmptyView from XAML and repeat step1 => OK

### Expected Behavior
No crash
### Actual Behavior
Crash
### Basic Information

- Version with issue: 4.3.0.851321-pre3
- Last known good version: 4.2.0.848062
- IDE: Visual Studio 16.2.5
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Confirmed that this is happening, only on Android

Full stack trace

>  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <e85f8f7e7f794240ac4758e206676ac4>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <e85f8f7e7f794240ac4758e206676ac4>:0 
  at Android.Support.V7.Widget.RecyclerView+Adapter.UnregisterAdapterDataObserver (Android.Support.V7.Widget.RecyclerView+AdapterDataObserver observer) [0x00031] in <7d32f6ecea2f48a59f0d551b445680b3>:0 
  at Xamarin.Forms.Platform.Android.DataChangeObserver.Stop (Android.Support.V7.Widget.RecyclerView+Adapter adapter) [0x0000b] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\DataChangeObserver.cs:33 
  at Xamarin.Forms.Platform.Android.ItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].UpdateItemsSource () [0x00024] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewRenderer.cs:260 
  at Xamarin.Forms.Platform.Android.ItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs changedProperty) [0x00020] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewRenderer.cs:214 
  at Xamarin.Forms.Platform.Android.StructuredItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs changedProperty) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\StructuredItemsViewRenderer.cs:19 
  at Xamarin.Forms.Platform.Android.SelectableItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs changedProperty) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewRenderer.cs:18 
  at Xamarin.Forms.Platform.Android.GroupableItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs changedProperty) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\GroupableItemsViewRenderer.cs:18 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:350 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:461 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x00042] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311 
  at Xamarin.Forms.ItemsView.set_ItemsSource (System.Collections.IEnumerable value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Items\ItemsView.cs:43 
  at CollectionViewItemsSourceEmptyView.MainPage.Button_Clicked_ItemsSource (System.Object sender, System.EventArgs e) [0x00001] in /Users/jfversluis/Downloads/CollectionViewItemsSourceEmptyView/CollectionViewItemsSourceEmptyView/MainPage.xaml.cs:58 
  at Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Button.cs:185 
  at Xamarin.Forms.ButtonElement.ElementClicked (Xamarin.Forms.VisualElement visualElement, Xamarin.Forms.Internals.IButtonElement ButtonElementManager) [0x0001f] in D:\a\1\s\Xamarin.Forms.Core\ButtonElement.cs:61 
  at Xamarin.Forms.Button.SendClicked () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Button.cs:171 
  at Xamarin.Forms.Platform.Android.ButtonElementManager.OnClick (Xamarin.Forms.VisualElement element, Xamarin.Forms.IButtonController buttonController, Android.Views.View v) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\ButtonElementManager.cs:25 
  at Xamarin.Forms.Platform.Android.FastRenderers.ButtonRenderer.Android.Views.View.IOnClickListener.OnClick (Android.Views.View v) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\ButtonRenderer.cs:71 
  at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v) [0x00011] in <4ed855fb65824da79e2edd6f6bb06c94>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.41(intptr,intptr,intptr)
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Observer crc643f46942d9dd1fff9.DataChangeObserver@1c09d95 was not registered.
	at android.database.Observable.unregisterObserver(Observable.java:69)
	at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:7017)
	at crc64ee486da937c010f4.ButtonRenderer.n_onClick(Native Method)
	at crc64ee486da937c010f4.ButtonRenderer.onClick(ButtonRenderer.java:95)
	at android.view.View.performClick(View.java:7140)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by samhouts** [comment]
closed by #7945
