### ISSUE TITLE
[Bug] Can't build after upgrade to XF 4.3 SR2

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [xamarin/Xamarin.Forms#8502]
### Description
Can't build after upgrade to XF 4.3 SR2

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mono.Cecil.PE.ByteBuffer.ReadByte()
   at Mono.Cecil.PE.ByteBuffer.ReadCompressedUInt32()
   at Mono.Cecil.SignatureReader..ctor(UInt32 blob, MetadataReader reader)
   at Mono.Cecil.MetadataReader.ReadSignature(UInt32 signature)
   at Mono.Cecil.MetadataReader.ReadSequencePoints(MethodDefinition method)
   at Mono.Cecil.Cil.PortablePdbReader.ReadSequencePoints(MethodDebugInformation method_info)
   at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
   at Mono.Cecil.ImmediateModuleReader.ReadMethodsSymbols(TypeDefinition type, ISymbolReader symbol_reader)
   at Mono.Cecil.ImmediateModuleReader.ReadTypesSymbols(Collection`1 types, ISymbolReader symbol_reader)
   at Mono.Cecil.ImmediateModuleReader.ReadSymbols(ModuleDefinition module)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

### Basic Information

- Version with issue: 4.3 SR2
- Last known good version: 4.3 SR1
- IDE: VS 16.3.9

**Comment by xamarindevelopervietnam** [comment]
downgrade to 4.3 SR1 then can build project again.

**Comment by xamarindevelopervietnam** [comment]
downgrade then upgrade again and now i can build it, closing this issue.

**Comment by jfversluis** [comment]
Probably/hopefully some kind of caching issue. Glad to see it's resolved!
