### ISSUE TITLE
[Bug][UWP] Exception in Forms.Init()

### ISSUE THREAD

**Issue by sude22** [xamarin/Xamarin.Forms#8533]
After upgrading to V4.3 from V4.2 the UWP app crashes during startup calling Forms.Init in OnLaunched. I already deleted all bin/obj directories, error still occurs.
Message:

`Error 0x261F.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30319.0&File=mscorrc.dll&Key=0x261F `
`Klasse nicht registriert (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))`
Stacktrace:
```
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider..ctor()
   at FSM.UWP.FSM_UWP_XamlTypeInfo.XamlTypeInfoProvider.get_OtherProviders() in C:\Projekte\FSM\FSM.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 765
   at FSM.UWP.FSM_UWP_XamlTypeInfo.XamlTypeInfoProvider.CheckOtherMetadataProvidersForName(String typeName) in C:\Projekte\FSM\FSM.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 797
   at FSM.UWP.FSM_UWP_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName) in C:\Projekte\FSM\FSM.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 162
   at FSM.UWP.FSM_UWP_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(String fullName) in C:\Projekte\FSM\FSM.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 90
   at FSM.UWP.App.GetXamlType(String fullName) in C:\Projekte\FSM\FSM.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 41
```

- Version with issue: V4.3.0.991211
- Last known good version:V4.2.0.910310
- IDE: VS2019
- UWP: 17134

**Comment by sude22** [comment]
I just created a new Xamarin project from scratch with the same versions, and the exception is not thrown. Must have something to do with my "old" project....

**Comment by hartez** [comment]
@sude22  Have you tried manually uninstalling the debug version of the old application on your development machine? (That is, Start Menu, find the application, right click and select 'Uninstall'.)

**Comment by valentinhuber** [comment]
Hello, had the same issue, try installing Xamarin.Forms into your UWP project

**Comment by sude22** [comment]
@hartez That did not work.
@valentinhuber Installing Xamarin.Forms nuget package to the UWP project solved the issue, thank you. Maybe I haven't seen this in the release notes of 4.3, or it could be added as a hint for people upgrading to 4.3.
