### ISSUE TITLE
[Bug] Tizen Tv - app crashes if collectionview is IsVisible is set to false

### ISSUE THREAD

**Issue by WanftMoon** [xamarin/Xamarin.Forms#8586]
## Description
If CollectionView.IsVisible is set to false, app crashes with error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.Tizen.Native.LinearLayoutManager.FindFirstGreaterOrEqualTo(IList`1 data, Int32 value)
   at Xamarin.Forms.Platform.Tizen.Native.LinearLayoutManager.LayoutItems(Rect bound, Boolean force)
   at Xamarin.Forms.Platform.Tizen.Native.CollectionView.<RequestLayoutItems>b__62_0()
   at Xamarin.Forms.Platform.Tizen.TizenPlatformServices.<>c__DisplayClass6_0.<BeginInvokeOnMainThread>b__0(Object o)
   at Tizen.Applications.TizenSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at Tizen.Applications.TizenSynchronizationContext.GSourceManager.Handler(IntPtr userData)
   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
   at Tizen.Applications.CoreApplication.Run(String[] args)
   at Tizen.Applications.CoreUIApplication.Run(String[] args)

### Steps to Reproduce

1.  Create page with collectionview, set its property IsVisible to false.
2.  app crashes

### Expected Behavior

collectionview to not be visible

### Actual Behavior

app crashes with null reference exception

### Basic Information

- Version with issue:
Xamarin.Forms(4.3.0.991211)
Tizen.Net (5.0.0.14629)
- Last known good version: N/A
- IDE: Visual Studio 2017 with tizen tools
- Platform Target Frameworks: 
  - Tizen:  Tizen.Net (5.0.0.14629)
- Android Support Library Version: 
- Nuget Packages:
Refit(5.0.15)
Tizen.Net(5.0.0.14629)
Xamarin.Essentials(1.3.1)
- Affected Devices:
Samsung Tizen TV v.5

**Comment by StephaneDelcroix** [comment]
please provide a repro project. thanks

**Comment by WanftMoon** [comment]
follows as requested: https://www.dropbox.com/s/1oytsd30ws4mtbs/8586.rar?dl=0

**Comment by rookiejava** [comment]
Hi @WanftMoon! Thank you for reporting. It's my bad. I've just noticed that I'm forgetting this. 
Anyway, I'll take a look and get back to you soon.

**Comment by sung-su** [comment]
#8586 and #8587 are not the same issue. 
The problem occurs in "IsVisible=False" state at app startup.
I will patch soon.

**Comment by rookiejava** [comment]
> #8586 and #8587 are not the same issue.
> The problem occurs in "IsVisible=False" state at app startup.
> I will patch soon.

I was sorry that both of the issues were late.
