### ISSUE TITLE
[Bug] Tizen Tv - App crashes if CollectionView.EmptyView is set while trying to set ItemsSource to null

### ISSUE THREAD

**Issue by WanftMoon** [xamarin/Xamarin.Forms#8587]
### Description
If CollectionView.EmptyView is not null while trying to set ItemsSource to null, app crashes with error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.Tizen.Native.ItemTemplateAdaptor.OnItemMeasureInvalidated(Object sender, EventArgs e)
   at Xamarin.Forms.VisualElement.InvalidateMeasureInternal(InvalidationTrigger trigger)
   at Xamarin.Forms.Grid.InvalidateMeasureInternal(InvalidationTrigger trigger)
   at Xamarin.Forms.Layout.OnChildMeasureInvalidated(VisualElement child, InvalidationTrigger trigger)
   at Xamarin.Forms.Layout.OnChildMeasureInvalidated(Object sender, EventArgs e)
   at Xamarin.Forms.VisualElement.InvalidateMeasureInternal(InvalidationTrigger trigger)
   at Xamarin.Forms.VisualElement.set_IsPlatformEnabled(Boolean value)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.SetElement(TElement newElement)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.Xamarin.Forms.Platform.Tizen.IVisualElementRenderer.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.Tizen.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.AddChild(Element child)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.SetElement(TElement newElement)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.Xamarin.Forms.Platform.Tizen.IVisualElementRenderer.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.Tizen.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.Tizen.Native.ItemTemplateAdaptor.CreateNativeView(Int32 index, EvasObject parent)
   at Xamarin.Forms.Platform.Tizen.Native.ItemTemplateAdaptor.CreateNativeView(EvasObject parent)
   at Xamarin.Forms.Platform.Tizen.Native.CollectionView.CreateEmptyView()
   at Xamarin.Forms.Platform.Tizen.Native.CollectionView.OnAdaptorChanged()
   at Xamarin.Forms.Platform.Tizen.ItemsViewRenderer.UpdateAdaptor(Boolean initialize)
   at Xamarin.Forms.Platform.Tizen.ItemsViewRenderer.UpdateItemsSource(Boolean initialize)
   at Xamarin.Forms.Platform.Tizen.VisualElementRenderer`1.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Xamarin.Forms.ItemsView.set_ItemsSource(IEnumerable value)

### Steps to Reproduce

1. Page with CollectiView with non emptyview
2.  Set ItemsSource to null
3.  app crashes

### Expected Behavior

empty view to be displayed

### Actual Behavior

app crahes

### Basic Information

- Version with issue:
Xamarin.Forms(4.3.0.991211)
Tizen.Net (5.0.0.14629)
- Last known good version: N/A
- IDE: Visual Studio 2017 with tizen tools
- Platform Target Frameworks: 
  - Tizen:  Tizen.Net (5.0.0.14629)
- Android Support Library Version: 
- Nuget Packages:
Refit(5.0.15)
Tizen.Net(5.0.0.14629)
Xamarin.Essentials(1.3.1)
- Affected Devices:
Samsung Tizen TV v.5

**Comment by StephaneDelcroix** [comment]
please attach a sample project. thanks

**Comment by WanftMoon** [comment]
follows as requested:
https://www.dropbox.com/s/mzk3qel3pevrx28/8587.rar?dl=0

**Comment by rookiejava** [comment]
Same as previous issue (#8586), I'm sorry I'm too late. :( 
Anyway, we'll check this issue and get back to you soon. Thanks.

/cc @sung-su PTAL

**Comment by sung-su** [comment]
#8586 and #8587 are not a same issue. 
And crash does not occur in the attached sample.

**Comment by rookiejava** [comment]
> #8586 and #8587 are not a same issue.
> And crash does not occur in the attached sample.

I do not mean that the reason of #8586 and #8587 is same. I was sorry that both of the issues were late.

**Comment by sung-su** [comment]
I reproduced and patched the problem situation.

**Comment by rookiejava** [comment]
This issue fixed in #9367.
