### ISSUE TITLE
[Bug] Issue with Android 6

### ISSUE THREAD

**Issue by georgeemr** [xamarin/Xamarin.Forms#8922]
### Description

We using a binding library, app crash in Android 6.
Library use C++ code.

`2-16 19:44:46.523 E/AndroidRuntime( 5138): Process: com.companyname.Xamarin.TestApp, PID: 5138
12-16 19:44:46.523 E/AndroidRuntime( 5138): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__android_log_vprint" referenced by "/data/app/com.companyname.Xamarin.TestApp-1/lib/x86/libmonodroid.so"...
12-16 19:44:46.523 E/AndroidRuntime( 5138): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
12-16 19:44:46.523 E/AndroidRuntime( 5138): 	at java.lang.System.loadLibrary(System.java:1076)
12-16 19:44:46.523 E/AndroidRuntime( 5138): 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:59)`

### Steps to Reproduce

1. Add binding library (AAR) with internal code generated in C++.
2. Add as project library.
3. When the app starts (because it is static) it crash with the image I upload.

This doesn't happen with a lower android (4.1) or higher version, just with Android 6.

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 6

### Screenshots

![image](https://user-images.githubusercontent.com/3822009/70954981-dc062580-2034-11ea-9427-2583fe1f2bbd.png)

**Comment by knocte** [comment]
Maybe this should have been filed in Xamarin.Android repo?
