### ISSUE TITLE
[Bug] Cannot start debugging session Xamarin.Forms due to locked NuGet folder

### ISSUE THREAD

**Issue by robertsundstrom** [xamarin/Xamarin.Forms#9001]
Cannot debug iOS apps in Visual Studio Preview for Windows because the Xamarin.Forms NuGet directory (.nuget\packages\xamarin.forms) is locked.

Hot Reload is enabled. If that makes a difference.

```The connection with the debugger has been lost. The target application may have exited.
System.IO.IOException: The process cannot access the file 'C:\Users\robert\.nuget\packages\xamarin.forms\4.4.0.991265\lib
etstandard2.0\Xamarin.Forms.Core.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Debugging.VisualStudio.SymbolsAdapter.FindPathInDll(String path) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 184
   at Mono.Debugging.VisualStudio.SymbolsAdapter.RefreshSymbolPath(String assemblyPath) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 71
   at Mono.Debugging.VisualStudio.SymbolsAdapter.OnAssemblyLoaded(Object sender, AssemblyEventArgs e) in E:\A\_work\3718\s\src\Debugging.VisualStudio.Vsix\Integration\SymbolsAdapter.cs:line 62
   at Mono.Debugging.Client.DebuggerSession.OnAssemblyLoaded(String assemblyLocation) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:line 1191
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleAssemblyLoadEvents(AssemblyLoadEvent[] events) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2070
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1708
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in E:\A\_work\3718\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1639
```
The only way to temporarily fix this until the folder is locked again is to close Visual Studi. Delete the folder. Restart the app.

[Similar](https://xamarin.github.io/bugzilla-archives/43/43738/bug.html)

**Comment by robertsundstrom** [comment]
The same happens for Android.

**Comment by samhouts** [comment]
@robertsundstrom This is an issue in VS 16.5 P1. It will be fixed in the next preview. This is being tracked here: https://developercommunity.visualstudio.com/content/problem/846153/the-connection-with-the-debugger-has-been-lost-the-1.html. Thanks!
