### ISSUE TITLE
[Bug] Xamarin.Forms.Controls build error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#9066]
### Description

Unable to build Xamarin.Forms.Controls:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "XamlCTask" task failed unexpectedly.
System.MissingMethodException: Method not found: 'Void Xamarin.Forms.Xaml.RootNode..ctor(Xamarin.Forms.Xaml.XmlType, System.Xml.IXmlNamespaceResolver)'.

Server stack trace: 
   at Xamarin.Forms.Build.Tasks.ILRootNode..ctor(XmlType xmlType, TypeReference typeReference, IXmlNamespaceResolver nsResolver)
   at Xamarin.Forms.Build.Tasks.XamlTask.ParseXaml(Stream stream, TypeReference typeReference)
   at Xamarin.Forms.Build.Tasks.XamlCTask.Execute(IList`1& thrownExceptions)
   at Xamarin.Forms.Build.Tasks.XamlTask.Execute()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Xamarin.Forms.Controls	C:\Source\Xamarin.Forms\.nuspec\Xamarin.Forms.targets	110	

### environment:
- Visual studio 2019.5 preview 1
- latest master build on Xamarin Forms

I have cleaned .nuget/packages folder and deleted bin and obj folders.

**Comment by VladislavAntonyuk** [comment]
if comment XamlCTask (line 110-117) build succeeded

**Comment by PureWeen** [comment]
@VladislavAntonyuk this is all compiling and deploying for me without any issues using 16.5 P2 
So I'm thinking your issue is most likely resolved.  

If you are still having this issue once P2 comes out then we can re-open and investigate
