### ISSUE TITLE
[Bug][UWP] Loading wrong Xamarin.Forms.Core.dll

### ISSUE THREAD

**Issue by kapsiR** [xamarin/Xamarin.Forms#9652]
### Description
It seems there is an issue with loading the wrong `Xamarin.Forms.Core.dll` on UWP which leads to a `System.MissingMethodException` or a compiler error `Error CS0029  Cannot implicitly convert type 'Xamarin.Forms.Color' to 'System.Drawing.Color'`.

This happens only on UWP. 

### Steps to Reproduce

1. Create a new Xamarin Forms project (Only UWP necessary to reproduce)
   - Target `.NET Standard 2.0`
   - UWP-Target `16299`
2. Update to latest Xamarin Forms stable (4.4.0.991640)
3. Add an implicit `Color` conversion from `System.Drawing.Color` to `Xamarin.Forms.Color` or the other way around 

### Expected Behavior
No exception or compiler error

### Actual Behavior
 - When writing the `Color` conversion into the UWP-Project, then there is a compiler error.
 - When writing the `Color` conversion into the Xamarin class library, then there is a runtime error.

```
Method not found: 'System.Drawing.Color Xamarin.Forms.Color.op_Implicit(Xamarin.Forms.Color)'.

at MethodNotFoundRepro.App.App.TestBug() in \MethodNotFoundRepro\MethodNotFoundRepro.App\MethodNotFoundRepro.App\App.xaml.cs:line 22
   at MethodNotFoundRepro.App.App.OnStart() in \MethodNotFoundRepro\MethodNotFoundRepro.App\MethodNotFoundRepro.App\App.xaml.cs:line 16
   at Xamarin.Forms.Platform.UWP.WindowsBasePage.LoadApplication(Application application)
   at MethodNotFoundRepro.App.UWP.MainPage..ctor() in \MethodNotFoundRepro\MethodNotFoundRepro.App\MethodNotFoundRepro.App.UWP\MainPage.xaml.cs:line 24
   at MethodNotFoundRepro.App.UWP.MethodNotFoundRepro_App_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage() in \MethodNotFoundRepro\MethodNotFoundRepro.App\MethodNotFoundRepro.App.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 311
   at MethodNotFoundRepro.App.UWP.MethodNotFoundRepro_App_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in \MethodNotFoundRepro\MethodNotFoundRepro.App\MethodNotFoundRepro.App.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 1407
```

### Basic Information

- Version with issue: `4.4.0.991220-pre3` (introduced with PR [#7079](https://github.com/xamarin/Xamarin.Forms/pull/7079))
- Last known good version: `4.4.0.991210-pre2` or stable `4.3.0.991250`
- New known good version: `4.5.0.282-pre4` (working again with PR [#9132](https://github.com/xamarin/Xamarin.Forms/pull/9132))
- IDE: VS 2019
- Platform Target Frameworks: 
  - UWP:  >= 16299
- Nuget Packages: NETStandard.Library, Xamarin.Essentials, Xamarin.Forms

### Reproduction Link

[XamarinMethodNotFoundRepro](https://github.com/kapsiR/XamarinMethodNotFoundRepro)

### Workaround

Use latest Xamarin Forms `4.5.0.282-pre4` or `4.4.0.991210-pre2` or the stable `4.3.0.991250`

**Comment by PureWeen** [comment]
We're close to releasing 4.5 stable so for now we aren't planning on backporting the fix to 4.4
