### ISSUE TITLE
[Bug] Illegal characters in path on Android after update to VS 16.5.0

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#9996]
### Description

After updating to Visual Studio 16.5, Android apps fail to build with the error "Illegal characters in path" from Xamarin.Android.Tasks.Crunch

### Steps to Reproduce

1. Rebuild after upgrading
2. Tried a full bin/obj clean
3. 

### Expected Behavior
Builds

### Actual Behavior
```
Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Xamarin.Android.Tasks.Crunch.<>c.<RunTaskAsync>b__19_1(ITaskItem x)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at Xamarin.Android.Tasks.AsyncTaskExtensions.WhenAll[TSource](AsyncTask asyncTask, IEnumerable`1 source, Action`1 body)
   at Xamarin.Android.Tasks.Crunch.<RunTaskAsync>d__19.MoveNext()	Max.Droid	
```		

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 16.4
- Platform Target Frameworks:  
  - Android:  Pie, 9.0

**Comment by ianvink** [comment]
There is a discussion on the issue here: https://forums.xamarin.com/discussion/175824/r8-enabled-gives-build-error-compilation-cant-be-completed-because-some-library-classes-ar? , others are getting the same issues.

**Comment by ianvink** [comment]
It seems to be related to **Dex** and **aapt2** ? I kept playing with settings until I found one that worked:

Related: R8 : error : Compilation can't be completed because some library classes are missing.

![2020-03-17 12_22_43-Maximizer (Running) - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/112916/76893866-50c24900-684a-11ea-871d-26787021fddc.png)

**Comment by guillermo-gerard** [comment]
After applying the workaround I can get a proper build but I've got errors when trying to deploy the app to debug.
Even when the deploy is done, I'm getting this at runtime (And I know I'm not the only one):
![image](https://user-images.githubusercontent.com/50535806/77110617-9591df80-6a04-11ea-8bf8-da41f33aa747.png)
